cdnjs/cdnjs

ajax/libs/bootstrap-year-calendar/package.json

close #10120, cc @Paul-DS
Pull request for issue: #10120
* Git repository (required): https://github.com/Paul-DS/bootstrap-year-calendar
* Official website (optional, not the repository): http://www.bootstrap-year-calendar.com/
* NPM package url (optional): https://www.npmjs.com/package/bootstrap-year-calendar
- Count of stars: 131
- Count of forks: 62
- Downloads in the last day: 3
- Downloads in …

Add bootstrap-year-calendar w/ npm auto-update via single package.json

---

ajax/libs/mathjax-mhchem/package.json

This is moving MathJax/mhchem to cdnjs, because cdn.mathjax.org will be closed (https://www.mathjax.org/cdn-shutting-down/).
This is adding a new library via a single package.json with auto-update config.
I intentionally do _not_ include a .min.js file, because MathJax loads its extension via `extensions: ["[Contrib]/mhchem/mhchem.js"]` and `mhchem.js` always was the minified file. Users are used to request/include `mhchem.js` in order to get a minified file.
The extension is popular. It is used by StackExchange.
* Git repository (required): https://github.com/mhchem/MathJax-mhchem
* Official website (optional, not the repository): https://mhchem.github.io/MathJax-mhchem/
* License and its reference: Apache 2.0
* Popularity: Used by chemistry.stackexchange.com with 50k visits per day …

[author] Add mathjax-mhchem w/ git auto-update via single package.json

---

ajax/libs/formjs/package.json

Pull request for issue: #10710
* Git repository (required): https://github.com/the94air/formjs
* Official website (optional, not the repository): https://form.js.org/
* License and its reference: MIT [reference](https://github.com/the94air/formjs/blob/master/License.txt)
- Count of watchers: 1
- Count of stars: 3 …

Add formjs w/ git auto-update via single package.json

---

README.md

Apparently the companies where mentioned first and later
moved to the unordered list. This left an artifact which is
solved by this commit.

Minor grammatical correction

---

ajax/libs/cytoscape/package.json

Pull request for issue: #11052
@cdnjs/intern3 Please help me review this PR. Thanks.
* Git repository (required): https://github.com/cytoscape/cytoscape.js
* Official website (optional, not the repository): http://js.cytoscape.org
* NPM package url (optional): https://www.npmjs.com/package/cytoscape
* License and its reference: MIT, https://github.com/cytoscape/cytoscape.js/blob/master/LICENSE

Fix license of cytoscape from LGPL to MIT, close #11052

---

ajax/libs/cytoscape/package.json

Pull request for issue: cc #11052
* Git repository (required): https://github.com/cytoscape/cytoscape.js
* Official website (optional, not the repository): http://js.cytoscape.org
* NPM package url (optional): https://www.npmjs.com/package/cytoscape
* License and its reference: MIT, https://github.com/cytoscape/cytoscape.js/blob/master/LICENSE

Update author, homepage info of cytoscape

---

ajax/libs/jsSocials/package.json

close #9847, cc @tabalinas
Pull request for issue: #9847
* Git repository (required): https://github.com/tabalinas/jssocials
* NPM package url (optional): https://www.npmjs.com/package/jssocials
* Official website (optional, not the repository): http://js-socials.com/
- Count of watchers: 27
- Count of stars: 261
- Count of forks: 55
- Downloads in the last day: 24
- Downloads in the last week: 174 …

Add jsSocials w/ git auto-update via single package.json

---

ajax/libs/background-check/package.json

Pull request for issue: #10609
* Git repository (required): https://github.com/kennethcachia/background-check
* Official website (optional, not the repository):http://www.kennethcachia.com/background-check/
- Count of watchers: 83
- Count of stars: 2906
- Count of forks: 221

Add background-check w/ git auto-update via single package.json

---

ajax/libs/across-tabs/package.json

* Git repository (required): https://github.com/wingify/across-tabs
* Official website (optional, not the repository): http://engineering.wingify.com/across-tabs/introduction.html
* NPM package url (optional): https://www.npmjs.com/package/across-tabs
* License and its reference: [MIT](https://github.com/wingify/across-tabs/blob/master/LICENSE)
- Count of watchers: 40
- Count of stars: 774
- Count of forks: 18 …

[author][new] Add across-tabs w/ npm auto-update via single package.json

---

ajax/libs/videojs-ima/package.json

Pull request for issue: #10491
Related issue(s): googleads/videojs-ima#347
* Git repository (required): https://github.com/googleads/videojs-ima
* NPM package url (optional): https://www.npmjs.com/package/videojs-ima
* License and its reference: [Apache-2.0](https://github.com/googleads/videojs-ima/blob/master/LICENSE)
- Count of watchers: 44
- Count of stars: 162
- Count of forks: 110
- Downloads in the last day: 17
- Downloads in the last week: 146
- …

Add videojs-ima w/ git auto-update via single package.json

---

ajax/libs/can.js/package.json

Adding CanSJ 3 [npm:can](https://www.npmjs.com/package/can).
We were previously added to your site under [can.js](https://cdnjs.com/libraries/can.js) (we used to be named [npm:canjs](https://www.npmjs.com/package/canjs)), though it has not been updated in quite some time (and those files are actually from [can-jquery](https://www.npmjs.com/package/can-jquery). Should something be done about the now incorrectly named can.js?
Checklist for **Pull request** follows the conventions.
* Git repository (required): https://github.com/canjs/canjs
* Official website (optional, not the repository): http://canjs.com/
* NPM package …

[author][new] Add can w/ npm auto-update via single package.json

---

vega-tooltip/package.json

* Git repository (required): https://github.com/vega/vega-tooltip
* NPM package url (optional): https://www.npmjs.com/package/vega-tooltip
* License and its reference: BSD-3
- Count of watchers: 8
- Count of stars: 16
- Count of forks: 4
- Downloads in the last day: 16
- Downloads in the last week: 25
- Downloads in the last month: 73
* This is the plugin for vega and vega-lite modules (https://github.com/vega/vega and https://github.com/vega/vega-lite) that provides tooltip to extend the capability.

[author][new] add vega-tooltip w/ npm auto-update via single package.json

---

ajax/libs/floating.js/package.json

close #9848, cc @Haroenv
Pull request for issue: #9848
* Git repository (required): https://github.com/Haroenv/floating.js/
* Official website (optional, not the repository): https://haroen.me/floating.js/
* NPM package url (optional): https://www.npmjs.com/package/floating.js
- Count of stars: 150
- Downloads in the last day: 3
- Downloads in the last week: 34
- Downloads in …

Add floating.js w/ npm auto-update via single package.json

---

ajax/libs/isomorphic-fetch/package.json

close #11054, cc @matthew-andrews
Pull request for issue: #11054
* Git repository (required): https://github.com/matthew-andrews/isomorphic-fetch/
* NPM package url (optional): https://www.npmjs.com/package/isomorphic-fetch
- Count of watchers: 60
- Count of stars: 4,067
- Count of forks: 142
- Downloads in the last day: 134,051
- Downloads in the last week: 710,421
- …

Add isomorphic-fetch w/ git auto-update via single package.json

---

ajax/libs/preact-compat/package.json

Adding preact-compat@3.15.0 to cdnjs
Related issue(s): developit/preact-compat#281
* Git repository (required): https://github.com/developit/preact-compat 
* NPM package url (optional): https://www.npmjs.com/package/preact-compat
- Count of stars: 320
- Count of forks: 57
- Downloads in the last day: 948 …

[new] Add preact-compat w/ npm auto-update via single package.json

---

ajax/libs/d3-array/package.json
ajax/libs/d3-axis/package.json
ajax/libs/d3-brush/package.json
ajax/libs/d3-chord/package.json
ajax/libs/d3-collection/package.json
ajax/libs/d3-color/package.json
ajax/libs/d3-dispatch/package.json
ajax/libs/d3-drag/package.json
ajax/libs/d3-ease/package.json
ajax/libs/d3-force/package.json
ajax/libs/d3-format/package.json
ajax/libs/d3-geo/package.json
ajax/libs/d3-hierarchy/package.json
ajax/libs/d3-interpolate/package.json
ajax/libs/d3-path/package.json
ajax/libs/d3-polygon/package.json
ajax/libs/d3-quadtree/package.json
ajax/libs/d3-random/package.json
ajax/libs/d3-request/package.json
ajax/libs/d3-scale/package.json
ajax/libs/d3-selection/package.json
ajax/libs/d3-shape/package.json
ajax/libs/d3-time-format/package.json
ajax/libs/d3-time/package.json
ajax/libs/d3-timer/package.json
ajax/libs/d3-transition/package.json
ajax/libs/d3-voronoi/package.json
ajax/libs/d3-zoom/package.json

Pull request for issue: #11025
* Git repository (required): https://github.com/d3
* Official website (optional, not the repository): https://d3js.org
* License and its reference: BSD-3-Clause https://opensource.org/licenses/BSD-3-Clause
- Count of watchers: > 3,100
- Count of stars: > 63,000
- Count of forks: > 16,000

[new] Add d3 v4 modules w/ npm auto-update via single package.json

---

ajax/libs/mdui/package.json

* Git repository (required): https://github.com/zdhxiong/mdui
* Official website (optional, not the repository): http://mdui.org/
* NPM package url (optional): https://www.npmjs.com/package/mdui
- Count of watchers: 37
- Count of stars: 1032
- Count of forks: 93
- Downloads in the last day: 6
- Downloads in the last week: 17
- Downloads in the last month: 70

[Author] [New] Add mdui@0.2.0 w/ npm auto-update via single package.json

---

tools/fixFormat.js

Pull request for issue: #11185 
As the error message shown in #11185, I update `tools/fixFormat.js` to fix it.

update tools/fixFormat.js to fix #11185

---

ajax/libs/script.js/package.json

ref: https://github.com/ded/script.js/blob/05860e2fcd07259da61319a1a30b2a9ad5f19d3a/src/header.js#L4

Add license of script.js, cc #5500

---

ajax/libs/PKI.js/package.json

ref: https://github.com/PeculiarVentures/PKI.js/blob/master/LICENSE, https://github.com/PeculiarVentures/PKI.js#license

Add license of PKI.js

---

ajax/libs/mathjax/package.json

The `latest.js` file was missing from there autoupdate list; this is a new file in 2.7.1 that was not in previous versions.

Update auto-update config for MathJax

---

ajax/libs/davis.js/package.json

ref: https://github.com/olivernn/davis.js/blob/0da596aa0b13f041f71c76bef828cc23f54455ef/lib/header.js#L4

Add license of davis.js, cc #5500

---

ajax/libs/mathjax/2.7.1/latest.js

Add missing file to MathJax 2.7.1.
This adds the file `latest.js` that was added in 2.7.1 but was not in the `package.json` file.  See PR #11254.
- Downloads in …

Add missing latest.js file to MathJax 2.7.1

---

ajax/libs/CSS-Mint/package.json

Pull request for issue: #10114
* Git repository (required): https://github.com/ArunMichaelDsouza/CSS-Mint
* Official website (optional, not the repository): https://arunmichaeldsouza.github.io/CSS-Mint/
* NPM package url (optional): https://www.npmjs.com/package/css-mint
- Count of stars: 117
- Count of forks: 8
* [ …

Add CSS-Mint w/ git auto-update via single package.json

---

ajax/libs/dio/package.json

Pull request for issue: #11331
* Git repository (required): https://github.com/thysultan/dio.js
* Official website (optional, not the repository): https://dio.js.org
* NPM package url (optional): https://www.npmjs.com/package/dio.js
- Count of stars: 382
- Count of forks: 20
- Downloads in the last day: 173
- Downloads in the last week: 482
- Downloads in the last month: 803

Update auto-update filemap of dio

---

ajax/libs/slim-select/package.json

Pull request for issue: #11189 
* Git repository (required): https://github.com/brianvoe/slim-select
* Official website (optional, not the repository): http://slimselectjs.com/
* NPM package url (optional): https://www.npmjs.com/package/slim-select
- Count of stars: 28
- Count of forks: 1
- Downloads in the last day: 128
- Downloads in the last week: 532 …

Add slim-select w/ npm auto-update via single package.json

---

ajax/libs/ngclipboard/package.json

close #11344 
Pull request for issue: #11344
Glue library for employing clipboard.js (already hosted here) in angular.js
* Git repository (required): https://github.com/sachinchoolur/ngclipboard
* Official website (optional, not the repository): https://sachinchoolur.github.io/ngclipboard/
* NPM package url (optional): https://www.npmjs.com/package/ngclipboard
* License and its reference: MIT https://github.com/sachinchoolur/ngclipboard/blob/master/LICENSE
- Count of stars: 309
- Count of forks: 65
- Downloads in the last day: 1051
- Downloads in the last week: 5723
- Downloads in the last month: 21624

Add ngclipboard w/ npm auto-update via single package.json

---

ajax/libs/qrious/package.json

* Git repository (required): https://github.com/neocotic/qrious
* NPM package url (optional): https://www.npmjs.com/package/qrious
* License and its reference: GPL-3.0
- Count of stars: 310
- Count of forks: 41
- Downloads in the last day: 83
- Downloads in the last week: 1663
- Downloads in the last month: 5315

[author] [new] Add qrious w/ npm auto-update via single package.json

---

ajax/libs/oojs-ui/package.json

Pull request for issue: #11350
**Git repository url:** https://phabricator.wikimedia.org/diffusion/GOJU
**npm:** https://www.npmjs.com/package/oojs-ui
**License (List them all if it's multiple):** MIT
**Official homepage:** https://www.mediawiki.org/wiki/OOjs_UI
- Downloads in the last day: 675
- Downloads in the last week: 1406
- Downloads in the last month: 3180

Update auto-update filemap of oojs-ui

---

ajax/libs/angular-numeraljs/1.0.0/angular-numeraljs.js
ajax/libs/angular-numeraljs/1.0.0/angular-numeraljs.min.js
ajax/libs/angular-numeraljs/1.0.1/angular-numeraljs.js
ajax/libs/angular-numeraljs/1.0.1/angular-numeraljs.min.js
ajax/libs/angular-numeraljs/1.0.2/angular-numeraljs.js
ajax/libs/angular-numeraljs/1.0.2/angular-numeraljs.min.js
ajax/libs/angular-numeraljs/1.0.3/angular-numeraljs.js
ajax/libs/angular-numeraljs/1.0.3/angular-numeraljs.min.js
ajax/libs/angular-numeraljs/2.0.1/angular-numeraljs.js
ajax/libs/angular-numeraljs/2.0.1/angular-numeraljs.min.js
ajax/libs/angular-numeraljs/package.json

Pull request for issue: #9493
Related issue(s): #10086 #11170
* Git repository (required): https://github.com/baumandm/angular-numeraljs
* NPM package url (optional): https://www.npmjs.com/package/angular-numeraljs
- Count of watchers: 4
- Count of stars: 39
- Count of forks: 20
- Downloads in the last day: 139
- Downloads in the last week: 922 …

Add angular-numeraljs /w npm auto-update

---

ajax/libs/PKI.js/package.json

Pull request for issue: #11268
ref : https://github.com/PeculiarVentures/PKI.js/blob/master/package.json#L15
https://github.com/PeculiarVentures/PKI.js/blob/master/package.json#L54-L67
https://pkijs.org/

Update repository url, homepage, keyword info of PKI.js

---

ajax/libs/findAndReplaceDOMText/package.json

Pull request for issue: Resolves #11099
* Git repository (required): https://github.com/padolsey/findAndReplaceDOMText
* NPM package url (optional): https://www.npmjs.com/package/findandreplacedomtext
* License and its reference: unlicense
- Count of stars: 475
- Count of forks: 82
- Downloads in the last day: 161
- Downloads in the last week: 726 
- Downloads in the last month: 2,781

[new] Add findAndReplaceDOMText via single package.json w/ git auto-update

---

ajax/libs/videojs-overlay/package.json

closes: #9826
Pull request for issue: #9826
* Git repository (required): [https://github.com/brightcove/videojs-overlay](https://github.com/brightcove/videojs-overlay)
* NPM package url (optional): https://www.npmjs.com/package/videojs-overlay
* License and its reference: [Apache 2.0](https://github.com/brightcove/videojs-overlay/blob/master/LICENSE)
- Count of watchers:36
- Count of stars:84
- Count of forks:51
* NPM …

Add videojs-overlay w/ git auto-update via single package.json

---

ajax/libs/knockout-es5/0.4.6/knockout-es5-clean.js
ajax/libs/knockout-es5/0.4.6/knockout-es5-clean.min.js
ajax/libs/knockout-es5/0.4.6/knockout-es5.js
ajax/libs/knockout-es5/0.4.6/knockout-es5.min.js
ajax/libs/knockout-es5/package.json

close #7619
Pull request for issue: #7619
* Git repository (required): https://github.com/SteveSanderson/knockout-es5
* Official website (optional, not the repository): http://blog.stevensanderson.com/2013/05/20/knockout-es5-a-plugin-to-simplify-your-syntax/
- Count of stars: 157
- Count of forks: 39
- Downloads in …

Add knockout-es5@0.4.6 w/ git auto-update

---

ajax/libs/cell/package.json

* Git repository (required): https://github.com/intercellular/cell
* Official website (optional, not the repository): https://celljs.org
* License and its reference: MIT https://github.com/intercellular/cell/blob/develop/LICENSE
- Count of watchers: 28
- Count of stars: 732
- Count of forks: 40

[New] Add cell w/ git auto-update via single package.json

---

ajax/libs/inferno/package.json

Pull request for issue: #11489

Update inferno repository url and homepage

---

ajax/libs/reactstrap/package.json

Pull request for issue: #11470 
Related issue(s): reactstrap/reactstrap#476 #11483
* Git repository (required): https://github.com/reactstrap/reactstrap.git
* Official website (optional, not the repository): https://reactstrap.github.io/
* NPM package url (optional): https://www.npmjs.com/package/reactstrap
* License and its reference: MIT ref: [in repo](https://github.com/reactstrap/reactstrap/blob/master/LICENSE) and [in package.json](https://github.com/reactstrap/reactstrap/blob/d153a7801bb88f117a5e6c92b4bf838c9af3feb5/package.json#L …

[author] [new] Add reactstrap w/ npm auto-update via single package.json

---

.gitignore
ajax/libs/europa/package.json

* Git repository (required): https://github.com/NotNinja/europa
* NPM package url (optional): https://www.npmjs.com/package/europa
- Count of watchers: 4
- Count of stars: 116
- Count of forks: 21
- Downloads in the last week: 6
- Downloads in the last month: 37

[author] [new] Add europa w/ npm auto-update via single package.json

---

ajax/libs/react-uwp/package.json

Add react-uwp via single package.json w/ git auto-update
Close #11448
* Git repository (required):  https://github.com/myxvisual/react-uwp
* Official website (optional, not the repository): https://www.react-uwp.com
* NPM package url (optional): https://www.npmjs.com/package/react-uwp
- Count of stars: 122
- Downloads in the last day: 56 …

[New][Author] Add react-uwp w/ git auto-update via single package.json 

---

ajax/libs/pipes-core/package.json

* Git repository (required): https://github.com/pipesjs/core
* Official website (optional, not the repository): http://pipes.js.org/core
- Count of watchers: 1
- Count of stars: 2

[New][author] Add pipes-core w/ git auto-update via single package.json

---

ajax/libs/nestable2/package.json

* Git repository (required): https://github.com/RamonSmit/Nestable2
* NPM package url (optional): https://www.npmjs.com/package/nestable2
* License and its reference: https://github.com/RamonSmit/Nestable2/blob/master/LICENSE
- Count of stars: 54
- Count of forks: 28
- Downloads in the last day: 23
- Downloads in the last week: 146
- …

[New][Author] Add nestable2 w/ git auto-update via single package.json

---

ajax/libs/webpack-cesium/package.json

Pull request for issue: #11442
Related issue(s): None
* Git repository: 
- https://github.com/AnalyticalGraphicsInc/cesium
- https://github.com/DigitalArsenal/webpack-cesium
* Official website (optional, not the repository): https://cesiumjs.org
* NPM package url: 
- https://www.npmjs.com/package/webpack-cesium
- https://www.npmjs.com/package/cesium
* License and its reference: 
- [ISC](http://www.isc.org/downloads/software-support-policy/isc-license)
- [Apache 2](http://www.apache.org/licenses/LICENSE-2.0.html)
* GitHub / Bitbucket popularity: 
- Count of watchers: 268
- Count of stars: 2,268
- Count of forks: 1,092
* NPM download stats:

[New][Author] Add webpack-cesium@1.31.2 w/ npm auto-update

---

ajax/libs/react-transition-group/package.json

Pull request for issue: #11487 
Related issue(s): 
Close #11487 
cc @jquense
* Git repository (required): https://github.com/reactjs/react-transition-group
* NPM package url (optional): https://www.npmjs.com/package/react-transition-group
* License and its reference: [in repo](https://github.com/reactjs/react-transition-group/blob/master/LICENSE)
- Count of stars: 827
- Count of forks: 56 …

Add react-transition-group w/ npm auto-update via single package.json

---

ajax/libs/react-widgets/package.json

close #11535
Pull request for issue: #11535
Related issue(s): # # @PeterDaveHello
* Git repository (required): https://github.com/jquense/react-widgets
* Official website (optional, not the repository): https://jquense.github.io/react-widgets/docs
* NPM package url (optional): https://npmjs.org/package/react-widgets
- Count of watchers: 52
- Count of stars: 1405
- Count of forks: 244
- Downloads in the last day: 298
- Downloads in …

Add react-widgets w/ npm auto-update via single package.json

---

ajax/libs/ng-dropzone/package.json

close #11476, cc @thatisuday
Pull request for issue: #11476 
* Git repository (required): https://github.com/thatisuday/ng-dropzone
* Official website (optional, not the repository): http://www.dropzonejs.com
* NPM package url (optional): https://www.npmjs.com/package/ngdropzone
- Count of stars: 71
- Count of forks: 18
- Downloads in the last day: 69 …

Add ng-dropzone w/ git auto-update via single package.json

---

ajax/libs/notie/package.json

Update the repository's url, homepage, author, keywords, description
close #11555
Pull request for issue: #11555
* Git repository url: https://github.com/jaredreich/notie
* npm: https://www.npmjs.com/package/notie
* License (List them all if it's multiple): MIT
* Official homepage: https://jaredreich.com/notie
- Count of watchers: 134
- Count of stars: 5562
- Count of forks: 347
- Downloads in the last day: 161 …

Update package.json of notie

---

ajax/libs/video.js/package.json

close #11557
Pull request for issue: #11557 
* Git repository (required): https://github.com/videojs/video.js
* Official website (optional, not the repository): http://www.videojs.com
* NPM package url (optional): https://www.npmjs.com/package/video.js
- Count of watchers: 1080
- Count of stars: 16867
- Count of forks: 4749
- Downloads in the last day: 9934
- Downloads in the last week: 25,444
- …

Update video.js auto-update config & add more keywords

---

ajax/libs/elfinder/package.json

Several files are missing at this time. That fix.
Related PR: #11443
* Git repository (required): https://github.com/Studio-42/elFinder
* Official website (optional, not the repository): https://studio-42.github.io/elFinder/
* License and its reference: 3-clauses BSD license
- Count of watchers: 218
- Count of stars: 2430
- Count of forks: 982 …

[Author] Update auto-update config of elfinder

---

.gitignore

Pull request for issue: #None
* Git repository (required): https://github.com/primer/primer-css
* Official website (optional, not the repository): http://primercss.io/
* NPM package url (optional): https://www.npmjs.com/package/primer-css
- Count of watchers: 182
- Count of stars: 5791
- Count of forks: 412
- Downloads in the last day: 4421
- Downloads in the last week: 10957 …

Update .gitignore to exclude Primer alpha versions

---

ajax/libs/tween.js/package.json

close #11595
Pull request for issue: #11595
* Git repository (required): https://github.com/tweenjs/tween.js/
* NPM package url (optional): https://www.npmjs.com/package/@tweenjs/tween.js
- Count of watchers: 194
- Count of stars: 4422
- Count of forks: 730
- Downloads in the last day: 334
- Downloads in the last week: 991 …

Update tween.js auto-update config

---

ajax/libs/spellbook/package.json

Changed my contact mail.
Thank you.

[Update][Author] Update spellbook author contact

---

ajax/libs/cssobj/package.json

close #11548
Pull request for issue: #11548 
Related issue(s): #11601 #11623
* Git repository (required):  https://github.com/cssobj/cssobj
* Official website (optional, not the repository): https://cssobj.github.io/cssobj-demo/
* NPM package url (optional): https://www.npmjs.com/package/cssobj
- Count of stars: 186
- Downloads in the last day: 7
- Downloads in the last week: 116
- …

Add cssobj w/ npm auto-update via single package.json

---

ajax/libs/bootstrap-table/package.json

Pull request for issue: none
Related issue(s): none
---
Update homepage url in `package.json`. The old url is broken (404).
Old: `http://wenzhixin.net.cn/p/bootstrap-table/`
New: …

Update bootstrap-table homepage url

---

ajax/libs/sinon.js/package.json

close #11612
Pull request for issue: #11612
* Git repository (required): http://www.github.com/sinonjs/sinon
* Official website (optional, not the repository): http://sinonjs.org/
* NPM package url (optional): https://www.npmjs.com/package/sinon
* License and its reference: https://github.com/sinonjs/sinon/blob/master/LICENSE
- Count of watchers: 87
- Count of stars: 4467
- Count of forks: 549
- Downloads in the last day: 153.342 …

Add npm auto-update config of sinon.js

---

ajax/libs/instafetch.js/package.json

Pull request for issue: #11190 
* Git repository (required): https://github.com/thomasvaeth/instafetch.js
* Official website (optional, not the repository): http://thomasvaeth.com/instafetch.js/
* NPM package url (optional): https://www.npmjs.com/package/instafetch.js
- Count of stars: 113
- Count of forks: 5
- Downloads in the last week: 20
- Downloads in the last month: 61

[Author] Add instafetch.js w/ npm auto-update via single package.json

---

ajax/libs/jquery-spellchecker/package.json

close #11511
Pull request for issue: #11511 
* Git repository (required): https://github.com/badsyntax/jquery-spellchecker
* Official website (optional, not the repository):  http://jquery-spellchecker.badsyntax.co/
* License and its reference: "MIT" - https://opensource.org/licenses/MIT
- Count of watchers: 30
- Count of stars: 262
- Count of forks: 108 …

Add jquery-spellchecker w/ git auto-update via single package.json

---

ajax/libs/react-block-ui/package.json

Pull request for issue: #11665
* Git repository (required): https://github.com/Availity/react-block-ui.git
* Official website (optional, not the repository): https://availity.github.io/react-block-ui/
* NPM package url (optional): https://www.npmjs.com/package/react-block-ui
* License and its reference: MIT: [Github LICENSE file](https://github.com/Availity/react-block-ui/blob/master/LICENSE) | [package.json license property](https://github.com/Availity/react-block-ui/blob/master/package.json#L55)
- …

[New][Author] Add react-block-ui w/ npm auto-update via single package.json

---

.gitignore

Fix .gitignore to exclude react-data-grid correctly

---

ajax/libs/bootstrap-switch/package.json

It seems that I can not change the original PR #11708 
I created a new one and squashed all to one commit. Thanks.

Update homepage, author & repository of bootstrap-switch

---

ajax/libs/email-autocomplete/package.json

close #11512, cc @10w042
Pull request for issue: #11512 
* Git repository (required): https://github.com/10w042/email-autocomplete
- Count of stars: 199

Add email-autocomplete w/ git auto-update via single package.json

---

ajax/libs/cytoscape/package.json

* Git repository (required): https://github.com/cytoscape/cytoscape.js
* Official website (optional, not the repository): http://js.cytoscape.org/
* NPM package url (optional): https://www.npmjs.com/package/cytoscape
- Count of watchers: 183
- Count of stars: 3390
- Count of forks: 507
- Downloads in the last day: 1697
- Downloads in the last week: 4757 …

Update cytoscape auto-update config

---

ajax/libs/simplebar/package.json

close #9917 
Pull request for issue: #9917 
* Git repository (required): https://github.com/Grsmto/simplebar
* Official website (optional, not the repository): http://grsmto.github.io/simplebar/
* NPM package url (optional): https://www.npmjs.org/package/simplebar
- Count of stars: 364
- Count of forks: 66
- Downloads in the last day: 201
- Downloads in the last week: 976
- Downloads in the last month: 3 …

[New] Add simplebar w/ git auto-update via single package.json

---

ajax/libs/whitestorm.js/package.json

The origin repository's url always redirect to https://github.com/WhitestormJS/whs.js
And add `whs.js` keyword let CDNJS homepage better to search.
* Git repository (required): https://github.com/WhitestormJS/whs.js
* Official website (optional, not the repository): https://whsjs.io/
* NPM package url (optional): https://www.npmjs.com/package/whs
- Count of watchers: 257
- Count of stars: 4261
- Count of forks: 265
- Downloads …

Update repository's url and keywords of whitestorm.js

---

ajax/libs/jodit/package.json

Pull request for issue: Update repository
* Git repository (required): none
* Official website (optional, not the repository): https://xdsoft.net/jodit/
* NPM package url (optional): https://www.npmjs.com/package/jodit
* License and its reference: CC-BY-NC-3.0
- Count of watchers:1
- Count of stars:1
- Count of forks:1
- Downloads in the last day:2,817 
- Downloads in the last week:2,854
- Downloads in the last month:5,028
* [x Project …

[Author] Update jodit auto-update config

---

.gitignore
ajax/libs/embed-js/package.json

1. Update .gitignore to exclude the versions as the followings:
```
embed-js/0.1.0-alpha.15063db7/
embed-js/0.1.0-alpha.17cc8c7a/
embed-js/0.1.0-alpha.4c5f8c5a/
embed-js/0.1.0-alpha.574cf3c6/
embed-js/0.1.0-alpha.8aea9208/
embed-js/0.1.0-alpha.962d53f6/
embed-js/0.1.0-alpha.989fbc45/
```
2. Update auto-update config to get the v5.0.0-beta.1 and v5.0.0
* Git repository (required): https://github.com/ritz078/embed-js
* Official website (optional, not the repository): http://riteshkr.com/embed.js …

Update embed-js auto-update config and .gitignore

---

ajax/libs/gridder/package.json

close #11508
Pull request for issue: #11508
* Git repository (required): https://github.com/oriongunning/gridder
* Official website (optional, not the repository): http://oriongunning.github.io/gridder/
* License and its reference: CC-BY-3.0
- Count of watchers: 30
- Count of stars: 340
- Count of forks: 100

[New] Add gridder w/ git auto-update via single package.json

---

ajax/libs/dompurify/package.json

* Git repository (required): https://github.com/cure53/DOMPurify
* Official website (optional, not the repository): https://cure53.de/purify
* NPM package url (optional): https://www.npmjs.com/package/dompurify
* License and its reference: MPL-2.0, Apache-2.0
- Count of watchers: 79
- Count of stars: 1625
- Count of forks: 121
- Downloads in the last day: 3342
- Downloads in the last week: 19317
- Downloads in …

Update auto-update config & add homepage of dompurify

---

ajax/libs/ef.js/package.json

* Git repository (required): https://github.com/TheNeuronProject/ef.js
* Official website (optional, not the repository): https://ef.js.org/#!home
* NPM package url (optional): https://www.npmjs.com/package/ef.js
- Count of stars: 73
- Count of forks: 2
- Downloads in the last day: 63
- Downloads in the last week: 1536
- Downloads in the last month: 3520

[New][Author] Add ef.js w/ npm auto-update via single package.json

---

ajax/libs/framework7/package.json

* Git repository (required): https://github.com/nolimits4web/Framework7
* Official website (optional, not the repository): http://framework7.io
- Count of watchers: 632
- Count of stars: 10467
- Count of forks: 2253

Update framework7 auto-update config

---

ajax/libs/circular-progress/package.json

close #11507, cc @neoziro
Pull request for issue: #11507
* Git repository (required): https://github.com/neoziro/circular-progress
- Count of stars: 257
- Count of forks: 30
* NPM download stats (optional): N/A
- Downloads in the last day: N/A
- Downloads in the last week: N/A
- Downloads in the last month: N/A

Add circular-progress w/ git auto-update via single package.json

---

ajax/libs/jexcel/package.json

Related issue(s): #10671
* Git repository (required): http://github.com/paulhodel/jexcel
* Official website (optional, not the repository): http://bossanova.uk/jexcel
* NPM package url (optional): https://www.npmjs.com/package/jexcel
- Count of stars: 90
- Count of forks: 21
- Downloads in the last day: 0 
- Downloads in the last week: 120
- Downloads in the last month: 180
*[ ] More than 200 [Stars / …

[New][Author] Add jexcel w/ npm auto-update via single package.json

---

ajax/libs/jquery-nearest/package.json

close #10989  @sashberd
* Git repository (required): https://github.com/gilmoreorless/jquery-nearest
* Official website (optional, not the repository): https://gilmoreorless.github.io/jquery-nearest/
* NPM package url (optional): https://www.npmjs.com/package/jquery-nearest
- Count of watchers: 8
- Count of stars: 94
- Count of forks: 20
- Downloads in the last day: 20
- Downloads …

Add jquery-nearest w/ git auto-update via single package.json

---

ajax/libs/jquery-watch/package.json

close #11756, cc @RickStrahl
Pull request for issue: #11756 
* Git repository (required): https://github.com/RickStrahl/jquery-watch
* Official website (optional, not the repository): https://weblog.west-wind.com/posts/2014/Oct/20/A-jquerywatch-Plugin-for-watching-CSS-styles-and-Attributes
* NPM package url (optional): https://www.npmjs.com/package/jquery-watch
* License and its reference:  MIT
- Count of stars:123
- Count of forks: 24
* NPM …

Add jquery-watch w/ git auto-update via single package.json

---

ajax/libs/jquery.hoverintent/package.json

- Update auto-update config
- Update v1.9.0 because there is a minified file from v1.9.0 of lib
close #11656
Pull request for issue: #11656 
Related issue(s): #11785
* Git repository (required): https://github.com/briancherne/jquery-hoverIntent
- Count of watchers: 41
- Count of stars:696
- Count of forks:188
- …

Update jquery.hoverintent auto-update config & homepage

---

ajax/libs/jquery.i18n/package.json

close #11203, cc @Wikimedia
Pull request for issue: #11203
* Git repository (required): https://github.com/wikimedia/jquery.i18n
* Official website (optional, not the repository): https://www.wikimedia.org/
* NPM package url (optional): 
- Count of watchers: 46
- Count of stars: 343
- Count of forks: 70

Add jquery.i18n w/ git auto-update via single package.json

---

ajax/libs/emojionearea/package.json

* Git repository (required): https://github.com/mervick/emojionearea
* Official website (optional, not the repository): http://mervick.github.io/emojionearea/
* NPM package url (optional): https://www.npmjs.com/package/emojionearea
- Count of stars: 310
- Count of forks: 77
- Downloads in the last day: 1,353
- Downloads in the last week: 9,242 
- Downloads …

Add emojionearea w/ git auto-update via single package.json 

---

.gitignore
ajax/libs/angular-gridster/package.json

close #10240, cc @ManifestWebDesign
Pull request for issue: #10240
* Git repository (required): https://github.com/ManifestWebDesign/angular-gridster.git
* Official website (optional, not the repository): http://manifestwebdesign.github.io/angular-gridster/
* NPM package url (optional): https://www.npmjs.com/package/angular-gridster
- Count of watchers: 88
- Count of stars: 930
- Count of forks: 388
- …

Add angular-gridster w/ git auto-update via single package.json

---

ajax/libs/goalProgress/1.0/goalProgress.css
ajax/libs/goalProgress/1.0/goalProgress.js
ajax/libs/goalProgress/1.0/goalProgress.min.css
ajax/libs/goalProgress/1.0/goalProgress.min.js
ajax/libs/goalProgress/package.json

Pull request for issue: #11506
Related issue(s): 
* Git repository (required): https://github.com/tinacious/goalProgress
* Official website (optional, not the repository): http://tinacious.github.io/goalProgress/
* License and its reference: [MIT](https://github.com/dobtco/formbuilder/blob/gh-pages/LICENSE.md)
- Count of stars: 99
- Count of forks: 32 …

Add goalProgress@1.0 w/ git auto-update

---

ajax/libs/inferno-compat/package.json
ajax/libs/inferno-component/package.json
ajax/libs/inferno-create-element/package.json
ajax/libs/inferno-devtools/package.json
ajax/libs/inferno-hyperscript/package.json
ajax/libs/inferno-router/package.json
ajax/libs/inferno-server/package.json
ajax/libs/inferno-shared/package.json
ajax/libs/inferno-test-utils/package.json
ajax/libs/inferno-vnode-flags/package.json
ajax/libs/inferno/package.json

Update file pattern to grab files with more possible file types.
According to https://github.com/cdnjs/cdnjs/pull/11621#discussion_r136314498.
And I think we can close #10840 after this pull request is merged because all inferno related lib were added.

Update auto-update config of inferno related libs

---

ajax/libs/vee-validate/package.json

close #11831
Pull request for issue: #11831
* Git repository (required): https://github.com/logaretm/vee-validate
* Official website (optional, not the repository): http://vee-validate.logaretm.com
* NPM package url (optional): https://www.npmjs.com/package/vee-validate
- Count of watchers: 73
- Count of stars: 2517
- Count of forks: 313
- Downloads in the last day: 737
- Downloads in the last week: 19098 …

Update the auto-update config of vee-validate

---

ajax/libs/jit/package.json

ref: https://github.com/philogb/jit/blob/master/LICENSE

Update license information of jit, cc #11931

---

ajax/libs/jcalculator/package.json

Updated the repository. cc #11931 
ref: https://github.com/balajmarius/jcalculator

Update repository for jcalculator

---

ajax/libs/ekko-lightbox/package.json

update license in ekko-lightbox
cc #11931

Update package.json in lib/ekko-lightbox 

---

ajax/libs/buy-button-js/package.json

Pull request for issue: #11910
* Git repository (required): https://github.com/Shopify/buy-button-js
* Official website (optional, not the repository): http://shopify.github.io/buy-button-js/
* NPM package url (optional): https://www.npmjs.com/package/@shopify/buy-button-js
- Count of watchers: 135
- Count of stars: 30
- Count of forks: 14
- Downloads in the last week: 104
- …

[New] Add buy-button-js w/ npm auto-update via single package.json

---

ajax/libs/react-popper/package.json

Pull request for issue: #11924
Related issue(s):
* Git repository (required): https://github.com/souporserious/react-popper
* NPM package url (optional): https://www.npmjs.com/package/react-popper
* License and its reference: MIT: https://github.com/souporserious/react-popper/blob/master/LICENSE
- Count of stars: 260
- Count of forks: 26
- Downloads in the last day: 2,534
- Downloads in …

[New] Add react-popper w/ npm auto-update via single package.json

---

README.md

Hi. Just a typo. This is my first pull request so I hope this is ok.
Pull request for issue: #11168

Add missing y to read trying not tring.

---

ajax/libs/repo.js/package.json

ref: https://github.com/darcyclarke/Repo.js.git

Add repo.js license info

---

ajax/libs/jqPlot/package.json

Update license and keyword at lib Jq plot

---

ajax/libs/reactstrap/package.json

close #11927
Pull request for issue: #11927
* Git repository (required): https://github.com/reactstrap/reactstrap.git
* Official website (optional, not the repository): https://reactstrap.github.io/
* NPM package url (optional): https://www.npmjs.com/package/reactstrap
* License and its reference: MIT ref: [in repo](https://github.com/reactstrap/reactstrap/blob/master/LICENSE)
* GitHub / Bitbucket popularity (required): **GitHub**
- Count of watchers: 99
- Count of stars: 2,352
- Count of forks: 247
* NPM download …

[Author] Update auto-update config of reactstrap

---

ajax/libs/sticky-js/package.json

Pull request for issue: #11900 
* Git repository (required): https://github.com/rgalus/sticky-js
* Official website (optional, not the repository): https://rgalus.github.io/sticky-js/
* NPM package url (optional): https://www.npmjs.com/package/sticky-js
* License and its reference: [MIT](https://github.com/rgalus/sticky-js/blob/master/LICENSE)
- Count of stars: 160
- Count of forks: 29 …

[New] Add sticky-js  w/ npm auto-update via single package.json

---

ajax/libs/equalize.js/package.json

Update equalize.js license and add author info

---

ajax/libs/TableExport/package.json

Pull request for issue: #12013 

Update TableExport homepage info

---

ajax/libs/embedly-jquery/package.json

Issue #11931
* Git repository (required): https://github.com/embedly/embedly-jquery
* License and its reference: "BSD-3-Clause"
- Count of stars: 309
- Count of forks: 70

Update embedly-jquery license identify format

---

ajax/libs/gif.js/package.json

close #10040, cc @jnordberg
Pull request for issue: #10040 
* Git repository (required): https://github.com/jnordberg/gif.js
* Official website (optional, not the repository): http://jnordberg.github.io/gif.js/
- Count of watchers: 78
- Count of stars: 2321
- Count of forks: 231
* [X ] I …

Add gif.js w/ git auto-update via single package.json

---

ajax/libs/roll-call/package.json

close #11884, cc @mikeal
Pull request for issue: #11884
Related issue(s): 
* Git repository (required): [https://github.com/mikeal/roll-call](https://github.com/mikeal/roll-call)
* Official website (optional, not the repository): [https://rollcall.audio/](https://rollcall.audio/)
* NPM package url (optional): [https://www.npmjs.com/package/roll-call](https://www.npmjs.com/package/roll-call)
- Count of watchers: 52
- Count of stars: 1363
- Count of …

[New] Add roll-call w/ npm auto-update via single package.json

---

ajax/libs/tracing.js/package.json

Pull request for issue: #11973
* Git repository (required): https://github.com/ebobby/tracing.js
- Count of watchers: 24
- Count of stars: 516
- Count of forks: 18

[New] Add tracing.js w/ git auto-update via single package.json

---

ajax/libs/amplitudejs/package.json

close #11438, cc @521dimensions
Pull request for issue: #11438 
* Git repository (required): https://github.com/521dimensions/amplitudejs/tree/v1.0
* Official website (optional, not the repository): https://521dimensions.com/open-source/amplitudejs
* NPM package url (optional): https://www.npmjs.com/package/amplitudejs
- Count of watchers:  57
- Count of stars: 1844
- Count of forks: 155 …

Add amplitudejs w/ git auto-update via single package.json

---

ajax/libs/botui/package.json

close #11915, cc @moinism
Pull request for issue: #11915 
* Git repository (required): https://github.com/botui/botui
* Official website (optional, not the repository): https://botui.org/
* NPM package url (optional): https://www.npmjs.com/package/botui
* License and its reference: [MIT]( http://github.com/botui/botui/blob/master/LICENSE)
- Count of watchers: 40
- Count of stars: 1398
- Count of forks: 111
- Downloads in the last day: 6
- …

Add botui w/ npm auto-update via single package.json

---

ajax/libs/vega-embed/package.json

Fixes https://github.com/vega/vega-embed/issues/52

Update vega-embed auto-update config

---

ajax/libs/antimoderate/package.json

Update antimoderate license and keywords

---

ajax/libs/numbers.js/package.json

Pull request for issue: #12020 
* Git repository (required): https://github.com/numbers/numbers.js
* NPM package url (optional): https://www.npmjs.com/package/numbers
- Count of watchers: 79
- Count of stars: 1436
- Count of forks: 143
- Downloads in the last day: 58
- Downloads in the last week: 378
- Downloads in the last month: 2040

[New] Add numbers.js w/ npm auto-update via single package.json

---

ajax/libs/jquery-form-validator/package.json

Pull request for issue: #11931 
* Git repository (required): https://github.com/victorjonsson/jQuery-Form-Validator
* Official website (optional, not the repository): http://www.formvalidator.net/
* License and its reference:  https://github.com/victorjonsson/jQuery-Form-Validator/commit/b46e2760937dc04cbf2ce74710a1e7a1bcf7ef74
- Count of watchers: 62
- Count of stars: 841
- Count of forks: 392
- …

Fix license in jquery-form-validator

---

ajax/libs/json-forms/package.json

Pull request for issue: #10166 
* Git repository (required): https://github.com/brutusin/json-forms
* Official website (optional, not the repository): http://brutusin.org/json-forms/
* License and its reference: Apache License 2.0
- Count of watchers: 32
- Count of stars: 214
- Count of forks: 62

[New] Add json-forms w/ git auto-update via single package.json

---

ajax/libs/intercom.js/package.json

Update intercom.js license format to SPDX

---

ajax/libs/shopify-buy/package.json

Pull request for issue: https://github.com/cdnjs/cdnjs/issues/11909 cc @Shopify
* Git repository (required): https://github.com/Shopify/js-buy-sdk
* Official website (optional, not the repository): https://shopify.github.io/js-buy-sdk
* NPM package url (optional): https://www.npmjs.com/package/shopify-buy
* License and its reference: MIT License
- Count of watchers: 174
- Count of stars: 257
- Count of forks: 81 …

Add shopify-buy w/ npm auto-update via single package.json

---

ajax/libs/clipboard-polyfill/package.json

Pull request for issue: #11994
* Git repository (required): https://github.com/lgarron/clipboard-polyfill
* Official website (optional, not the repository): https://garron.net/code/clipboard-polyfill/
* NPM package url (optional): https://www.npmjs.com/package/clipboard-js
* License and its reference: [MIT](https://github.com/lgarron/clipboard-polyfill/blob/master/LICENSE.md)
- Count of stars: 231
- Count of forks: 48 …

Add clipboard-polyfill w/ git auto-update via single package.json

---

ajax/libs/jquery.quicksearch/package.json

close #12064
Pull request for issue: #12064 
* Git repository (required): https://github.com/DeuxHuitHuit/quicksearch
* Official website (optional, not the repository): https://deuxhuithuit.github.io/quicksearch/r/examples/super_table.html
* NPM package url (optional): https://www.npmjs.com/package/jquery.quicksearch
* License and its reference: https://github.com/DeuxHuitHuit/quicksearch#license
- Count of stars: 101
* NPM …

Transfer jquery.quciksearch to git auto-update for more versions

---

ajax/libs/froala-design-blocks/package.json

Related issue(s): froala/design-blocks#27 froala/design-blocks#8
https://www.producthunt.com/posts/froala-design-blocks-2
* Git repository (required): https://github.com/froala/design-blocks
* Official website (optional, not the repository): https://www.froala.com/design-blocks
* NPM package url (optional): https://www.npmjs.com/package/froala-design-blocks
* License and its reference: https://github.com/froala/design-blocks/blob/master/LICENSE …

[Author] Add froala-design-blocks w/ git auto-update via single package.json

---

ajax/libs/jquery.form/package.json

Ref:https://github.com/jquery-form/form#license
cc #11931

 Update licenses format of jquery.form

---

ajax/libs/embedly-jquery/package.json

@cdnjs/library-reviewer Please help me review this PR. Thanks. Just update some info.
* Git repository (required): https://github.com/embedly/embedly-jquery
* License and its reference: BSD-3-Clause, https://github.com/embedly/embedly-jquery/blob/master/LICENSE
- Count of stars: 309
- Count of forks: 70

Update embedly-jquery info and add git auto-update

---

ajax/libs/lamejs/package.json

close #12132, cc @zhuker
Pull request for issue: #12132 
* Git repository (required): https://github.com/zhuker/lamejs
* NPM package url (optional): https://www.npmjs.com/package/lamejs
* License and its reference: LGPL-3.0
- Count of stars: 204
- Count of forks: 41
- Downloads in the last day: 40
- Downloads in the last week: 209 …

[New] Add lamejs w/ npm auto-update via single package.json

---

ajax/libs/jquery-ui-map/package.json

Update jquery-ui-map license format to SPDX

---

ajax/libs/emergence.js/package.json

close #12149, cc @xtianmiller
Pull request for issue: #12149 
* Git repository (required): https://github.com/xtianmiller/emergence.js
* Official website (optional, not the repository): https://xtianmiller.github.io/emergence.js/
* NPM package url (optional): https://www.npmjs.com/package/emergence.js
- Count of stars: 721
- Count of forks: 22
- Downloads in the last day: 27
- …

[New] Add emergence.js w/ npm auto-update via single package.json

---

ajax/libs/SoundJS/package.json

Added npmFileMap for auto update support.
* Git repository (required): https://github.com/CreateJS/SoundJS
* Official website (optional, not the repository): http://createjs.com/soundjs
* NPM package url (optional): https://www.npmjs.com/package/soundjs
* License and its reference: MIT - https://github.com/CreateJS/SoundJS/blob/master/LICENSE.txt
- Count of watchers: 185
- Count of stars: 2,461
- Count of forks: 609 …

[Author] Update SoundJS package.json w/ npm auto-update config

---

ajax/libs/tweenjs/package.json

Added npmFileMap for auto update support.
* Git repository (required):https://github.com/CreateJS/TweenJS
* Official website (optional, not the repository): http://createjs.com/tweenjs
* NPM package url (optional): https://www.npmjs.com/package/tweenjs
* License and its reference: MIT - https://github.com/CreateJS/TweenJS/blob/master/LICENSE.txt
- Count of watchers: 164
- Count of stars: 2,414
- Count of forks: 560 …

[Author] Update TweenJS package.json w/ npm auto-update config

---

ajax/libs/PreloadJS/package.json

Added npmFileMap for auto update support.
* Git repository (required): https://github.com/CreateJS/PreloadJS
* Official website (optional, not the repository): http://createjs.com/preloadjs
* NPM package url (optional): https://www.npmjs.com/package/preloadjs
* License and its reference: MIT - https://github.com/CreateJS/PreloadJS/blob/master/LICENSE.txt
- Count of watchers: 141
- Count of stars: 2, 067
- Count of forks: 514 …

[Author] Update PreloadJS package.json w/ npm auto-update config

---

ajax/libs/EaselJS/package.json

Added npmFileMap for auto update support.
Pull request for issue: #11362
* Git repository (required): https://github.com/CreateJS/Easeljs
* Official website (optional, not the repository): http://createjs.com/easeljs
* NPM package url (optional): https://www.npmjs.com/package/easeljs
* License and its reference: MIT - https://github.com/CreateJS/EaselJS/blob/master/LICENSE.txt
- Count of watchers: 409
- Count of stars: 6.336
- Count of forks: 1704 …

[Author] Update EaselJS package.json w/ npm auto-update config

---

ajax/libs/jquery.appear/package.json

close #12180, cc @morr
Pull request for issue: #12180 

Add jquery.appear git auto-update config

---

ajax/libs/zensh-ui-autocomplete/package.json

close #8202, cc @zensh
Pull request for issue: #8202
* Git repository (required): https://github.com/zensh/ui-autocomplete/
- Count of stars: 68
- Count of forks: 41

[New] Add zensh-ui-autocomplete w/ git auto-update via single package.json

---

tools/fixFormat.js

close #5476 , @PeterDaveHello
Pull request for issue: #5476 
Related issue(s): # #11832 

Add support for run fixFormat tool on specific library by name pattern

---

ajax/libs/slim-select/package.json

Updated file name output. Will now have slimselect.js, slimselect.css and slimselect.min.js, slimselect.min.css

[Author] Update slim-select auto-update config

---

.gitignore
ajax/libs/fpo/package.json

Pull request for issue: #10811
* Git repository (required): https://github.com/getify/fpo
* NPM package url (optional): https://www.npmjs.com/package/fpo
* License and its reference: MIT https://github.com/getify/fpo/blob/master/LICENSE.txt
- Count of stars: 248
- Downloads in the last day: 1
- Downloads in the last week: 2 …

[Author] Add fpo w/ npm auto-update via single package.json

---

ajax/libs/sliiide/1.1.4/sliiide.js
ajax/libs/sliiide/1.1.4/sliiide.min.js
ajax/libs/sliiide/package.json

close #10112, cc @ahmedrad
Pull request for issue: #10112 
* Git repository (required): https://github.com/ahmedrad/sliiide
* Official website (optional, not the repository): http://ahmedrad.github.io/sliiide/
- Count of stars:122
- Count of forks:27

Add sliiide@1.1.4 w/ git auto-update

---

ajax/libs/country-select-js/package.json

Pull request for issue: #11462
* Git repository (required): https://github.com/mrmarkfrench/country-select-js
* NPM package url (optional): https://www.npmjs.com/package/country-select-js
* License and its reference: [MIT](https://github.com/mrmarkfrench/country-select-js/blob/master/package.json#L16)
- Count of stars: 143
- Count of forks: 65
- Downloads in the last day: 67
- Downloads …

Add country-select-js w/ git auto-update via single package.json

---

ajax/libs/unveil2/package.json

closes #10782
Related issue(s): #10782
* Git repository (required): https://github.com/nabble/unveil2
* Official website (optional, not the repository): https://nabble.github.io/unveil2/
* NPM package url (optional): https://www.npmjs.com/package/unveil2
- Count of stars: 33
- Count of forks: 719
- Downloads in the last day: 47
- Downloads in the last week: 265 …

[New] Add unveil2 w/ git auto-update via single package.json

---

ajax/libs/videojs-flash/package.json

Pull request for issue: #11517
* Git repository (required): https://github.com/videojs/videojs-flash
* NPM package url (optional): https://www.npmjs.com/package/videojs-flash
- Count of watchers: 15
- Count of stars: 50
- Count of forks: 21
- Downloads in the last day: 130
- Downloads in the last week: 603
- Downloads in the last month: 3480

Add videojs-flash w/ npm auto-update via single package.json

---

ajax/libs/datatable/package.json

Pull request for issue: #10718 
* Git repository (required):datatable
* NPM package url (optional): none
- Count of watchers: 8
- Count of stars: 76
- Count of forks: 24

Add datatable w/ git auto-update via single package.json

---

ajax/libs/emoji-picker/package.json

Update emoji-picker URL of homepage & repository

---

ajax/libs/bootswatch/package.json

fix bootswatch npm auto-update
* https://github.com/thomaspark/bootswatch
* https://www.npmjs.com/package/bootswatch
🔗 https://github.com/thomaspark/bootswatch/issues/766
* Git repository (required): https://github.com/thomaspark/bootswatch
* NPM package url (optional): https://www.npmjs.com/package/bootswatch

Update bootswatch auto-update config

---

ajax/libs/tempusdominus-bootstrap-4/package.json

Pull request for issue: #11453
Related issue(s): # #12337
* Git repository (required): https://github.com/tempusdominus/bootstrap-4
* NPM package url (optional): https://www.npmjs.com/package/tempusdominus-bootstrap-4
- Count of stars: 89
- Count of forks: 28
- Downloads in the last day: 63
- Downloads in the last week: 312 …

[New][Author] Add tempusdominus-bootstrap-4 w/ git auto-update via single package.json

---

ajax/libs/event-drops/package.json

Pull request for issue: #11999
* Git repository (required): https://github.com/marmelab/EventDrops
* Official website (optional, not the repository): http://marmelab.com/EventDrops/
* NPM package url (optional): https://www.npmjs.com/package/event-drops
* License and its reference: MIT License
- Count of watchers: 40
- Count of stars: 792
- Count of forks: 157
- Downloads in the last day: 3
- Downloads in the last week: 74
- Downloads in …

[New] Add event-drops w/ npm auto-update via single package.json

---

ajax/libs/limonte-sweetalert2/package.json

* Git repository (required): https://github.com/sweetalert2/sweetalert2
* Official website (optional, not the repository): https://sweetalert2.github.io/
* NPM package url (optional): https://www.npmjs.com/package/sweetalert2
* License and its reference: MIT https://github.com/sweetalert2/sweetalert2/blob/master/LICENSE
- Count of watchers: 137
- Count of stars: 4089
- Count of forks: 659

Update SweetAlert2 repository, homepage & description

---

ajax/libs/scrollama/package.json

Pull request for issue: #12250
* Git repository (required): https://github.com/russellgoldenberg/scrollama
* Official website (optional, not the repository): https://russellgoldenberg.github.io/scrollama/basic/
* NPM package url (optional): https://www.npmjs.com/package/scrollama
- Count of watchers: 56
- Count of stars: 2,759
- Count of forks: 93
- Downloads in the last day: 413
- Downloads in the last week: 1,657
- Downloads …

[New] Add scrollama w/ npm auto-update via single package.json

---

ajax/libs/css-doodle/package.json

Pull request for issue: #12376
* Git repository (required): https://github.com/yuanchuan/css-doodle
* Official website (optional, not the repository): http://yuanchuan.name/css-doodle/
* NPM package url (optional): https://www.npmjs.com/package/css-doodle
* License and its reference: [MIT](https://github.com/yuanchuan/css-doodle/blob/master/LICENSE)
- Count of stars: 309
- Downloads in …

[New] Add css-doodle w/ npm auto-update via single package.json

---

CONTRIBUTING.md

Pull request for issue: #12443 
This fixes a very tiny typo in the CONTRIBUTING.md file, where 'accessible' was misspelt as 'accessable' on line 48.

[Docs] Fix typo in CONTRIBUTING.md

---

ajax/libs/bubbly-bg/package.json

close #11974
Pull request for issue: #11974 
* Git repository (required): https://github.com/tipsy/bubbly-bg
* NPM package url (optional): https://www.npmjs.com/package/bubbly-bg
* License and its reference: [Apache 2.0](https://github.com/tipsy/bubbly-bg/blob/master/LICENSE)
- Count of watchers: 24
- Count of stars: 1112
- Count of forks: 53
- …

[New] Add bubbly-bg w/ npm auto-update via single package.json

---

ajax/libs/stickybits/package.json

* Git repository (required): [stickybits](https://github.com/dollarshaveclub/stickybits)
* Official website (optional, not the repository): https://dollarshaveclub.github.io/stickybits/
* NPM package url (optional): https://www.npmjs.com/package/stickybits
* GitHub / Bitbucket popularity (required): https://github.com/dollarshaveclub/stickybits
- Count of watchers: 31 
- Count of stars: 1087
- Count of forks: 63
* NPM download stats (optional): 
- Downloads in the last day: 108  …

[Author] Add stickybits w/ npm auto-update via single package.json

---

ajax/libs/chimee/package.json

Pull request for issue: #12148 
* Git repository (required): https://github.com/Chimeejs/chimee
* Official website (optional, not the repository): https://chimee.org/
* NPM package url (optional): https://www.npmjs.com/package/chimee
- Count of stars: 713
- Count of forks: 38
- Downloads in the last day: 33
- Downloads in the last week: 152
- Downloads in the last month: 419

[New] Add chimee w/ npm auto-update via single package.json 

---

ajax/libs/focusable/package.json

close #12462, cc @zzarcon
Pull request for issue: #12462
* Git repository (required): https://github.com/zzarcon/focusable
* Official website (optional, not the repository): http://zzarcon.github.io/focusable/
* NPM package url (optional): https://www.npmjs.com/package/focusable-element
- Count of watchers: 28
- Count of stars: 1,067
- Count of forks: 53 …

[New] Add focusable w/ git auto-update via single package.json

---

ajax/libs/bootstrap-select/package.json

Pull request for issue: #12520
* Git repository (required): https://github.com/snapappointments/bootstrap-select
* Official website (optional, not the repository): https://developer.snapappointments.com/bootstrap-select/
* NPM package url (optional): https://www.npmjs.com/package/bootstrap-select

[author] Update bootstrap-select information/use npm auto-update

---

PULL_REQUEST_TEMPLATE.md

Fix PULL_REQUEST_TEMPLATE.md typos

---

ajax/libs/jsnes/package.json

close #12463
Pull request for issue: #12463 
* Git repository (required): https://github.com/bfirsh/jsnes
* Official website (optional, not the repository): https://jsnes.fir.sh/
* NPM package url (optional): https://www.npmjs.com/package/jsnes
* License and its reference: GPL-3.0
- Count of watchers: 122
- Count of stars: 3072
- Count of forks: 452
- Downloads in the last day: 3
- Downloads in the last week: 70 …

[New] Add jsnes w/ npm auto-update via single package.json

---

README.md

fix link for cdnjs-importer to contributors

Fix cdnjs-importer link in README

---

ajax/libs/marked/package.json

Related issue(s): #12579
* Git repository (required): https://github.com/markedjs/marked
* NPM package url (optional): https://www.npmjs.com/package/marked

Update marked repo url

---

ajax/libs/tippy.js/package.json

Pull request for issue: #11047
* Git repository (required): https://github.com/atomiks/tippyjs
* Official website (optional, not the repository): https://atomiks.github.io/tippyjs/
* NPM package url (optional): https://www.npmjs.com/package/tippy.js
- Count of watchers: 55
- Count of stars: 3985
- Count of forks: 246
- Downloads in the last day: 1,666
- Downloads in the last week: 8,716
- Downloads in the last month: 33,595

Setup auto-update config & update description for tippy.js

---

ajax/libs/js-quantities/package.json

* Git repository (required): https://github.com/gentooboontoo/js-quantities
* Official website (optional, not the repository): https://gentooboontoo.github.io/js-quantities/
* NPM package url (optional): https://www.npmjs.com/package/js-quantities
- Count of stars: 221
- Count of forks: 57
- Downloads in the last day: 155
- Downloads in the last week: 6,464 …

[New] Add js-quantities w/ npm auto-update via single package.json

---

ajax/libs/Vague.js/package.json

According to [author response](https://github.com/GianlucaGuarini/Vague.js/issues/28)
cc #5500

Add Vague.js license info (MIT)

---

ajax/libs/skycons/package.json

Accoriding [to author answer]( https://github.com/darkskyapp/skycons/issues/23#issuecomment-348960341)
cc #5500

Update skycons lib license property in package.json

---

ajax/libs/RecordRTC/package.json

close #12131, cc @muaz-khan
Pull request for issue: #12131
* Git repository (required): https://github.com/muaz-khan/RecordRTC
* Official website (optional, not the repository): http://RecordRTC.org
* NPM package url (optional): https://www.npmjs.com/package/recordrtc
- Count of watchers: 99
- Count of stars: 1272
- Count of forks: 534
- Downloads in the last day: 331
- Downloads in the last week: 2212
- …

[New] Add RecordRTC w/ npm auto-update via single-package.json

---

ajax/libs/sentinel-js/package.json

close #12516, cc @muicss
Pull request for issue: #12516
* Git repository (required): https://github.com/muicss/sentineljs.git
* NPM package url (optional): https://www.npmjs.com/package/sentinel-js
- Count of stars: 933
- Count of forks: 41
- Downloads in the last day: 1
- Downloads in the last week: 11 …

[New] Add sentinel-js w/ npm auto-update via single package.json

---

ajax/libs/babel-polyfill/package.json

Pull request for issue: #12563 

Update babel polyfill auto-update & metadata

---

ajax/libs/json2/package.json

cc #5500
Accrofing to:
https://github.com/douglascrockford/JSON-js/issues/18
Pull request for issue: #5500 
* Git repository (required): https://github.com/douglascrockford/JSON-js
* Official website (optional, not the repository): http://www.JSON.org/
* License and its reference: Public Domain
- Count of watchers: 501
- Count of stars: 7314
- Count of forks: 4167
- Downloads in …

Update json2 lib license property in package.json

---

ajax/libs/openajax-hub/package.json

cc #5500
According to:
https://github.com/cdnjs/cdnjs/blob/master/ajax/libs/openajax-hub/2.0.7/OpenAjaxUnmanagedHub.min.js#L1

Update openajax lib license property in package.json

---

ajax/libs/gsap/package.json

cc #5500
According to:
https://github.com/greensock/GreenSock-JS/blob/c0c4603364056391bbfd0dc930d494b48267f77b/package.json#L59
Pull request for issue: #5500
* Git repository (required): https://github.com/greensock/GreenSock-JS

Add gsap library license property in package.json

---

ajax/libs/jquery-tools/package.json

cc #5500
According to:
https://github.com/jquerytools/jquerytools/issues/753
Pull request for issue: #5500 
* Git repository (required): https://github.com/jquerytools/jquerytools
* Official website (optional, not the repository): http://jquerytools.org
- Downloads …

Add jquery-tools license property in package.json

---

ajax/libs/flipCounter/package.json

cc #5500
According to:
https://github.com/cdnjs/cdnjs/blob/6d1e3b8edf9b8f2da970e4c3d4818dd5aa13ce41/ajax/libs/flipCounter/1.2/jquery.flipCounter.js#L9
It is BSD-3-Clause because of 3 clauses in related link above
Based on: https://en.wikipedia.org/wiki/BSD_licenses#3-clause_license_(%22BSD_License_2.0%22,_%22Revised_BSD_License%22,_%22New_BSD_License%22,_or_%22Modified_BSD_License%22)
Pull request for issue: #5500 

Update flipcounter library license property in package.json

---

ajax/libs/multi-level-push-menu/package.json

close #12519, cc @adgsm
Pull request for issue: #12519
* Git repository (required):  https://github.com/adgsm/multi-level-push-menu
* Official website (optional, not the repository): http://multi-level-push-menu.make.rs/
- Count of watchers: 64
- Count of stars: 783
- Count of forks: 212

[New] Add multi-level-push-menu w/ git auto-update via single package.json

---

ajax/libs/reframe.js/0.0.1/responsive-iframe.css
ajax/libs/reframe.js/0.0.1/responsive-iframe.js
ajax/libs/reframe.js/2.1.18/jquery.noframe.js
ajax/libs/reframe.js/2.1.18/jquery.noframe.min.js
ajax/libs/reframe.js/2.1.18/jquery.reframe.js
ajax/libs/reframe.js/2.1.18/jquery.reframe.min.js
ajax/libs/reframe.js/2.1.18/noframe.js
ajax/libs/reframe.js/2.1.18/noframe.min.js
ajax/libs/reframe.js/2.1.18/reframe.js
ajax/libs/reframe.js/2.1.18/reframe.min.js
ajax/libs/reframe.js/package.json

close #10072, cc @dollarshaveclub
Pull request for issue: #10072
* Git repository (required): https://github.com/dollarshaveclub/reframe.js
* Official website (optional, not the repository): https://dollarshaveclub.github.io/reframe.js/
* NPM package url (optional): https://www.npmjs.com/package/reframe.js
- Count of watchers: 42
- Count of stars: 1375
- Count of forks: 50
- Downloads in the last day: 124 …

[New] Add reframe.js@2.1.18 w/ npm auto-update

---

ajax/libs/Primer/package.json

* Git repository (required): https://github.com/primer/primer
* Official website (optional, not the repository): https://primer.github.io/
* NPM package url (optional): https://www.npmjs.com/package/primer
- Count of watchers: 200
- Count of stars: 6,966 
- Count of forks: 518
- Downloads in the last day: 58
- Downloads in the last week: 428
- Downloads in the last month: 3554

Update Primer auto-update & metadata

---

ajax/libs/sweetalert/package.json

Pull request for issue: #12361
* Git repository (required): https://github.com/t4t5/sweetalert
* Official website (optional, not the repository): https://sweetalert.js.org/guides/#cdn
* NPM package url (optional): https://www.npmjs.com/package/sweetalert

Update Sweetalert auto-update config, homepage & keywords

---

ajax/libs/ng-browser-info/package.json

close #11890, cc @transferwise
Pull request for issue: 11890
Related issue(s):
* Git repository (required): https://github.com/transferwise/ng-browser-info
- Count of watchers: 123
- Count of stars: 33
- Count of forks: 3
* [ x] This lib was not found …

[New] Add ng-browser-info w/ git auto-update via single package.json

---

ajax/libs/modern-normalize/package.json

Pull request for issue: #12543
Related issue(s): #12543
* Git repository (https://github.com/sindresorhus/modern-normalize)
* NPM package url (https://www.npmjs.com/package/modern-normalize)
- Count of watchers: 31
- Count of stars: 1229
- Count of forks: 24

[New] Add modern-normalize w/ git auto-update via single package.json

---

ajax/libs/overlayscrollbars/package.json

close #12562, cc @KingSora
Pull request for issue: #12562 
* Git repository (required): https://github.com/KingSora/OverlayScrollbars
* Official website (optional, not the repository): https://kingsora.github.io/OverlayScrollbars
* NPM package url (optional): https://www.npmjs.com/package/overlayscrollbars
- Count of stars: 118
- Count of forks: 10
- …

Add overlayscrollbars w/ npm auto-update via single package.json

---

ajax/libs/ng-table/package.json

Add homepage info ng-table

---

ajax/libs/pnp-common/package.json
ajax/libs/pnp-config-store/package.json
ajax/libs/pnp-graph/package.json
ajax/libs/pnp-logging/package.json
ajax/libs/pnp-odata/package.json
ajax/libs/pnp-pnpjs/package.json
ajax/libs/pnp-sp-addinhelpers/package.json
ajax/libs/pnp-sp-clientsvc/package.json
ajax/libs/pnp-sp-taxonomy/package.json
ajax/libs/pnp-sp/package.json

* Git repository (required): https://github.com/pnp/pnp
* Official website (optional, not the repository): https://pnp.github.io/pnp/

[author] [new] adding new pnp scoped client side libraries

---

ajax/libs/mnist/package.json

close #10619, cc @cazala
Pull request for issue: #10619 
* Git repository (required): https://github.com/cdnjs/cdnjs/issues/10619
* Official website (optional, not the repository): https://github.com/cazala/mnist
* NPM package url (optional): https://www.npmjs.com/package/mnist
- Count of watchers: 5
- Count of stars: 141
- Downloads in the last day: 19 …

[New]Add mnist@1.1.0 via w/ npm auto-update

---

ajax/libs/webtorrent-component/package.json

Pull request for issue: #11883 
* Git repository (required): https://github.com/mikeal/webtorrent-component
* NPM package url (optional): https://www.npmjs.com/package/webtorrent-component
* License and its reference: apache 2.0
- Count of stars: 461
- Count of forks: 21
- Downloads in the last week: 0 …

[New] Add webtorrent-component w/ npm auto-update via single package.json

---

ajax/libs/coverflow/package.json

Close: #12292 
Pull request for issue: #12292
* Git repository (required): https://github.com/coverflowjs/coverflow
* Official website (optional, not the repository): http://coverflowjs.github.io/coverflow/
- Count of watchers: 23
- Count of stars: 316
- Count of forks: 100

[New] Add coverflow w/ git auto-update via single package.json

---

ajax/libs/js-beautify/package.json

Change glob to allow "beautifier" as a file name
This library was already added to CDNJS.  I'm the author of the library and I would like to update the pattern to include another file.

[Author] Update js-beautifier auto-update file pattern

---

ajax/libs/phaser/package.json

The build folder was changed to dist
close #12874
Pull request for issue: #12874

[New] Update phaser auto update config and homepage

---

CONTRIBUTING.md

Just fixed a broken link in the docs

Update link of "package.json" document in CONTRIBUTING.md

---

ajax/libs/framework7/package.json

Update homepage property
Update repository property
Update auto update config
cc #12877
Pull request for issue: #12877 

[New] Update framework7 auto-update and meta data

---

ajax/libs/valine/package.json

Pull request for issue: #12331 #12649
Related issue(s): #12251 
* Git repository (required): https://github.com/xCss/Valine
* Official website (optional, not the repository): https://valine.js.org
* NPM package url (optional): https://www.npmjs.com/package/valine
* License and its reference: GPL-2.0
- Count of stars: 488
- Count of forks: 61
- Downloads in the last day: 186
- Downloads in the last week: 269 …

[author]Add valine w/ npm auto-update via single package.json

---

ajax/libs/tui-calendar/package.json

Pull request for issue: #12852
* Git repository (required):  https://github.com/nhnent/tui.calendar
* Official website (optional, not the repository): https://ui.toast.com/tui-calendar/
* NPM package url (optional): https://www.npmjs.com/package/tui-calendar
- Count of watchers: 135
- Count of stars: 5964
- Count of forks: 303
- Downloads in the last day: 28
- Downloads in the last week: 333
- Downloads in the last month: 838

[New] Add tui-calendar w/ git auto-update via single package.json

---

.gitignore
ajax/libs/octicons/package.json

Update homepage property to https
Update auto update config from git to npm
close #12851
Pull request for issue: #12851

Update octicons auto-update & metadata

---

ajax/libs/angular-elevatezoom-plus/package.json

close #10384, cc @igorlino
Pull request for issue: #10384 
* Git repository (required): https://github.com/igorlino/angular-elevatezoom-plus
* Official website (optional, not the repository): https://igorlino.github.io/angular-elevatezoom-plus/
* NPM package url (optional): https://www.npmjs.com/package/angular-ez-plus
- Count of stars: 20 …

Add angular-elevatezoom-plus w/ git auto-update via single package.json

---

ajax/libs/apexcharts/package.json

close #12900, cc @apexcharts
Pull request for issue: #12900 
* Git repository (required): https://github.com/apexcharts/apexcharts.js
* NPM package url (optional): https://www.npmjs.com/package/apexcharts
* Count of watchers: 32
* Count of stars: 2181
* Count of forks: 51 …

Add apexcharts w/ npm auto-update via single package.json

---

ajax/libs/iris-ws/package.json

Pull request for issue: #12884 
* Git repository (required): https://github.com/kataras/iris
* Official website (optional, not the repository): https://iris-go.com/
* License and its reference: https://github.com/kataras/iris/blob/master/websocket/LICENSE (BSD 3-Clause "New" or "Revised" License)
- Count of watchers: 547
- Count of stars: 11109
- Count of forks: 1141

[New] Add iris-ws w/ git auto-update via single package.json 

---

ajax/libs/datalist-polyfill/package.json

Pull request for issue: #12813 
* Git repository (required): https://github.com/mfranzke/datalist-polyfill/
* NPM package url (optional): https://www.npmjs.com/package/datalist-polyfill
- Count of watchers: 8
- Count of stars: 65
- Count of forks: 24
- weekly Downloads: 1795
- weekly Downloads at its highest so far: 3618
- total Downloads: 73k
- jsDelivr hits/day: 70-80k
* NPM downloads:
The downloads currently vary a …

[author][new] Add datalist-polyfill w/ npm auto-update via single package.json

---

ajax/libs/highcharts/package.json

Update autoupdate configuration of highcharts lib
Update homepage and author properties link to https
Pull request for issue: #12824

Update highcharts package.json properties

---

ajax/libs/leaflet.pm/package.json

close #13079
Pull request for issue: #13079

Update leaflet.pm lib auto-update config to npm

---

ajax/libs/hls.js/package.json

- Point to `video-dev` rather than `dailymotion` org
- Align `description` and `license` field with `video-dev/hls.js#package.json`
Pull request for issue: https://github.com/cdnjs/cdnjs/issues/12927
* Git repository (required): https://github.com/video-dev/hls.js
* Official website (optional, not the repository): https://video-dev.github.io/hls.js/stable/demo/
* NPM package url (optional): https://www.npmjs.com/package/hls.js
* License and its reference: `Apache-2.0`
* Count of watchers: 323 …

[Author] Update hls.js#package.json

---

ajax/libs/scribbletune/package.json

Pull request for issue: #12968
Related issue(s): # #12968
* Git repository (required): https://github.com/scribbletune/scribbletune
* Official website (optional, not the repository): https://scribbletune.com/
* NPM package url (optional): https://www.npmjs.com/package/scribbletune
* Count of watchers: 110
* Count of stars: 2792
* Count of forks: 186
* Downloads in the last day: 
* Downloads in the last week: 250+
* Downloads in …

[Author] [New] Add scribbletune w/ npm auto-update via single package.json

---

ajax/libs/rxdb/package.json

close #12964, cc @pubkey
* Git repository (required): https://github.com/pubkey/rxdb
* NPM package url (optional): https://www.npmjs.com/package/rxdb
* License and its reference: [Apache-2.0|https://github.com/pubkey/rxdb/blob/master/LICENSE.txt]
* Count of watchers: 189
* Count of stars: 8231
* Count of forks: 3732
* Downloads in the last week: 1318

[new] Add rxdb w/ npm auto-update via single package.json

---

ajax/libs/webkul-micron/package.json

Pull request for issue: #12750 cc: @nitishkmrk
* Git repository (required): https://github.com/webkul/micron.git
* Official website (optional, not the repository): https://webkul.github.io/micron/
* NPM package url (optional): https://www.npmjs.com/package/webkul-micron
* Count of watchers: 44
* Count of stars: 1896
* Count of forks: 81
* Downloads in the last day: NA
* Downloads in the last week: 313 …

[New] Add webkul-micron w/ npm auto-update via single package.json

---

ajax/libs/vivid/package.json

close #13015, cc @webkul
Pull request for issue: #13015 
* Git repository (required): https://github.com/webkul/vivid
* Official website (optional, not the repository): https://webkul.github.io/vivid/
* NPM package url (optional): https://www.npmjs.com/package/vivid-icons
* License and its reference: [MIT|https://github.com/webkul/vivid/blob/master/LICENSE
* Count of watchers: 24
* Count of stars: 1544
* Count of forks: 56
* Downloads in …

[new] Add vivid w/ npm auto-update via single package.json

---

ajax/libs/protovis/package.json

Reference: https://mbostock.github.io/protovis/
CC: #11931

Update protovis license info in package.json

---

ajax/libs/jquery.mb.YTPlayer/package.json

Reference: https://github.com/pupunzi/jquery.mb.YTPlayer/tree/master/licences
CC: #11931

Update jquery.mb.YTPlayer license info in package.json

---

ajax/libs/jquery.collapsible/package.json

Reference: https://github.com/juven14/Collapsible/blob/master/LICENSE 
CC: #11931

Update jquery.collapsible license info in package.json

---

ajax/libs/fomantic-ui/package.json

Pull request for issue: N/A
Related issue(s): N/A
* Git repository (required): https://github.com/fomantic/Fomantic-UI
* Official website (optional, not the repository): https://fomantic-ui.com/
* NPM package url (optional): https://www.npmjs.com/package/fomantic-ui
* License and its reference: [MIT](https://github.com/fomantic/Fomantic-UI/blob/master/LICENSE.md)
* Count of watchers: 11
* Count of stars: 60
* Count of forks: 6
* Downloads in the last day: 108 …

[author] [new] add fomantic-ui w/ git auto-update via single package.json

---

ajax/libs/signalr/package.json

Related issue(s): #13198 
* Git repository (required):https://github.com/aspnet/AspNetCore/
* Official website (optional, not the repository):http://dot.net
* NPM package url (optional):https://npmjs.com/package/@aspnet/signalr
* License and its reference:Apache-2
* Count of watchers:1,278
* Count of stars:10,744
* Count of forks:2,569
* Downloads in the last day: 10,000 (est as npm provides weekly only) …

[New] Add signalr with npm auto-update via single package.json

---

ajax/libs/json2csv/package.json

Pull request for issue: #13197 
* Git repository (required): https://github.com/zemirco/json2csv
* Official website (optional, not the repository): http://www.mircozeiss.com/json2csv/
* NPM package url (optional): https://www.npmjs.com/package/json2csv
* Count of watchers: 31
* Count of stars: 1526
* Count of forks: 260

[New] Add json2csv w/ npm auto-update via single package.json

---

ajax/libs/es6-tween/package.json

Pull request for issue: #13359 
Related issue(s): #10998
* Git repository (required): https://github.com/tweenjs/es6-tween.git
* Official website (optional, not the repository): https://es6-tween.js.org/
* NPM package url (optional): https://www.npmjs.com/package/es6-tween
* License and its reference: [MIT License](https://github.com/tweenjs/es6-tween/blob/master/LICENSE)
* GitHub / Bitbucket popularity (required): https://github.com/tweenjs/es6-tween
* Count of watchers: 8
* Count of stars: 123
* Count of forks: 26
* NPM download …

Update es6-tween auto-update config in package.json

---

ajax/libs/chillout/package.json

Pull request for issue: #13314
* Git repository (required): https://github.com/polygonplanet/chillout
* NPM package url (optional): https://www.npmjs.com/package/chillout
* Count of watchers: 14
* Count of stars: 523
* Count of forks: 17

[new] Add chillout w/ npm auto-update via single package.json

---

.gitignore
ajax/libs/single-spa/package.json

Pull request for issue: # n/a ?
Related issue(s): # # n/a ?
* Git repository (required): https://github.com/CanopyTax/single-spa
* Official website (optional, not the repository): https://single-spa.js.org
* NPM package url (optional): https://www.npmjs.com/package/single-spa
* License and its reference: MIT https://github.com/CanopyTax/single-spa/blob/master/LICENSE
* Count of watchers: 100
* Count of stars: 2065
* Count of forks: 183 …

[author] [new] add single-spa w/ npm auto-update via single package.json

---

ajax/libs/cheval/package.json

* Git repository (required): https://github.com/ryanpcmcquen/cheval
* Official website (optional, not the repository): https://ryanpcmcquen.org/cheval/
* License and its reference: MPL-2.0
- Count of stars: 120
- Count of forks: 10
@PeterDaveHello, thank you!

[Author] Add Cheval with git auto-update via single package.json

---

ajax/libs/ckeditor5/package.json

close #13414 
Pull request for issue: #13414 
* Git repository (required): https://github.com/ckeditor/ckeditor5
* Official website (optional, not the repository): https://ckeditor.com/ckeditor-5
* NPM package url (optional): https://www.npmjs.com/package/ckeditor5
* License and its reference: GPL-2.0-or-later
* Count of watchers: 114
* Count of stars: 2.7k
* Count of forks: 556
* Downloads in the last week: 25,227
* Downloads in …

[new] Add ckeditor5 w/ npm auto-update via single package.json

---

ajax/libs/bootstrap-validator/package.json

iylim: update boostrap-validator liscense

---

ajax/libs/microsoft-signalr/package.json

Related issue(s): #13198 #13319 #13438 #13499
* Git repository (required):https://github.com/aspnet/AspNetCore/
* Official website (optional, not the repository):http://dot.net
* NPM package url (optional):https://npmjs.com/package/@microsoft/signalr
* License and its reference:Apache-2
* Count of watchers:1,278
* Count of stars:10,744
* Count of forks:2,569
* Downloads in the last day: 10,000 (est as npm provides weekly only)
* …

microsoft-signalr

---

ajax/libs/vue-multiselect/package.json

Pull request for issue: #13475
* Git repository (required): https://github.com/shentao/vue-multiselect
* Official website (optional, not the repository): https://shentao.github.io/vue-multiselect/
* NPM package url (optional): https://www.npmjs.com/package/vue-multiselect
* License and its reference: MIT (https://github.com/shentao/vue-multiselect/blob/master/LICENSE)
* Count of watchers: 98
* Count of stars: 4710
* Count of forks: 664
* …

[new] vue-multiselect

---

ajax/libs/jquery.selectboxit/package.json

Related issue(s):
* Git repository (required): https://github.com/gfranko/jQuery.selectBoxIt.js
* Official website (optional, not the repository): http://www.selectboxit.com
* NPM package url (optional): https://www.npmjs.com/package/selectboxit
* License and its reference: MIT / http://www.gregfranko.com/jQuery.selectBoxIt.js//blob/master/LICENSE-MIT
* Count of watchers: 56
* Count of stars: 877
* Count of forks: 317
* Downloads …

Add author field #11931

---

ajax/libs/vue-clipboard2/package.json

Pull request for issue: #13434
* Git repository (required): https://github.com/Inndy/vue-clipboard2
* NPM package url (optional): https://www.npmjs.com/package/vue-clipboard2
* License and its reference: MIT https://github.com/Inndy/vue-clipboard2/blob/master/LICENSE
* Count of watchers: 10
* Count of stars: 980
* Count of forks: 134 …

[new] Add vue-clipboard2 with npm auto-update via single package.json

---

ajax/libs/1140/package.json

Add repository info for 1140

---

ajax/libs/loading-attribute-polyfill/package.json

[author][new] lib adding request issue: loading-attribute-polyfill with npm auto-update via single package.json
Pull request for issue: #13520
* Git repository (required): https://github.com/mfranzke/loading-attribute-polyfill
* Official website (optional, not the repository): https://mfranzke.github.io/loading-attribute-polyfill/
* NPM package url (optional): https://www.npmjs.com/package/loading-attribute-polyfill
* Count of watchers: 3 …

[author][new] lib adding request issue: loading-attribute-polyfill with npm auto-update via single package.json

---

ajax/libs/hashids/package.json

Pull request for issue: #13095 
* Git repository (required): https://github.com/ivanakimov/hashids.js
* Official website (optional, not the repository): https://hashids.org/javascript/
* NPM package url (optional): https://www.npmjs.com/package/hashids
* License and its reference: [MIT](https://github.com/ivanakimov/hashids.js/blob/master/LICENSE)
* Count of watchers: 46
* Count of stars: 2.6K
* Count of forks: 148
* Downloads in the last week: 103,271

[new] Add hashids.js

---

ajax/libs/vue-the-mask/package.json

close #13238 
Pull request for issue: #13238 
* Git repository (required): https://github.com/vuejs-tips/vue-the-mask
* Official website (optional, not the repository): https://vuejs-tips.github.io/vue-the-mask/
* NPM package url (optional): https://www.npmjs.com/package/vue-the-mask
* Count of watchers: 19
* Count of stars: 940
* Count of forks: 128
* Downloads in the last week: 34,609
* Downloads …

[new] Add vue-the-mask w/ npm auto-update via single package.json

---

ajax/libs/jsxgraph/package.json

In package.json the version is 1.3.5 which has been set by PeterBot because of an ill-named tag "v1.3.5" in JSXGraph. The actual version number is 0.99.7. The tag has meanwhile been removed from JSXGraph.
* Git repository (required): https://github.com/jsxgraph/jsxgraph
* Official website (optional, not the repository): https://jsxgraph.org
* License and its reference: MIT https://github.com/jsxgraph/jsxgraph/blob/master/LICENSE.MIT
* Count of watchers: 54
* …

[JSXGraph] Update package.json

---

ajax/libs/hi-sven/package.json

This test library will be used to ensure autoupdaters are running and updating.
* Git repository (required): https://github.com/xtuc/hi-sven
* NPM package url (optional): https://www.npmjs.com/package/hi-sven
* …

[new] add hi-sven

---

auto-update.js

auto-update: configure via env

---

auto-update.js

autoupdater: handle uncaught exception

---

ajax/libs/ityped/package.json

close #12872, cc @luisvinicius167
Pull request for issue: #12872 
* Git repository (required): https://github.com/luisvinicius167/ityped
* Official website (optional, not the repository):  https://ityped.surge.sh/
* NPM package url (optional): https://www.npmjs.com/package/ityped
* Count of watchers: 52
* Count of stars: 1890
* Count of forks: 118
* Downloads in the last day: 70 …

Add ityped w/ git auto-update via single package.json

---

ajax/libs/hi-sven-git/package.json

Add hi-sven-git

---

ajax/libs/jquery-cropper/package.json

* Git repository (required): https://github.com/fengyuanchen/jquery-cropper
* Official website (optional, not the repository): https://fengyuanchen.github.io/jquery-cropper/
* NPM package url (optional): https://www.npmjs.com/package/jquery-cropper
* Count of watchers: 23
* Count of stars: 356
* Count of forks: 140
* …

[new] Add jquery-cropper w/ auto-update

---

ajax/libs/3Dmol/package.json

The previous git based was not actually pulling the right files
* Git repository (required): https://github.com/3dmol/3Dmol.js
* Official website (optional, not the repository): http://3dmol.csb.pitt.edu/
* NPM package url (optional): https://www.npmjs.com/package/3dmol
* License and its reference: BSD 3-claus
* Count of watchers: 30
* Count of stars: 336
* Count of forks: 102
* Downloads in the last week: 451
* [x ] I'm the author of this library
* [x ] I would like to add link to the page of this library on CDNJS on website / readme
* [x ] The first line of commit message is less then 50 chars; clean, clear and easy to understand.
* [ x] The parent of …

3Dmol: switch to npm based update

---

ajax/libs/ui-cropper/package.json

Initial commit using package.json method with auto-update enabled.
Closes #11250
Pull request for issue: [#11250](https://github.com/cdnjs/cdnjs/issues/11250)
* Git repository (required): https://github.com/CrackerakiUA/ui-cropper
* Official website (optional, not the repository): https://crackerakiua.github.io/ui-cropper/
* License and its reference: [MIT](https://github.com/CrackerakiUA/ui-cropper/blob/master/LICENSE)
* Count of watchers: 11
* Count of stars: 156
* Count of forks: 76
* NPM …

Add ui-cropper via single package.json w/ npm auto-update

---

ajax/libs/hideseek-mod/package.json

Pull request for issue: #13435
* Git repository (required): https://github.com/maxwroc/HideSeek-Mod
* Official website (optional, not the repository): http://maxwroc.github.io/HideSeek-Mod/
* NPM package url (optional): https://www.npmjs.com/package/hideseek-mod
* Count of watchers: 1
* Count of stars: 0
* Count of forks: 80
* Downloads in the last day: 173
* Downloads in the last week: 442
* …

Add hideseek-mod via single package.json w/ npm auto-update

---

ajax/libs/ali-oss/package.json

Add ali-oss via single package.json w/ npm auto-update

---

ajax/libs/scenejs/package.json

Pull request for issue: na
Related issue(s): na
* Git repository (required): https://github.com/daybrush/scenejs
* Official website (optional, not the repository): https://daybrush.com/scenejs
* NPM package url (optional): https://www.npmjs.com/package/scenejs
* Count of watchers: 21
* Count of stars: 759
* Count of forks: 31
* Downloads in the last day: 30
* Downloads in the last week: 321
* Downloads in the last month: 1K

Add scenejs via single package.json w/ npm auto-update

---

ajax/libs/vue-meta/package.json

Pull request for issue: na
Related issue(s): na
* Git repository (required): https://github.com/nuxt/vue-meta
* Official website (optional, not the repository): https://vue-meta.nuxtjs.org
* NPM package url (optional): https://www.npmjs.com/package/vue-meta
* Count of watchers: 37
* Count of stars: 2615
* Count of forks: 147
* Downloads in the last day: 
* Downloads in the last week: 142k
* Downloads in the last month: 588k

Add vue-meta via single package.json w/ git auto-update

---

ajax/libs/izitoast/package.json

Old [homepage](http://izitoast.marcelodolce.com/) is died.
* Git repository (required): https://github.com/marcelodolza/iziToast
* Official website (optional, not the repository): http://izitoast.marcelodolza.com/
* Count of watchers: 61
* Count of stars: 1895
* Count of forks: 210
* Downloads in …

Update homepage of izitoast.js

---

ajax/libs/vue-bootstrap-typeahead/package.json

* Git repository (required): https://github.com/alexurquhart/vue-bootstrap-typeahead
* Official website (optional, not the repository): https://alexurquhart.github.io/vue-bootstrap-typeahead/
* NPM package url (optional): https://github.com/alexurquhart/vue-bootstrap-typeahead/blob/master/package.json
* License and its reference: https://github.com/alexurquhart/vue-bootstrap-typeahead/blob/master/LICENSE.txt
* Count of watchers: 3
* Count of …

Add vue-bootstrap-typeahead via single package.json w/ npm auto-update

---

auto-update.js

respect .do_not_update

---

ajax/libs/between.js/package.json

close #12901, cc @sasha240100
Pull request for issue: #12901 
* Git repository (required): https://github.com/sasha240100/between.js
* Official website (optional, not the repository): https://between.js.org/
* NPM package url (optional): https://www.npmjs.com/package/between.js
* License and its reference: [MIT|https://github.com/sarahdayan/dinero.js/blob/master/LICENSE.md]
* Count of watchers: 18
* Count of stars: 632
* Count of forks: 14 …

Add between.js w/ npm auto-update via single package.json

---

ajax/libs/dplayer/package.json

Update MIT license & repo library dplayer

---

ajax/libs/blueprintjs-core/package.json

Pull request for issue: #9667 
@Piicksarn @cdnjs/intern2 could you please help me review this PR? Thanks!
* Git repository (required): https://github.com/palantir/blueprint
* Official website (optional, not the repository): http://blueprintjs.com/
* NPM package url (optional): https://www.npmjs.com/package/@blueprintjs/core
Watch 100
Star 4,529
Fork 130
- Downloads in the last day: no data
- Downloads in the last week: no data
- Downloads in the last month: no …

Add blueprintjs-core via single package.json w/ npm auto-update 

---

.gitignore
ajax/libs/webvr-polyfill/package.json

Pull request for issue: #11901 
* Git repository (required): https://github.com/immersive-web/webvr-polyfill
* Official website (optional, not the repository): https://immersive-web.github.io/webvr-polyfill/
* NPM package url (optional): webvr-polyfill
* License and its reference: Apache 2.0
- Count of watchers: 89
- Count of stars: 900
- Count of forks: 215
- Downloads in the last day: 186
- Downloads in the last week: 1,346 …

Add webvr-polyfil via single package.json w/ npm auto-update

---

ajax/libs/vast-client/package.json

Pull request for issue: #12210 
* Git repository (required): https://github.com/dailymotion/vast-client-js
* NPM package url (optional): https://www.npmjs.com/package/vast-client
- Count of watchers: 51
- Count of stars: 186
- Count of forks: 127
- Downloads in the last day: 38
- Downloads in the last week: 168
- Downloads in the last month: 842

Add vast-client via single package.json w/ npm auto-update

---

ajax/libs/hyphenopoly/package.json

* Git repository (required): https://github.com/mnater/Hyphenopoly
* Official website (optional, not the repository): https://mnater.github.io/Hyphenopoly/
* NPM package url (optional): https://www.npmjs.com/package/hyphenopoly
* License and its reference: MIT https://github.com/mnater/Hyphenopoly/blob/master/LICENSE
* Count of watchers: 17
* Count of stars: 250
* Count of forks: 22
* …

Add hyphenopoly via single package.json w/ npm auto-update 

---

ajax/libs/ui.multiselect/package.json

Pull request for issue: #11646 
@cdnjs/library-reviewer This lib is `jqgrid`'s dependent lib. Please help me review this PR ASAP, thanks!
* Git repository (required): https://github.com/michael/multiselect
* Official website (optional, not the repository): http://www.quasipartikel.at/multiselect
* License and its reference: MIT, https://github.com/michael/multiselect/blob/master/MIT-LICENSE.txt
Watch 24
Star 562
Fork 214

Add ui.multiselect via single package.json w/ git auto-update

---

ajax/libs/webicons/package.json

Reference:
https://github.com/adamfairhead/webicons/issues/2#issuecomment-6919938

add license of webicons, cc #5500

---

ajax/libs/react-is/package.json

Styled-components v5 which is in this cdnjs is dependent upon react-is which is not in cdnjs, which i why im trying to add the library.
Related issue(s): # remake of pull request #13697
* Git repository (required): https://github.com/facebook/react
* Official website (optional, not the repository): https://reactjs.org/
* NPM package url (optional): https://www.npmjs.com/package/react-is
* Count of watchers: 6.600 …

[New] Added package json for React-is

---

ajax/libs/ammaps/package.json

Pull request for issue: #10958 #10285
* Git repository (required): https://github.com/amcharts/ammap3
* Official website (optional, not the repository): https://www.amcharts.com/
* License and its reference: [Custom](https://github.com/amcharts/ammap3#license) & [Commercial License](https://github.com/amcharts/ammap3#commercial-license)
- Count of stars: 64
- Count of forks: 36

[New] Add ammaps w/ git auto-update and update/enrich package.json

---

ajax/libs/bootstrap-vue/package.json

close #12245, cc @pi0.
Pull request for issue: #12245
* Git repository (required): https://github.com/bootstrap-vue/bootstrap-vue/
* NPM package url (optional): https://www.npmjs.com/package/bootstrap-vue
- Count of watchers: 138
- Count of stars: 3018
- Count of forks: 501
- Downloads in the last day: 2748
- Downloads in the last week: 15000
- Downloads …

Add bootstrap-vue@1.3.0 w/ npm auto-update

---

ajax/libs/unistore/package.json

Pull request for issue: #12323 
* Git repository (required): https://github.com/developit/unistore
* NPM package url (optional): https://www.npmjs.com/package/unistore
- Count of watchers: 29
- Count of stars: 1262
- Count of forks: 30
- Downloads in the last week: 352
- Downloads in the last month: 529

[New] Add unistore@3.0.3 w/ npm auto-update

---

ajax/libs/maptalks/package.json

Pull request for issue: #12432
* Git repository (required):https://github.com/maptalks/maptalks.js
* Official website (optional, not the repository):https://maptalks.org
* NPM package url (optional):https://www.npmjs.com/package/maptalks
- Count of watchers:81
- Count of stars:1215
- Count of forks:115
- Downloads in the last day:110
- Downloads in the last week:265
- Downloads in the last month:1531

[New] Add maptalks@0.37.0 w/ npm auto-update

---

ajax/libs/outdated-browser-rework/package.json

* Git repository (required): https://github.com/mikemaccana/outdated-browser-rework
* NPM package url (optional): https://www.npmjs.com/package/outdated-browser-rework
* License and its reference: [MIT](https://github.com/mikemaccana/outdated-browser-rework/blob/master/LICENSE.md)
* Count of watchers: 3
* Count of stars: 95
* Count of forks: 32
* Downloads in the …

[New] Add outdated-browser-rework.js with autoupdate via NPM

---

ajax/libs/jquery.blockUI/package.json

Reference: https://github.com/malsup/blockui#copyright-and-license
CC: #11931

Update jquery.blockUI license info in package.json

---

ajax/libs/parsimmon/package.json

Add parsimmon w/ npm auto-update via single package.json

---

ajax/libs/logline/package.json

* Git repository (required): https://github.com/latel/logline
* NPM package url (optional):https://www.npmjs.com/package/logline
* Count of watchers: 24
* Count of stars: 277
* Count of forks: 32
* Downloads in the last day: 
* Downloads in the last week:29
* [√ ] I'm the author of this library
* [ √] I would like to add link to the page of this …

[New][Author] Add logline w/ npm auto-update via single package.json

---

ajax/libs/canvas-nest.js/package.json

This pr is just update the package urls, such as homepage, repo url.
- repo url is move to `hustcc`
- homepage move to [https://atool.vip/](https://atool.vip/)
Trouble for review, thanks!

update urls of the package

---

ajax/libs/query-string/package.json

Pull request for issue: #10334
* Git repository (required): https://github.com/sindresorhus/query-string
* NPM package url (optional): https://www.npmjs.com/package/query-string
- Count of watchers: 22
- Count of stars: 1662
- Count of forks: 144
- Downloads in the last day: 365,829
- Downloads in the last week: 1,972,824
- Downloads in the last month: 8,347,989

[New] Add query-string@5.0.1 w/ git auto-update

---

ajax/libs/turndown/package.json

Pull request for issue: #12397
* Git repository (required): https://github.com/domchristie/turndown
* Official website (optional, not the repository):https://domchristie.github.io/turndown/
* NPM package url (optional):https://www.npmjs.com/package/turndown
* License and its reference:MIT
- Count of watchers:79
- Count of stars:2662
- Count of forks:444
- Downloads in the last day:209
- Downloads in the last week:2743
- Downloads in the last month:4811

[New] Add turndown@4.0.1 w/ npm auto-update

---

ajax/libs/venn.js/package.json

closes #10912
Pull request for issue: #10912
* Git repository (required): https://github.com/benfred/venn.js
* NPM package url (optional): https://www.npmjs.com/package/venn.js
* License and its reference: MIT https://github.com/benfred/venn.js/blob/master/LICENSE
- Count of watchers: 36
- Count of stars: 557
- Count of forks: 140
- Downloads in the last day: 110 …

[New] Add venn.js w/ npm auto-update via single package.json

---

ajax/libs/hyperHtml/package.json

Pull request for issue: #12546
Related issue(s): #12547
* Git repository (required): https://github.com/WebReflection/hyperHTML
* Official website (optional, not the repository): https://viperhtml.js.org/hyper.html
* NPM package url (optional): https://www.npmjs.com/package/hyperhtml
* License and its reference: ISC License
- Count of watchers: 78
- Count of stars: 1,476
- Count of forks: 51
- Downloads in the last day: 411
- Downloads in the last week: 3101
- …

Add hyperHtml w/ npm auto-update via single package.json

---

ajax/libs/simple-icons/package.json

Switches from git to NPM auto-update
Updates repo to reflect new ownership
I was unsure if the version should be updated, given that the contribution guidelines explicitly tell me not to - but if your autoupdater checks if the new version > old version, then it should be manually changed (as the proper version is `1.6.7` and your current version claims to be `3.0.1`)
I was also unsure if the existing version folders should be deleted. Please do comment if they should.
Closes #12885
Pull request for issue: #12885 
* Git repository (required): https://github.com/simple-icons/simple-icons
* Official website (optional, not the repository): https://simpleicons.org …

[author] Update simple-icons package.json

---

ajax/libs/echarts-gl/package.json

Related issue(s): Closes #13729 
* Git repository (required): https://github.com/ecomfe/echarts-gl
* Official website (optional, not the repository): https://www.echartsjs.com/
* NPM package url (optional): https://www.npmjs.com/package/echarts-gl
* License and its reference: BSD
* GitHub / Bitbucket popularity:
* Count of watchers: 132
* Count of stars: 1.9k
* Count of forks: 601

Add echarts-gl

---

ajax/libs/cloudinary-jquery/package.json

Pull request for issue: #10411
Related issue(s): #7563 #13012 #13013
* Git repository (required): https://github.com/cloudinary/pkg-cloudinary-jquery
* Official website (optional, not the repository): http://cloudinary.com/
* NPM package url (optional): https://www.npmjs.com/package/cloudinary-jquery
* Count of watchers: 13/39
* Count of stars: 10/256
* Count of forks: 5/204
* Downloads in the last day: 11
* Downloads in the last week: 297
* Downloads in the last month: 2967

Add cloudinary-jquery via single package.json w/ npm auto-update

---

ajax/libs/country-region-dropdown-menu/package.json

* Git repository (required): https://github.com/geodatasource/country-region-dropdown-menu
* Official website (optional, not the repository): http://www.geodatasource.com/
* NPM package url (optional): https://www.npmjs.com/package/country-region-dropdown-menu
* License and its reference: https://github.com/geodatasource/country-region-dropdown-menu/blob/master/license.txt
* Count of watchers: 1
* Count of stars: 15
* Count of forks: 15
* NPM …

[author] Update country-region-dropdown-menu

---

ajax/libs/ant-design-vue/package.json

* Git repository (required): https://github.com/vueComponent/ant-design-vue.git
* NPM package url (optional): https://www.npmjs.com/package/ant-design-vue
* Count of watchers: 188
* Count of stars: 6069
* Count of forks: 580
* Downloads in the last week: 6341

[new] Add ant-design-vue with npm auto-update via single package.json

---

ajax/libs/g2plot/package.json

Pull request for issue: #13754 
* Git repository (required):https://github.com/antvis/g2plot
* Official website (optional, not the repository):https://g2plot.antv.vision/
* NPM package url (optional):https://www.npmjs.com/package/@antv/g2plot
* License and its reference: MIT https://github.com/antvis/g2plot/blob/master/LICENSE
* Count of watchers:58
* Count of stars:982
* Count of forks:91
* Downloads in the …

[new]  Add g2lot via single package.json

---

ajax/libs/jquery-file-upload/package.json

Add jquery-file-upload via single package.json w/ npm auto-update

---

ajax/libs/fastify/package.json

close #13219 
Pull request for issue: #13219 
* Git repository (required): https://github.com/fastify/fastify
* Official website (optional, not the repository): https://www.fastify.io
* NPM package url (optional): https://www.npmjs.com/package/fastify
* Count of watchers: 257
* Count of stars: 12.4k
* Count of forks: 797
* Downloads in the last week: 59,437

[new] Add fastify w/ npm auto-update via single package.json

---

ajax/libs/react-extras/package.json

close #13249
Pull request for issue: #13249 
* Git repository (required): https://github.com/sindresorhus/react-extras
* NPM package url (optional): https://www.npmjs.com/package/react-extras
* Count of watchers: 11
* Count of stars: 592
* Count of forks: 27
* Downloads in the last week: 1820

[new] Add react-extras w/ npm auto-update via single package.json

---

ajax/libs/mmenu-js/package.json

Pull request for issue: closes #13651
* Git repository (required): https://github.com/FrDH/mmenu-js
* NPM package url (optional): https://www.npmjs.com/package/mmenu-js
* License and its reference: [Creative Commons Attribution-NonCommercial 4.0 International License](https://github.com/FrDH/mmenu-js/blob/master/LICENSE.txt)
* Count of watchers: 126
* Count of stars: 2.3k
* Count of forks: 619 …

[new] Add mmenu-js via single package.json w/ npm auto-update

---

.gitignore
ajax/libs/tent-css/package.json

Pull request for issue: #12248
* Git repository (required): https://github.com/sitetent/tentcss
* Official website (optional, not the repository): https://css.sitetent.com/
* NPM package url (optional): https://www.npmjs.com/package/tent-css
* License and its reference: [MIT](https://github.com/sitetent/tentcss/blob/master/package.json#L7)
- Count of watchers: 16
- Count of stars: 386
- Count of forks: 26 …

Add tent-css w/ npm auto-update via single package.json

---

ajax/libs/emotion-core/package.json

Related issue(s): N/A - requested in https://twitter.com/nathan5x/status/1240361663070527488
* Git repository (required): https://github.com/emotion-js/emotion/tree/master/packages/core
* NPM package url (optional): https://www.npmjs.com/package/@emotion/core
* Count of stars: 10.3k
* …

Add emotion-core via single package.json w/ npm auto-update

---

ajax/libs/coffee-script/package.json

Update coffee-script w/ npm auto-update

---

ajax/libs/polymer/package.json

Resolves #4973 (hopefully)
Resolves #7671

Update polymer w/ npm auto-update

---

ajax/libs/bootstrap-confirmation2/package.json

Add bootstrap-confirmation2 via single package.json w/ npm auto-update

---

ajax/libs/angular-auto-validate/package.json

Add angular-auto-validate via single package.json w/ npm auto-update

---

ajax/libs/jsonform/package.json

Add jsonform via single package.json w/ npm auto-update

---

ajax/libs/shortid/package.json

Add shortid via single package.json w/ npm auto-update

---

ajax/libs/react-helmet/package.json

Add react-helmet via single package.json w/ npm auto-update

---

ajax/libs/deep-diff/package.json

Update deep-diff w/ npm auto-update

---

ajax/libs/autobahn/package.json

Add autobahn via single package.json w/ git auto-update

---

ajax/libs/load-awesome/package.json

Add load-awesome via single package.json w/ npm auto-update

---

ajax/libs/icepick/package.json

Add icepick via single package.json w/ npm auto-update

---

ajax/libs/jQuery.YoutubeBackground/package.json

Add jQuery.YoutubeBackground via single package.json w/ git auto-update

---

ajax/libs/quantumui/package.json

Add quantumui via single package.json w/ git auto-update

---

ajax/libs/google-palette/package.json

Add google-palette via single package.json w/ npm auto-update

---

ajax/libs/data-layer-helper/package.json

Add data-layer-helper via single package.json w/ npm auto-update

---

ajax/libs/angular-tooltips/package.json

Add angular-tooltips via single package.json w/ npm auto-update

---

ajax/libs/route-recognizer/package.json

Add route-recognizer via single package.json w/ npm auto-update

---

ajax/libs/microevent/package.json

Add microevent via single package.json w/ npm auto-update

---

ajax/libs/infamous/package.json

Update infamous w/ npm auto-update

---

ajax/libs/jsrsasign/package.json

Update jsrsasign w/ git auto-update

---

ajax/libs/d3-sankey/package.json

Update d3-sankey w/ npm auto-update

---

ajax/libs/playcanvas/package.json

Add playcanvas via single package.json w/ npm auto-update

---

ajax/libs/datatables-buttons/package.json

Add datatables-buttons via single package.json w/ npm auto-update

---

ajax/libs/datatables-fixedheader/package.json

Update datatables-fixedheader w/ npm auto-update

---

ajax/libs/collections/package.json

Add collections via single package.json w/ npm auto-update

---

ajax/libs/mergely/package.json

Add mergely via single package.json w/ npm auto-update

---

ajax/libs/yaml-js/package.json

Add yaml-js via single package.json w/ npm auto-update

---

ajax/libs/tldjs/package.json

Add tldjs via single package.json w/ npm auto-update

---

ajax/libs/angular-pdf-viewer/package.json

Add angular-pdf-viewer via single package.json w/ git auto-update

---

ajax/libs/react-tinymce/package.json

Add react-tinymce via single package.json w/ npm auto-update

---

ajax/libs/alpaca/package.json

Add alpaca via single package.json w/ npm auto-update

---

ajax/libs/bootstrap-dropdown-hover/package.json

Add bootstrap-dropdown-hover via single package.json w/ npm auto-update

---

ajax/libs/marzipano/package.json

Add marzipano via single package.json w/ npm auto-update

---

ajax/libs/react-dnd/package.json

Add react-dnd via single package.json w/ npm auto-update

---

ajax/libs/react-json-tree/package.json

Add react-json-tree via single package.json w/ npm auto-update

---

ajax/libs/angulartics2/package.json

Resolves #9346
Unsure what exactly from the lib is required due to its size, so I have included all JS & TS files.

Add angulartics2 via single package.json w/ npm auto-update

---

ajax/libs/videojs-vimeo/package.json

Add videojs-vimeo via single package.json w/ npm auto-update

---

ajax/libs/request/package.json

Add request via single package.json w/ npm auto-update

---

ajax/libs/object-path/package.json

Add object-path via single package.json w/ npm auto-update

---

ajax/libs/qrcodejs/package.json

Add qrcodejs via single package.json w/ npm auto-update

---

ajax/libs/cheerio/package.json

Add cheerio via single package.json w/ npm auto-update

---

ajax/libs/post-robot/package.json

Add post-robot via single package.json w/ npm auto-update

---

ajax/libs/codeflask/package.json

Add codeflask via single package.json w/ npm auto-update

---

ajax/libs/signalr.js/package.json

Pull request for issue: fixes #13370
Related issue(s): https://cdnjs.discourse.group/t/signalr-js-has-not-updated-to-2-4-1/327

Update signalr.js w/ npm auto-update

---

ajax/libs/hideseek-mod/package.json

File was not picked up for 2 months so trying to reuse the file structure from lib for which it worked.
I have noticed that bunch of libs added around Feb10th are not downloaded by auto-update script. Probably for the same reason as the case mentioned in https://github.com/cdnjs/cdnjs/issues/13670
Pull request for issue: https://github.com/cdnjs/cdnjs/issues/13435
* GitHub / …

Update hideseek-mod info

---

ajax/libs/react-toolbox/package.json

Add react-toolbox via single package.json w/ npm auto-update

---

ajax/libs/moment-business-days/package.json

Add moment-business-days via single package.json w/ npm auto-update

---

ajax/libs/dojo/package.json

Update dojo w/ git auto-update

---

ajax/libs/bf-solid/package.json

Add bf-solid via single package.json w/ npm auto-update

---

ajax/libs/ndarray/package.json

Add ndarray via single package.json w/ npm auto-update

---

ajax/libs/material-ui/package.json

Add material-ui via single package.json w/ npm auto-update

---

ajax/libs/wicked-good-xpath/package.json

Add wicked-good-xpath via single package.json w/ npm auto-update

---

ajax/libs/three.meshline/package.json

Add three.meshline via single package.json w/ npm auto-update

---

ajax/libs/textarea-autosize/package.json

Add textarea-autosize via single package.json w/ npm auto-update

---

ajax/libs/anchorme/package.json

Add anchorme via single package.json w/ npm auto-update

---

ajax/libs/gmaps-marker-clusterer/package.json

Add gmaps-marker-clusterer via single package.json w/ npm auto-update

---

ajax/libs/hchs-vue-charts/package.json

Add hchs-vue-charts via single package.json w/ npm auto-update

---

ajax/libs/moment-timer/package.json

Add moment-timer via single package.json w/ npm auto-update

---

ajax/libs/shifty/package.json

Add shifty via single package.json w/ npm auto-update

---

ajax/libs/zoid/package.json

Add zoid via single package.json w/ npm auto-update

---

ajax/libs/cep-promise/package.json

Add cep-promise via single package.json w/ npm auto-update

---

ajax/libs/ejs/package.json

Add ejs via single package.json w/ npm auto-update

---

ajax/libs/angular-ui-switch/package.json

Add angular-ui-switch via single package.json w/ npm auto-update

---

ajax/libs/waffle-grid/package.json

Add waffle-grid via single package.json w/ npm auto-update

---

ajax/libs/fluentui-react/package.json

Add fluentui-react via single package.json w/ npm auto-update

---

ajax/libs/knockstrap/package.json

Add knockstrap via single package.json w/ npm auto-update

---

ajax/libs/micromarkdown/package.json

Add micromarkdown via single package.json w/ npm auto-update

---

ajax/libs/ar.js/package.json

Add ar.js via single package.json w/ npm auto-update

---

ajax/libs/isomorphic-fetch/package.json

Update isomorphic-fetch w/ npm auto-update

---

ajax/libs/vazir-font/package.json

Add vazir-font via single package.json w/ git auto-update

---

ajax/libs/shabnam-font/package.json

Add shabnam-font via single package.json w/ git auto-update

---

ajax/libs/mapbox-gl-leaflet/package.json

Add mapbox-gl-leaflet via single package.json w/ npm auto-update

---

ajax/libs/bigtext/package.json

Add bigtext via single package.json w/ npm auto-update

---

ajax/libs/three-js-csg/package.json

Add three-js-csg via single package.json w/ npm auto-update

---

ajax/libs/simple-ajax-uploader/package.json

Add simple-ajax-uploader via single package.json w/ npm auto-update

---

ajax/libs/webextension-polyfill/package.json

Add webextension-polyfill via single package.json w/ npm auto-update

---

ajax/libs/angular-base64-upload/package.json

Add angular-base64-upload via single package.json w/ npm auto-update

---

ajax/libs/10up-sanitize.css/package.json

https://github.com/jonathantneal/sanitize.css

Update 10up-sanitize.css w/ npm auto-update

---

ajax/libs/optimizely/package.json

Add optimizely via single package.json w/ npm auto-update

---

ajax/libs/mainloop.js/package.json

Add mainloop.js via single package.json w/ npm auto-update

---

ajax/libs/nanogallery2/package.json

Add nanogallery2 via single package.json w/ npm auto-update

---

ajax/libs/mapbox-polyline/package.json

Add mapbox-polyline via single package.json w/ npm auto-update

---

ajax/libs/eventsource-polyfill/package.json

Add eventsource-polyfill via single package.json w/ npm auto-update

---

ajax/libs/art-template/package.json

Add art-template via single package.json w/ npm auto-update

---

ajax/libs/tonal/package.json

Add tonal via single package.json w/ npm auto-update

---

ajax/libs/angular2-materialize/package.json

Add angular2-materialize via single package.json w/ npm auto-update

---

ajax/libs/chart.piecelabel.js/package.json

Add chart.piecelabel.js via single package.json w/ npm auto-update

---

ajax/libs/firacode/package.json

Add firacode via single package.json w/ npm auto-update

---

ajax/libs/neataptic/package.json

Add neataptic via single package.json w/ npm auto-update

---

ajax/libs/kotlin/package.json

Add kotlin via single package.json w/ npm auto-update

---

ajax/libs/kiwi.js/package.json

Add kiwi.js via single package.json w/ git auto-update

---

ajax/libs/ngl/package.json

Add ngl via single package.json w/ npm auto-update

---

ajax/libs/graphlib/package.json

Add graphlib via single package.json w/ git auto-update

---

ajax/libs/videojs-contrib-media-sources/package.json

Add videojs-contrib-media-sources via single package.json w/ npm auto-update

---

ajax/libs/react-three-renderer/package.json

Add react-three-renderer via single package.json w/ npm auto-update

---

ajax/libs/carbon-components/package.json

Add carbon-components via single package.json w/ npm auto-update

---

ajax/libs/jQuery-QueryBuilder/package.json

Add jQuery-QueryBuilder via single package.json w/ npm auto-update

---

ajax/libs/xlsx-populate/package.json

Add xlsx-populate via single package.json w/ npm auto-update

---

ajax/libs/jQuery-formBuilder/package.json

Add jQuery-formBuilder via single package.json w/ npm auto-update

---

ajax/libs/huntjs/package.json

Add huntjs via single package.json w/ npm auto-update

---

ajax/libs/zebra_dialog/package.json

Add zebra_dialog via single package.json w/ npm auto-update

---

ajax/libs/smartquotes/package.json

Add smartquotes via single package.json w/ npm auto-update

---

ajax/libs/bootstrap-material-design-icons/package.json

Add bootstrap-material-design-icons via single package.json w/ npm auto-update

---

ajax/libs/share-this/package.json

Add share-this via single package.json w/ npm auto-update

---

ajax/libs/rison/package.json

Add rison via single package.json w/ npm auto-update

---

ajax/libs/react-day-picker/package.json

Add react-day-picker via single package.json w/ npm auto-update

---

ajax/libs/obelisk.js/package.json

Add obelisk.js via single package.json w/ npm auto-update

---

ajax/libs/preact-router/package.json

Add preact-router via single package.json w/ npm auto-update

---

ajax/libs/videojs-panorama/package.json

Add videojs-panorama via single package.json w/ npm auto-update

---

ajax/libs/base32/package.json

Add base32 via single package.json w/ npm auto-update

---

ajax/libs/qiniu-js/package.json

* Git repository (required): https://github.com/qiniu/js-sdk
* Official website (optional, not the repository): https://developer.qiniu.com/kodo/sdk/1283/javascript
* Count of watchers: 70
* Count of stars: 1.2k
* Count of forks: 486

Add qiniu-js via single package.json w/ npm auto-update

---

ajax/libs/wade/package.json

Add wade via single package.json w/ npm auto-update

---

ajax/libs/leaflet-search/package.json

Add leaflet-search via single package.json w/ npm auto-update

---

ajax/libs/videojs-contrib-quality-levels/package.json

Add videojs-contrib-quality-levels via single package.json w/ npm auto-update

---

ajax/libs/fitty/package.json

Add fitty via single package.json w/ npm auto-update

---

ajax/libs/laravel-echo/package.json

Add laravel-echo via single package.json w/ npm auto-update

---

ajax/libs/table-to-json/package.json

Add table-to-json via single package.json w/ npm auto-update

---

ajax/libs/react-timeago/package.json

Add react-timeago via single package.json w/ npm auto-update

---

ajax/libs/vue-functional-calendar/package.json

Add vue-functional-calendar via single package.json w/ git auto-update

---

ajax/libs/jquery-deparam/package.json

Add jquery-deparam via single package.json w/ npm auto-update

---

ajax/libs/vue-markdown/package.json

Add vue-markdown via single package.json w/ npm auto-update

---

ajax/libs/feathers/package.json

Add feathers via single package.json w/ npm auto-update

---

ajax/libs/railroad-diagrams/package.json

Add railroad-diagrams via single package.json w/ npm auto-update

---

ajax/libs/reflex-grid/package.json

Add reflex-grid via single package.json w/ npm auto-update

---

ajax/libs/impetus/package.json

Add impetus via single package.json w/ npm auto-update

---

ajax/libs/nanoid/package.json

Add nanoid via single package.json w/ npm auto-update

---

ajax/libs/plaid/package.json

Add plaid via single package.json w/ npm auto-update

---

ajax/libs/jquery-balloon-js/package.json

Add jquery-balloon-js via single package.json w/ npm auto-update

---

ajax/libs/promise-polyfill/package.json

Add promise-polyfill via single package.json w/ npm auto-update

---

ajax/libs/sticky-sidebar/package.json

Add sticky-sidebar via single package.json w/ npm auto-update

---

ajax/libs/jquery.event.move/package.json

Add jquery.event.move via single package.json w/ npm auto-update

---

ajax/libs/epub.js/package.json

Add epub.js via single package.json w/ npm auto-update

---

ajax/libs/ajv-async/package.json

Add ajv-async via single package.json w/ npm auto-update

---

ajax/libs/paroller.js/package.json

Add paroller.js via single package.json w/ npm auto-update

---

ajax/libs/emoji-awesome/package.json

Add emoji-awesome via single package.json w/ npm auto-update

---

ajax/libs/file-upload-with-preview/package.json

Add file-upload-with-preview via single package.json w/ npm auto-update

---

ajax/libs/workbox-sw/package.json

Add workbox-sw via single package.json w/ npm auto-update

---

ajax/libs/nerd-fonts/package.json

Add nerd-fonts via single package.json w/ git auto-update

---

ajax/libs/pushy/package.json

This PR updates the homepage for [pushy](https://cdnjs.com/libraries/pushy)

[author] Update homepage in package.json

---

ajax/libs/js-jose/package.json

Add js-jose via single package.json w/ git auto-update

---

ajax/libs/scatterjs/package.json

Add scatterjs via single package.json w/ git auto-update

---

ajax/libs/nosleep/package.json

Update nosleep w/ git auto-update

---

ajax/libs/layer/package.json

Update layer w/ git auto-update

---

ajax/libs/jquery-mockjax/package.json

Update jquery-mockjax w/ git auto-update

---

ajax/libs/font-logos/package.json

Resolves https://github.com/cdnjs/cdnjs/issues/13955

Add font-logos via single package.json w/ git auto-update

---

.github/workflows/sync.yml

Use latest git-sync

---

CONTRIBUTING.md

"excepted" -> "accepted" in CONTRIBUTING.md
