cdnjs/cdnjs

ajax/libs/breezejs/package.json
Auto-update doesn't seem to be working.  Found a similar issue here:  https://github.com/cdnjs/cdnjs/issues/3873
The commit for this issue renamed the "repositories" property to "repository".
=> fixed auto-update bug

ajax/libs/aegis/package.json
I had made a mistake in the earlier package.json with the `basePath` configuration. This fixes that.
=> update aegis library to fix autoupdate paths

ajax/libs/textAngular/package.json
Change the include paths to include all the new paths in the v1.3.0 full and pre-releases.
=> [author] update textAngular to v1.3.0 format

ajax/libs/l20n/package.json
as discussed in https://bugzilla.mozilla.org/show_bug.cgi?id=1129965#c3
We prefer to change the package statement as "A client side localization library from Mozilla".
=> change description for l20n package

ajax/libs/backbone.js/package.json
Fixed backbone.js's package.json to be able to fetch its popularity from GitHub while indexing. Should fix #4368
=> Fixed backbone.js's package.json to be able to fetch its popularity

ajax/libs/ekko-lightbox/package.json
Modified package.json for ekko-lightbox to latest version for autoupdate but left version as 3.0.3a (current is 3.2.2) so that auto-update can do its thing.
This time with correct tab spacing.
=> Updating ekko-lightbox package.json

ajax/libs/react-router/package.json
The paths have changed from `/dist` to `/build/global` due to building
several targets for the 0.12 and 0.13 versions. This has prevented the
builds from entering the CDNJS repo
=> Updated React Router config to point to new paths

ajax/libs/trianglify/package.json
As of v0.2.0 I'm no longer providing non-minified builds of Trianglify.
This commit also removes a stray file that isn't a part of the repo.
=> Remove un-bundled source from trianglify files

build/zopfli.js, package.json, test/valid-packages-test.js
...because `fs.exists` and `fs.existsSync` will be deprecated.
=> Use is-there instead of fs.exists

ajax/libs/blueimp-file-upload/package.json, ajax/libs/fluidbox/package.json, ajax/libs/list.js/package.json, ajax/libs/list.pagination.js/package.json, ajax/libs/min.js/package.json, ajax/libs/qtip2/package.json, ajax/libs/reactive-coffee/package.json
Most other package.json's seem to have repositories be a list with dicts in them,
and the name being 'repositories' also makes sense with it being a list.
=> Make repositories field in package.json be consistently a list

ajax/libs/document-register-element/package.json
There is an extra file that arbitrary ships with this polyfill, it's called `innerHTML.js` and is a helper [necessary in some case](https://github.com/WebReflection/document-register-element/issues/21).
Thanks for the update.
=> [cleaned PR] Improved package.json autoupdate field

ajax/libs/textAngular/package.json
All our production files are only in the dist folder now.
=> OWNER: Update textAngular File structure.

test/valid-packages-test.js
Attempt to clarify that a trailing new line is part of the package.json format when you receive a formatting error. This caused me a moment of confusion trying to copy and paste the example before examining other working files.
=> Clarify that a trailing blank line is required in package.json

ajax/libs/angular-bindonce/package.json
@Amomo, I need your help for checking this PR.
The library had released the version 0.3.3 on git, however, the latest version installed from npm autoupdate still in 0.3.1.
In order to the reason, I think it's time to change the npm autoupdate to the git autoupdate for getting the latest version of the library.
Thank you!
=> Replace npm autoupdate with git autoupdate in angular-bindonce. close 4972.

ajax/libs/markdown.js/package.json
Hi @LeaYeh , From #5276, I would like to fix markdown.js to point to a stable version.
repo: https://github.com/evilstreak/markdown-js
This lib doesn't have auto-update, so I add npm auto-update config in package.json.
I think you may need to install it from npm for checking the file map.
The latest version on npm is v0.5.0,  but it doesn't provide minified version.
cdnjs has the minified file already, so I only record it in "requiredFile" field.
=> add auto-update config & point to a stable version of markdown.js

ajax/libs/json-mask/package.json
@Piicksarn , From #5276, I would like to fix json-mask to point to a stable version.
repo: https://github.com/nemtsov/json-mask
In cdnjs, json-mask has auto-update config, so it is the latest version now.
I only modify the field of version to a stable version `0.3.4`.
=> point to a stable version v0.3.4 of json-mask

ajax/libs/two.js/package.json
Hi @maruilian11  , From #5276, I would like to fix two.js to point to a stable version.
repo: https://github.com/jonobr1/two.js
In cdnjs, two.js has auto-update config already, so it is the latest version now.
I only modify the field of version to a stable version `0.4.0`.
=> point to a stable version v0.4.0 of two.js

ajax/libs/crafty/package.json
@Amomo, would you please checking the pr for me?
This pr is for adding git auto-update in exist library.
The lib information is shown below. 
Thank you!
**`git repository url :`** https://github.com/craftyjs/Crafty
`Watch : 130` 
`Star : 1848`
`Fork : 452 `
=> add Crafty with git auto-update, close #5361

ajax/libs/domready/1.0.8/ready.js, ajax/libs/domready/1.0.8/ready.min.js, ajax/libs/domready/package.json
Hi @Piicksarn  , I add a new lib with git auto-update from the request #5251
repo: https://github.com/ded/domready
=> [new] add domready@1.0.8 with git auto-update, close #5251

ajax/libs/backbone-tastypie/package.json
#5500 
License link: [https://github.com/PaulUithol/backbone-tastypie/blob/master/LICENSE.txt](https://github.com/PaulUithol/backbone-tastypie/blob/master/LICENSE.txt)
=> Enrich backbone-tastypie's package.json(field: license)

ajax/libs/KaTeX/package.json
This adds an autoupdate section to the KaTeX package.json.
Some questions:
- I didn't actually add the current version of KaTeX nor the intermediate versions which we have missed updating; do you want me to add the current one here?
- Does the autoupdating look at the git tags from a repository? We have recently started actually committing built files in separate off-master commits that are tagged (which is why we didn't add auto-updating before!). Will that work? This also means that some older versions won't be able to be auto-updated, since the built files don't exist in the repository at those tags. Do you want me to add those manually?
Hopefully this works. Thanks!
=> [author] Add KaTeX Autoupdate

ajax/libs/highmaps/package.json
Hi @maruilian11  , 
For #5194 and #5544 , I update the license & repository field in first commit.
highmaps use `"Creative Commons Attribution-NonCommercial 3.0 License"`,
You can find this info from http://shop.highsoft.com/highmaps.html
And, according to [SPDX License List](https://spdx.org/licenses/), it could be noted as `"CC-BY-NC-3.0"`
For #5525 , I add git auto-update config in the second commit.
repo: https://github.com/highslide-software/highmaps-release
I follow the official release pack and files already on cdnjs to add auto-update config.
download page: http://www.highcharts.com/download
official release: http://code.highcharts.com/zips/Highmaps-1.1.8.zip
lib on cdnjs: https://cdnjs.com/libraries/highmaps
=> add auto-update config & update package.json of highmaps

ajax/libs/highstock/package.json
Hi @Piicksarn , 
For #5500 and #5194 , I update the license & repository field in first commit.
highstock use `"Creative Commons Attribution-NonCommercial 3.0 License"`,
You can find this info from http://shop.highsoft.com/highstock.html
And, according to [SPDX License List](https://spdx.org/licenses/), it could be noted as `"CC-BY-NC-3.0"`
For #5525 , I add git auto-update config in the second commit.
repo: https://github.com/highslide-software/highstock-release
I follow the official release pack and files already on cdnjs to add auto-update config.
download page: http://www.highcharts.com/download
official release: http://code.highcharts.com/zips/Highstock-2.1.8.zip
lib on cdnjs: https://cdnjs.com/libraries/highstock
=> add auto-update config & update package.json of highstock

ajax/libs/prettify/package.json
Hi @LeaYeh  , From #5420, I have updated info in package.json of prettify.
From #5500, I have added license info.
old repo : https://code.google.com/p/google-code-prettify
repo : https://github.com/google/code-prettify
The repo on GitHub don't have tags, so I don't add auto-update config.
=> update package.json of prettify

ajax/libs/backbone.fetch-cache/package.json
#5500
License link: [https://github.com/madglory/backbone-fetch-cache/blob/master/LICENSE](https://github.com/madglory/backbone-fetch-cache/blob/master/LICENSE)
=> Enrich backbone.fetch-cache's package.json(field: license)

ajax/libs/backbone.layoutmanager/package.json
#5500 
license link: [https://github.com/tbranyen/backbone.layoutmanager/blob/master/LICENSE](https://github.com/tbranyen/backbone.layoutmanager/blob/master/LICENSE)
=> Enrich  backbone.layoutmanager's package.json(field: license)

ajax/libs/backbone.marionette/package.json
#5500 
license link: [https://github.com/marionettejs/backbone.marionette/blob/master/license.txt](https://github.com/marionettejs/backbone.marionette/blob/master/license.txt)
=> Enrich  backbone.marionette's package.json(field: license)

ajax/libs/react/package.json
In facebook/react#4901 we're going to be moving `react-dom.js` outside of the `react` npm package. For now we'd like to keep that file still in the same project here on the CDN (and we're still distributing it with the `react` bower package). In order to do that we need to point the autoupdater at the repo we use for bower instead of npm.
I think the only difference here is that we store RCs here. We always published those to npm as well but because we never used the `latest` tag, they never ended up here.
=> Change React auto-updating to use git

ajax/libs/backbone.modelbinder/package.json
#5500 
license link: [https://github.com/theironcook/Backbone.ModelBinder#legal-info-mit-license](https://github.com/theironcook/Backbone.ModelBinder#legal-info-mit-license]
=> Enrich backbone.modelbinder's package.json(field: license)

ajax/libs/aws-sdk/package.json
Hi @Piicksarn  , 
From #5500, I have added license info.
repo : https://github.com/aws/aws-sdk-js
=> Enrich aws-sdk's package.json(field: license)

ajax/libs/bootstrap-confirmation/package.json
Hi @Amomo  , 
For #5500 , I update the license.
bootstrap-confirmation use `"MIT License"`,
You can find this info from https://github.com/tavicu/bs-confirmation#copyright-and-license
Would you mind checking this PR for me?
=> Enrich bootstrap-confirmation's package.json(field: license)

ajax/libs/unveil/package.json
Hi @Piicksarn `unveil` is a lib aleady in cdnjs.
repo: https://github.com/luis-almeida/unveil
For #5422, because unveil don't provide keywords in its repo.
I pick some words from README.md as keywords.
And, I found some typo in the "author" field, so I corrected it.
For #5818, I add git auto-update config in the package.json.
=> add homepage & keywords & git auto-update in unveil

ajax/libs/backbone.syphon/package.json
#5500 
license link: [https://github.com/marionettejs/backbone.syphon/blob/master/package.json](https://github.com/marionettejs/backbone.syphon/blob/master/package.json)
=> Enrich backbone.syphon's package.json(field: license)

ajax/libs/backbone-forms/package.json
Hi @Amomo  , 
For #5500 , I update the license.
backbone-forms use `"MIT License"`,
You can find this info from https://github.com/powmedia/backbone-forms/blob/master/LICENSE
repo : https://github.com/powmedia/backbone-forms
=> Enrich backbone-forms's package.json(field: license)

ajax/libs/remoteStorage/package.json
Added auto-update tag and made `package.json` compliant to `test/schemata/npm-package.json`.
FYI, previously [remotestorage/remotestorage.js](https://github.com/remotestorage/remotestorage.js) directory structure was
release/v0.8.0
release/v0.9.0
...
now it's just
release/stable
.
Thanks a bunch.
=> [author] Updated package.json for remoteStorage

ajax/libs/remoteStorage/package.json
@PeterDaveHello, I mistakenly thought remoteStorage still had two licenses, but I was wrong. Sorry. Here is another PR to fix it.
I've updated package.json to match the right license: MIT.
Thanks a bunch!
=> [author] Update remoteStorage's license

ajax/libs/jQuery.mmenu/package.json
Hi. I noticed that the latest version of jQuery.mmenu library is not available on cdnjs.
The directory structure has been changed since jQuery.mmenu v5.4.0 and auto update is not working after that. This pull request fixes auto update settings of the library.
- Latest version
- https://github.com/BeSite/jQuery.mmenu/tree/v5.5.2/dist
- Latest available version on cdnjs
- https://github.com/BeSite/jQuery.mmenu/tree/v5.3.4/dist
=> Update package.json of jQuery.mmenu

ajax/libs/shaka-player/package.json
Shaka Player v1.6.0 includes new build variants that should be distributed on cdnjs.
See also google/shaka-player#116
=> Update shaka-player package.json to include new build variants

ajax/libs/free-jqgrid/package.json
The next version of free jqGrid will provide *.map to all *.js and *.css files.
=> Update package.json to include *.map files

ajax/libs/jquery.smartbanner/package.json
#5500 
license link: [https://github.com/jasny/jquery.smartbanner/blob/master/LICENSE](https://github.com/jasny/jquery.smartbanner/blob/master/LICENSE)
[https://github.com/jasny/jquery.smartbanner/search?utf8=%E2%9C%93&q=MIT](https://github.com/jasny/jquery.smartbanner/search?utf8=%E2%9C%93&q=MIT)
=> Enrich jquery.smartbanner's package.json(field: license)

CONTRIBUTING-WIP.md
old version can't pass the test
=> modify npm auto-update example to fit test format

ajax/libs/jquery-boilerplate/3.5.0/jquery.boilerplate.js, ajax/libs/jquery-boilerplate/3.5.0/jquery.boilerplate.min.js, ajax/libs/jquery-boilerplate/package.json
@Amomo  , would you mind to have a look at the pr?
The PR is referenced to issue  #6121
The git repo : https://github.com/jquery-boilerplate/jquery-boilerplate/tree/v3.5.0
Thank you!
=> Add jquery-boilerplate@3.5.0 with git autoupdate

ajax/libs/typescript/package.json
"typescript" is a library already on cdnjs, but it don't have auto-update config.
repo: https://github.com/Microsoft/TypeScript
npm package url: https://www.npmjs.com/package/typescript
For #6102 and #6238, I add `npm` auto-update config in typescript's package.json.
For #5500, I add license info in the package.json.
Also, I modify the "repository" field to its GitHub repo, and add "author" field.
=> add npm auto-update & update package.json of typescript

ajax/libs/angular-morris-chart/1.1.4/angular-morris-chart.js, ajax/libs/angular-morris-chart/1.1.4/angular-morris-chart.min.js, ajax/libs/angular-morris-chart/package.json
Hi @LeaYeh 
For #6059, I add angular-morris-chart at v1.1.4  and add `npm` auto-update config in its package.json.
repo: https://github.com/stewones/angular-morris-chart
npm package url: https://www.npmjs.com/package/angular-morris-chart
=> [new] add angular-morris-chart@1.1.4 with npm auto-update

ajax/libs/Uniform.js/package.json
#6324 
License type: MIT
Source: https://github.com/pixelmatrix/uniform#uniform
=> add license info of Uniform.js

ajax/libs/batman.js/package.json
PR for #6324 
Hi,
license of batman.js is referenced from
https://github.com/batmanjs/batman#license
=> add license info to batman.js

ajax/libs/bean/package.json
#6324
add missing license of bean
[License](https://github.com/fat/bean/blob/master/LICENSE)
=> add missing license of bean

ajax/libs/eve.js/package.json
#6324
[ref](https://github.com/Yuffster/Eve.js/blob/master/MIT_LICENSE.txt)
=> add license to eve.js

ajax/libs/gumby/package.json
for #6324
note: https://github.com/GumbyFramework/Gumby
=> add missing license info of gumby

ajax/libs/jquery-hashchange/package.json
**git repo url:** https://github.com/cowboy/jquery-hashchange/tree/v1.3
**Watch 58
Star 1101
Fork 246**
@Amomo   could you help me check out the PR for #6197   ? thank you~
=> Add auto-update config and licence into jquery-hashchange

ajax/libs/jqPlot/package.json
Hi @Piicksarn , this PR is for #6097
I have update the url of repository to a correct url in package.json.
repo: https://github.com/jqPlot/jqPlot
I didn't add auto-update config because the repo don't have tags.
However, they are planning to have tags!
https://github.com/jqPlot/jqPlot/issues/28
=> fix repository url of jqPlot

ajax/libs/jsrender/package.json
jsrender v0.9.71 can be downloaded from npm package.
=> modify auto-update config to npm of jsrender

ajax/libs/systemjs/package.json
because #6517, i found there is a typo error, so the latest version can't be updated.
=> fix npm auto-update config typo of systemjs

ajax/libs/canvas-nest.js/package.json
Hi @Piicksarn
`canvas-nest.js` has been add to project last week(see #6544 ), now need to modify the auto-update method to `npm`, thx
` Watch 9 ` ` Star 156 ` ` Fork 62 `
=> modify canvas-nest.js auto-update method to npm

ajax/libs/bitcoinjs-lib/package.json, ajax/libs/bonsai/package.json, ajax/libs/bootstrap-social/package.json, ajax/libs/chaplin/package.json
For #6324 
- bitcoinjs-lib [License ref](https://github.com/bitcoinjs/bitcoinjs-lib#license)
- bonsai [License ref](https://github.com/uxebu/bonsai/blob/master/LICENSE)
- bootstrap-social [License ref](https://github.com/lipis/bootstrap-social/blob/gh-pages/LICENSE)
- chaplin [License ref](https://github.com/chaplinjs/chaplin/blob/master/MIT-LICENSE.txt)
=> Add license info of bitcoinjs-lib, bonsai, bootstrap-social, chaplin with MIT

ajax/libs/jquery-migrate/package.json
jquery-migrate v1.3.0 has been released a few days ago. So this seems like the perfect time to add autoupdate to this module.
=> Enable npm autoupdate for jquery-migrate

PULL_REQUEST_TEMPLATE.md
Hi @PeterDaveHello I found a typo in the [PULL_REQUEST_TEMPLATE.md](https://github.com/cdnjs/cdnjs/blob/master/PULL_REQUEST_TEMPLATE.md).
- **Count of `folks`**
(omitted)
=> fix typo in PULL_REQUEST_TEMPLATE.md

ajax/libs/BigVideo.js/package.json
This is the first PR since we support adding a library by only a single package.json!
Now you can add a lib by a single package.json, just don't provide the version info in the package.json, and add a valid auto-update confif, so that the lib will be treat as a new library without its real files, and the invalid indent will be also accepted in this situation.
Related commit:
- allow lib package.json have no version, just ignore that lib
- https://github.com/cdnjs/cdnjs/commit/b024a698819bd02ad796b45615ed72b25aa5e1d6
- lib without version info must have valid auto-update config
- https://github.com/cdnjs/cdnjs/commit/11b89a77eeec7acc2e9343b628a8b6ecff98920d
- allow wrong indent in lib without real file/version
- https://github.com/cdnjs/cdnjs/commit/77bbfc1c4b2659491dc374250e8ce128d8088e17 …
=> Add BigVideo.js by a single package.json

ajax/libs/mathjs/package.json
I saw cdnjs hadn't picked up the latest release of mathjs, v3.0.0.
This PR changes package.json to the preferred npm update script. I suppose that after updating the script, cdnjs will auomatically add mathjs v3.0.0.
Thanks!
=> Change mathjs library to npm update script

ajax/libs/select2/package.json
The home page for Select2 was switched during the 4.0.0 release to the new location at https://select2.github.io. This finally fixes the homepage link in the `package.json` here, since cdnjs never updated it after it was changed in the NPM package.
=> Correct Select2 home page

ajax/libs/boexfi/package.json
@PeterDaveHello 
cause old homepage url point to wrong website, so i remove the homepage field.
=> Remove homepage field for lib boexfi

ajax/libs/tinyColorPicker/package.json
jqColorPicker.js has colors.js as dependency
cc https://github.com/cdnjs/cdnjs/issues/6210#issuecomment-200550664
=> update auto-update config of tinyColorPicker

ajax/libs/lave/1.1.9/lave.js, ajax/libs/lave/package.json
* Git repository (required): https://github.com/jed/lave
* NPM package url (optional): https://www.npmjs.com/package/lave
- Count of stars: 785
- Count of forks: 17
- Downloads in the last day: 27
- Downloads in the last week: 77
- Downloads in the last month: 740
close #7323, cc @jed
=> add lave.js v1.1.9 with autoupdate config

ajax/libs/shaka-player/package.json
Shaka Player v2.0 only distributes one file, and it has moved to /dist/.
* Git repository (required): https://github.com/google/shaka-player
* NPM package url (optional): https://www.npmjs.com/package/shaka-player
- Count of stars: 544
- Count of watchers: 104
- Count of forks: 118
- Downloads in the last day: 34
- Downloads in the last week: 185
- Downloads in the last month: 1089
=> Update Shaka Player paths in preparation for v2.0

ajax/libs/free-jqgrid/package.json
Update `package.json` of free jqGrid (GitHub repository: [here](https://github.com/free-jqgrid/jqGrid), NPM package: [here](https://www.npmjs.com/package/free-jqgrid)).
Fix the structure of directories to better support of JavaScript modules together with the old format, where all module where merged together. One can get advantage of HTTP/2 recently installed on cdnjs.
Thanks in advance!
=> Update update.json of free-jqgrid

ajax/libs/Backbone.dualStorage/package.json, ajax/libs/angular-mousewheel/package.json, ajax/libs/guards/package.json, ajax/libs/ion.calendar/package.json, ajax/libs/jarallax/package.json, ajax/libs/jquery-dotimeout/package.json, ajax/libs/jvectormap/package.json, ajax/libs/min/package.json, ajax/libs/minimap/package.json, ajax/libs/ng-currency/package.json, ajax/libs/switchy.js/package.json, ajax/libs/typeahead-addresspicker/package.json, ajax/libs/vue-google-maps/package.json
repository info from target of git auto-update.
Affected 13 libs as follow:
- Backbone.dualStorage
- angular-mousewheel
- guards
- ion.calendar
- jarallax
- jquery-dotimeout
- jvectormap
- min
- minimap
- ng-currency
- switchy.js
- typeahead-addresspicker
- vue-google-maps
cc @PeterDaveHello
=> add missing repository info for some libs

ajax/libs/Clamp.js/package.json
Hi @maruilian11 , 
From #5500, I have added license info. https://github.com/josephschmitt/Clamp.js/blob/master/clamp.js#L5
repo : https://github.com/josephschmitt/Clamp.js
=> Enrich Clamp.js' package.json(field: license)

ajax/libs/Chart.js/package.json
Updating the Chart.js `package.json` to now npm auto update. Starting [this commit](https://github.com/chartjs/Chart.js/commit/9082507c1ccdbe1975519f49071d7e441de2a56d), dist files have been removed from the repository. See https://github.com/chartjs/Chart.js/pull/2555 for details.
=> Update package.json of Chart.js

ajax/libs/cloudinary-core/package.json, ajax/libs/cloudinary-jquery-file-upload/package.json
PR for #8512 
Because the basePath of `cloudinary-jquery-file-upload` and `cloudinary-core` is ```"."```, I modified `"."` to `""` and it can work.
close #8512
=> fixed auto-update can't update some libs

ajax/libs/politespace/package.json
hi @Amomo,
could you help me check this PR for #7407? thank you!
the author has added the pre-built file on git repo and npm package.
the `dist` folder include a `test` folder we don't need, so i use `politespace*` in filemap.
https://github.com/filamentgroup/politespace/issues/47
https://github.com/filamentgroup/politespace/tree/master/dist
=> add npm auto-update config of politespace, close #7407

ajax/libs/bootstrap-datepicker/package.json
The repository was moved from eternicode to uxsolutions. Github does redirect the old repository url, but to cleanup this config and avoid useless redirects I've updated the repository urls
=> Updated the repository url to the new organization

ajax/libs/annyang/package.json
Updating existing library after directory structure change.
Files used to be in root directory, now they are in [`dist/`](https://github.com/TalAter/annyang/tree/master/dist)
=> Update autoupdate basePath in annyang

ajax/libs/FileSaver.js/package.json, ajax/libs/bootstrap-notify/package.json, ajax/libs/es6-shim/package.json, ajax/libs/flexslider/package.json, ajax/libs/jquery-visibility/package.json, ajax/libs/mori/package.json, ajax/libs/portal/package.json, ajax/libs/processing.js/package.json, ajax/libs/punycode/package.json, ajax/libs/q.js/package.json, test/valid-packages-test.js
PR to 
- add and update basePath in auto-update for some libs  
Affected 10 libs as follow:
- bootstrap-notify
- es6-shim
- FileSaver.js
- flexslider
- jquery-visibility
- mori
- portal
-  processing.js
- punycode
- q.js
- add test to check basePath in auto-update
cc @PeterDaveHello , cc #9192
=> add and update basePath in auto-update for some libs

ajax/libs/wordcloud2.js/package.json
Reference:
https://github.com/timdream/wordcloud2.js/blob/0606e894731cb6f6fa2fda36dce348cd4f2d8e97/LICENSE
=> Add license info of wordcloud2.js, cc #5500

ajax/libs/viz.js/package.json
PR for #8527 
- update license from MIT -> Unlicense
- remove homepage point to github repo in pakcage.json
@kennynaoh @x09326 Please help me review this pull request, thank you.
close #8527
=> Update license and remove homepage of viz.js

ajax/libs/angular-deckgrid/package.json
=> Fix angular-deckgrid keyword typo

ajax/libs/clientside-haml-js/package.json
Reference:
https://github.com/uglyog/clientside-haml-js/commit/d15512fcb102d5387cd680f634689b4bb9cccd9f
=> Add license info of clientside-haml-js, cc #5500

ajax/libs/tinymce/package.json
for tinyMCE the "inlite" theme is missing
tinymce docs: https://www.tinymce.com/docs/demo/inlite/
=> include inlite theme for tinymce

ajax/libs/screenfull.js/package.json
https://github.com/sindresorhus/screenfull.js/blob/gh-pages/license
=> Add license of screenfull.js, cc #9248

ajax/libs/videojs-contrib-dash/package.json
References:
https://github.com/videojs/videojs-contrib-dash/blob/master/LICENSE
=> Add license info of videojs-contrib-dash, cc #5500

ajax/libs/livestamp/package.json
Refernce: https://github.com/mattbradley/livestampjs#license
cc #5500
=> Add license of livestamp, cc #5500

ajax/libs/jquery.tipsy/package.json
=> Correct license typo of jquery.tipsy

ajax/libs/flatpickr/package.json
PR for #9629 
Remove the `src` basepath. Ref: https://github.com/chmln/flatpickr/issues/411
@kennynaoh please help me review it, thanks
close #9629
=> update npm auto-update config of flatpickr

ajax/libs/viz.js/package.json
I've decided to license this project under the MIT license instead. See https://github.com/mdaines/viz.js/blob/master/LICENSE and #8527
=> [Author] Change viz.js license to MIT

ajax/libs/jquery-replace-text/package.json
Modified the spelling error of "licences".
=> Fix the spelling typo of jquery-replacetext "licenses"

ajax/libs/jquery.finderselect/package.json
Reference: https://github.com/evulse/finderSelect/blob/master/LICENSE.txt
=> Add license info of jquery.finderselect, cc #5500

ajax/libs/html5-history-api/package.json
#5500
#8774 
license link:
1. [https://github.com/devote/HTML5-History-API/blob/master/package.json](https://github.com/devote/HTML5-History-API/blob/master/package.json)
2. [https://github.com/devote/HTML5-History-API/blob/master/LICENSE-MIT](https://github.com/devote/HTML5-History-API/blob/master/LICENSE-MIT)
3. [https://github.com/devote/HTML5-History-API/commit/825d10706749e918a15c388e435365340743bf93](https://github.com/devote/HTML5-History-API/commit/825d10706749e918a15c388e435365340743bf93)
=> Enrich HTML5-History-API's package.json(field:license)

test/support/libsToRun.js, test/valid-packages-test.js
Adds support to running tests on individual lib.
Usage:
`npm test -- --only=jquery`
If passed a lib that doesn't exist:
```
➜  ✗ npm test -- --only=cat-the-great
> vows "--only=cat-the-great"
Couldn't find lib cat-the-great
```
To run tests against the entire directory, can still use `npm test`
=> Add "only" option to npm test, closes #5032

ajax/libs/tween.js/package.json
Pull request for issue: #10123
Transfer tween.js to git auto-update because release on GitHub is faster than NPM, , close #10123 
=> Transfer tween.js to git auto-update

build/packages.json.js
Pull request for issue: #10198
As stated in the issue #10198 the main reason of slow RSS build process was this git/bash command:
`git ls-tree -r --name-only HEAD | grep **/package.json | xargs -n 1 -P ' + threads + ' git log -1 --since="2 weeks ago" --name-status --format="blahcrap %ad" --`
I replaced it with the following command:
`git log --since="2 weeks ago" --name-status --format="blahcrap %ad" -- **/package.json`
and RSS build time decreased from 7 minutes to 3 seconds on my machine.
I also adjusted RSS generation code because new command produces slightly different output.
=> Optimize RSS build process, closes #10198

.github/PULL_REQUEST_TEMPLATE.md
To make the popularity order consistent with the GitHub repository page.
=> Reorder git repo popularity detail in PR template

spec/tools/fixFormatSpec.js, test/valid-packages-test.js, tools/fixFormat.js
Removes `dependencies` and `optionalDependencies` keys vi fixFormat script.
`peerDependencies` key is already being removed.
https://github.com/cdnjs/cdnjs/issues/10088
=> Drop dependencies from package.json, closes #10088

test/valid-packages-test.js
Pull request for issue: #10073 
Uses addition of `file` method to is-there module, which allows to check if the path exists _and_ is a file (not a directory).
`npm test` will fail if filename points to a directory.
=> npm test will error when filename is a directory, closes #10073

ajax/libs/bootstrap-rtl/package.json
Pull request for issue: #10389, #10793, #7927, #5295.
Add auto-update config in package.json of bootstrap-rtl to add its latest files to cdnjs and to add missing version of it.
Use `dist` as basePath instead of `dist/css` cause it meets the current file structure on cdnjs.
git repo: https://github.com/morteza/bootstrap-rtl
@cdnjs/intern3 Please help me review this pull request, thank you.
=> Add git auto-update config of bootstrap-rtl

ajax/libs/inferno/package.json
update auto-update config to exclude *.ts files
Pull request for issue: #10886 
@cdnjs/intern2 Please help me review this pull request, thank you.
* Git repository (required): https://github.com/infernojs/inferno
* NPM package url (optional):https://www.npmjs.com/package/inferno
=> update auto-update config of inferno

ajax/libs/justgage/package.json
Pull request for issue: #10974 
-  Transfer justgage to git auto-update because there are more and newer releases on GitHub than NPM
@cdnjs/intern2 @maruilian11 Please help me review this PR, thank you.
* Git repository (required): https://github.com/toorshia/justgage
* Official website (optional, not the repository): https://justgage.com/
* NPM package url (optional): https://www.npmjs.com/package/justgage
* License and its reference: MIT https://github.com/toorshia/justgage/blob/master/LICENSE
=> Transfer justgage to git auto-update

ajax/libs/jquery.gray/package.json
Added autoupdate via npm for jquery plugin grayscale
* Git repository (required): https://github.com/karlhorky/gray
* Official website (optional, not the repository): https://work.karlhorky.com/gray/
* NPM package url (optional): jquery-gray
- Count of stars: 469
- Count of forks: 90
- Downloads in the last day: 8
- Downloads in the last week: 169
- Downloads in the last month: 886
=> Update jquery.gray library info and add auto-update config

ajax/libs/vanilla-lazyload/package.json
Pull request for issue: #11057 
- Update auto-update config of vanilla-lazyload due to author said we don't need files under `src` folder anymore. ref: https://github.com/cdnjs/cdnjs/issues/11057#issuecomment-294142091
@cdnjs/intern2 @maruilian11 Please help me review this PR, thank you.
* Git repository (required): https://github.com/verlok/lazyload
* Official website (optional, not the repository): https://verlok.github.io/lazyload
* NPM package url (optional): https://www.npmjs.com/package/vanilla-lazyload
* License and its reference: MIT, https://github.com/verlok/lazyload/blob/master/license.md
=> Update auto-update config of vanilla-lazyload

ajax/libs/bulmaswatch/package.json
Pull request for issue: #10823
Related issue(s): #11322
* Git repository (required): https://github.com/jenil/bulmaswatch
- Count of stars: 107
=> [Author] Add bulmaswatch w/ git auto-update via single package.json

ajax/libs/billboard.js/package.json
Pull request for issue: #11409
Related issue(s): 
* Git repository (required): https://github.com/naver/billboard.js
* Official website (optional, not the repository): https://naver.github.io/billboard.js/
* NPM package url (optional): https://www.npmjs.com/package/billboard.js
* License and its reference: MIT, https://github.com/naver/billboard.js/blob/master/LICENSE
- Count of watchers: 31
- Count of stars: 908
- Count of forks: 1,151 …
=> [author][new] Add billboard.js w/ npm auto-update via single package.json

ajax/libs/typed.js/package.json
The base path has changed from `dist` to `lib` since v2.0
=> Update typed.js autoupdate config

PULL_REQUEST_TEMPLATE.md
Because the commit c484b8b1bdfaaf32e742a1687e927afe2de710c0 increase the requirement of the library popularity, I update the checklist of the notable popularity of the library.
=> Update lib's popularity of essential checklist

.gitignore
Pull request for issue: #10840
Related issue(s): https://github.com/cdnjs/cdnjs/pull/11561#issuecomment-319275422
Update .gitignore line 21 from `/ajax/libs/inferno/1.*.*-alpha.*` to `/ajax/libs/inferno/*-alpha.*` to exclude all possible inferno dummy versions in the future.
=> Update .gitignore for all inferno dummy versions

auto-update.js
Pull request for issue: #11049 
By checking if size of each file from the source equals zero, which means it is a empty file. We take the file only if it is not empty.
=> Fix auto-update.js to drop empty files from npm auto-update

ajax/libs/yepnope/package.json
Update it because the license yepnope used changed, cc #11931 
SPDX short identifier: BSD-3-Clause
Ref: https://github.com/SlexAxton/yepnope.js/blob/master/LICENSE.md
=> Update yepnope license info in package.json

ajax/libs/ionic/package.json
Update it because the license format is wrong, cc #11931
Ref: https://github.com/ionic-team/ionic/blob/master/LICENSE#L4
=> Update ionic license info in package.json

ajax/libs/jshashes/package.json
Update it because the license format is wrong, cc #11931
Ref: https://github.com/h2non/jshashes/blob/master/LICENSE
=> Update jshashes license info in package.json

ajax/libs/jo/package.json
Update it because the license format is wrong, cc #11931
Ref: https://github.com/davebalmer/jo/blob/ec767af487b8653778c36168c7b3a5f478753cc5/LICENSE.mdown
=> Update jo license info in package.json

ajax/libs/legojs/package.json
Update it because the license format is wrong, cc #11931
Ref: https://github.com/tybenz/presentation-js-legos/blob/gh-pages/js/reveal.js#L4
=> Update legojs license info in package.json

ajax/libs/ionicons/package.json
Update it because it didn't contain `url` field, cc #11931.
Ref: https://github.com/ionic-team/ionicons/blob/master/LICENSE
=> Update ionicons license info in package.json

README.md
Hello. I've copy-edited the README.md. These are just suggestions. Besides correcting some grammar and punctuation, I tried to reduce the length of some sentences and the use of passive to help improve readability. I also fixed the link to the API docs.
Pull request for issue: #11168
- Count of …
=> Copy-edit README.md Issue: #11168

ajax/libs/jquery.form/package.json
Update it because the license jquery.form used changed, cc #11931
Ref: https://github.com/jquery-form/form#license
=> Update jquery.form license info

ajax/libs/jquery.pep/package.json
Update it because it license is "MIT"
=> Update jquery.pep license identify format to SPDX package.json

ajax/libs/roundabout/package.json
cc #11931
Update it because the license roundabout used changed
Ref: https://github.com/fredleblanc/roundabout/blob/master/jquery.roundabout.js#L11-L40
=> Add roundabout license info in package.json

ajax/libs/moment-range/package.json
Pull request for issue: N/A
Related issue(s): N/A
CDN already hosts `moment-range` (https://cdnjs.com/libraries/moment-range).
The repo has since changed location - updating accordingly.
Old location: https://github.com/gf3/moment-range
New location: https://github.com/rotaready/moment-range
Auto-update is currently working (cdnjs correctly detected 3.1.0 release).
* Git repository (required): https://github.com/rotaready/moment-range
* NPM package url (optional): https://www.npmjs.com/package/moment-range
* License and its reference: Unlicense
- Count of watchers: 39
- Count of stars: 998
- Count of forks: 157
- Downloads in the last day: 8,532
- Downloads in the last week: 53,048
- Downloads in the last month: 200,476
I am …
=> Update moment-range repo location

ajax/libs/jquery.activity-indicator/package.json
cc #5500
According to:
https://github.com/cdnjs/cdnjs/blob/master/ajax/libs/jquery.activity-indicator/1.0.0/jquery.activity-indicator.js#L5
* Git repository (required): disappear
* Official website (optional, not the repository): disappear
=> Update jquery.activity-indicator lib license property in package.json

ajax/libs/jquery-validation-unobtrusive/package.json
Update the npmFileMap to correctly point to the dist directory
Pull request for issue: https://github.com/cdnjs/cdnjs/issues/12647
Related issue(s): https://github.com/cdnjs/cdnjs/issues/7176
=> Update jquery-validation-unobtrusive npmFileMap in package.json

ajax/libs/Snowstorm/package.json
Update it because its license is "BSD"
=> Update Snowstorm license info in package.json

ajax/libs/jquery.tablesorter/package.json
Update it because it's license is "MIT"
=> Update jquery.tablesorter license in package.json

ajax/libs/zrender/package.json
Before version `3.6.1`, the built artifacts of [zrender](
https://www.npmjs.com/package/zrender) were placed in [`build/`](https://github.com/ecomfe/zrender/tree/master/build). After that version, built files were placed in [`dist/`](https://github.com/ecomfe/zrender/tree/master/dist). As a result, cdnjs was unable to find updates and it's currently [11 versions behind](https://cdnjs.com/libraries/zrender).
The current version is [`4.0.4`](https://github.com/ecomfe/zrender/releases).
This PR adds the missing `dist` folder to the `package.json` so that the auto updater can locate the artifacts in the updated path.
=> Update zrender auto-update config, add `dist` folder

ajax/libs/elfinder/package.json
elFinder >= 2.1.39 will be include "img/*.svg" files.
c.f. https://github.com/Studio-42/elFinder/commit/f9b0e53d63d99e98c66cdd74d6c34e82b22bfe7e
=> [Author] Update auto-update config of elfinder

.gitignore
Prevent v1.0.0 ~ v1.2.0 from being fetched via .gitignore
Pull request for issue: #https://github.com/cdnjs/cdnjs/pull/10446#issuecomment-393571819
Related issue: #10446
=> Update .gitignore for v-mask incompatible versions

ajax/libs/qunit/package.json
The npm name was update due to it was changed from qunitjs to qunit
According to: https://github.com/cdnjs/cdnjs/blob/master/ajax/libs/qunit/package.json#L22
close #12849
Pull request for issue: #12849
=> [New] Update qunit auto-update and homepage

ajax/libs/scion/package.json
SCION has moved to gitlab. This pull request updates the `repository.url` and `npmFile` fields in package.json.
This fixes issue #12971 (I think).
The original pull requests to add SCION to cdnjs are here:
* #212
* #8782
Thank you for your help with this.
=> [author] Update SCION package information

ajax/libs/animations/package.json
As reported in #13182 the URL that animations linked to for the homepage was no longer working and so should be removed. This PR removes the dead URL.
=> Remove not found homepage URL for animations

README.md
A small PR to add the Discord community to the readme file.
We've been given some cool perks by Discord now (custom invite: https://discord.gg/cdnjs and custom splash art on that page).
They asked if we could link the Discord from this repo as well as the site :)
=> Add Community Discord to readme

ajax/libs/jsonld/package.json
I'm a jsonld.js upstream maintainer.  Many jsonld.js versions ago the npm package file layout for browsers changed to move from using the raw source js to using built js files in the dist dir.  This update reflects those changes for the latest release.
Related issue(s): https://github.com/digitalbazaar/jsonld.js/issues/278
=> [author] Update jsonld auto-update config and author url

ajax/libs/inputmask/package.json
* Git repository (required): https://github.com/RobinHerbots/Inputmask
* Official website (optional, not the repository): http://robinherbots.github.io/Inputmask
* NPM package url (optional): https://www.npmjs.com/package/inputmask
* License and its reference: https://github.com/RobinHerbots/Inputmask/blob/4.x/LICENSE.txt
* Count of watchers: https://github.com/RobinHerbots/Inputmask/watchers
* Count of stars: https://github.com/RobinHerbots/Inputmask/stargazers …
=> [author] Add inputmask w/ npm auto-update using single package.json 

ajax/libs/react-card-flip/package.json
Pull request for issue: N/A
Related issue(s): #13228 
* Git repository (required): https://github.com/AaronCCWong/react-card-flip
* Official website (optional, not the repository): https://aaronccwong.github.io/react-card-flip/
* NPM package url (optional): https://www.npmjs.com/package/react-card-flip
* License and its reference: MIT 
* Count of watchers: 3
* Count of stars: 64
* Count of forks: 22
* Downloads in the last day: 447 …
=> [author] Add react-card-flip w/ npm auto-update using single package.json

ajax/libs/FlexSearch/package.json
* Git repository (required): https://github.com/nextapps-de/flexsearch
* NPM package url (optional): https://www.npmjs.com/package/flexsearch
* License and its reference: Apache-2.0 https://github.com/nextapps-de/flexsearch/blob/master/LICENSE
* Count of watchers: 30
* Count of stars: 2664
* Count of forks: 45
* Downloads in the last day:  …
=> [Author] [New] Add FlexSearch.js with git auto-update via single package.json

ajax/libs/bootstrap4-duallistbox/package.json
* Git repository (required): https://github.com/istvan-ujjmeszaros/bootstrap-duallistbox
* Official website (optional, not the repository): https://www.virtuosoft.eu/code/bootstrap-duallistbox/
* NPM package url (optional): https://www.npmjs.com/package/bootstrap4-duallistbox
* Count of watchers: 45
* Count of stars: 490
* Count of forks: 215
* …
=> [new] Add bootstrap4-duallistbox with npm auto-update via single package.json

README.md
This pull request intends to make the following changes:
- Adding Open Collective, Patreon & Liberapay to the donation options on the README
- Removing Gratipay as it goes to a 404 and is not used on the website
- Updating the badges in the README header to match the donation options
=> Update support us links & badges and adjust readme

ajax/libs/mixitup/package.json
Change license format to cdnjs convention and add commercial license. #11931
Reference: https://www.kunkalabs.com/mixitup/licenses/
=> Update mixitup license info in package.json

ajax/libs/preact/package.json
Pull request for issue: #13485
My only inquiry for this change is:
Does the auto update script handle the older versions (8.5.2) gracefully if the `hooks` and `compat` folders don't exist?
* Git repository (required): https://github.com/preactjs/preact
* NPM package url (optional): https://www.npmjs.com/package/preact
* License and its reference: https://github.com/preactjs/preact/blob/master/LICENSE
* Count of watchers: 439
* Count of stars: 23,753
* Count of forks: 1,248
* Downloads in the last week: 196,625
=> Update preact auto-update to include hooks and compat modules

ajax/libs/mithril/package.json
It was severely outdated, including a dead link to the old website. I'm updating it to point to up-to-date information, with the description ripped straight from the current `package.json`.
Also, in v1, a `mithril/stream` submodule was added for a streams implementation with its own separate source file, but this was similarly erroneously *not* included.
Now if only the autoupdate mechanism also could by option copy the description and website from the published `package.json`.
=> Update Mithril's package info

ajax/libs/popmotion/package.json
The latest version on CDNJS is [4.3.4](https://cdnjs.com/libraries/popmotion).
The latest version on the github repo is now [8.1.1](https://github.com/Popmotion/popmotion/tree/master/packages/popmotion/dist).
The basepath has been changed from `""` to `"packages/popmotion/dist"`.
Pull request for issue: #12324
=> Update popmotion auto-update config

ajax/libs/cryptico/package.json
cc #5500
According to:
https://github.com/wwwtyro/cryptico/issues/11#issuecomment-51131177
Pull request for issue: #5500
=> Update cryptico library license property in package.json

ajax/libs/store.js/package.json
Related issue: #12336
The current version on CDNJS is outdated because the file structure on the upstream repo changed. I made this change so that auto-update can successfully grab the latest version.
=> Update auto-update config of store.js

ajax/libs/chartjs-plugin-zoom/package.json
Related PR in chartjs-plugin-zoom: https://github.com/chartjs/chartjs-plugin-zoom/pull/202
Hi,
We're working on auto-deployment of npm releases of `chartjs-plugin-zoom`. In this context, we switch to npm autoupdate mechanism.
Thanks!
=> Update chartjs-plugin-zoom auto-update config to use npm instead of git

ajax/libs/tesseract.js/package.json
Related issue(s): #9279 #9717
As tesseract.js releasve 1.0.11 and 1.0.12 on 2019/11/15, it is expected that cdnjs will auto-update the new versions. But until today no update triggered.
To solve the issue, I think it is better we switch to npm autoupdate mechanism, please kindly help to merge this PR to make it work.
Thanks 😃
=> Update tesseract.js auto-update config to use npm instead of git

ajax/libs/sql-formatter/package.json
Pull request for issue: #12740
Related issue(s): N/A
* Git repository (required): https://github.com/zeroturnaround/sql-formatter
* Official website (optional, not the repository): https://zeroturnaround.github.io/sql-formatter/
* NPM package url (optional): https://www.npmjs.com/package/sql-formatter
- Count of watchers: 16
- Count of stars: 163
- Count of forks: 45 …
=> [new] Adding new library, sql-formatter via package.json

libs/ajax/jquery-ajax-unobtrusive/package.json
Adds jquery-ajax-unobtrusive under libs/ajax/jquery-validation-unobtrusive using a package.json with npm auto-update config.
Pull request for issue: #12790 
Related issue(s): #11976
* Git repository (required): https://github.com/aspnet/jquery-ajax-unobtrusive
* Official website (optional, not the repository): www.asp.net
* NPM package url (optional): https://www.npmjs.com/package/jquery-ajax-unobtrusive
* License and its reference: https://aka.ms/jquery-ajax-license
* Count of watchers: 42
* …
=> [author] [new] Add jquery-ajax-unobtrusive via npm auto-update

ajax/libs/datatables-plugins/package.json
Resolves #5234
Resolves #6646
Note: *.lang is not in the cdnjs whitelist, and so will not be served currently.
=> Add datatables-plugins via single package.json w/ npm auto-update

ajax/libs/ant-design-icons-svg/package.json
Resolves #9500
It seems the original antd font requested is no longer used, so I'm adding this in instead.
=> Add ant-design-icons-svg via single package.json w/ npm auto-update

ajax/libs/placeholder-shiv/package.json
Update it because the license placeholder-shiv used has been updated, cc [#11931 ](https://github.com/cdnjs/cdnjs/issues/11931)
SPDX short identifier: BSD 3-Clause
ref: https://github.com/walterdavis/placeholder-shiv/blob/master/LICENSE.txt
=> Update placeholder-shiv license in package.json

ajax/libs/popper.js/package.json
perhaps the change in package name from `popper.js` to `popper-core` demands a new folder in cdnjs, similar to the new package in npmjs.
=> Update popper.js w/ npm auto-update

.github/ISSUE_TEMPLATE/config.yml
We switched over to using YML issue templates in cdnjs/packages a while ago to have custom forms -- this PR updates the links when creating an issue in this repo to point the user to the new templates in cdnjs/packages.
=> Update issue template links

.github/workflows/sync.yml
Self-hosted runner is a `s-8vcpu-16gb` DigitalOcean Droplet.
=> Switch sync to using self-hosted runner
