- ajax/libs/angular-mixpanel/1.0.0/angular-mixpanel.min.js
- ajax/libs/angular-mixpanel/package.json
Library source: https://github.com/kuhnza/angular-mixpanel 
This is the best library I could find for integrating mixpanel with angular. Would be nice to have it on cdnjs.
> [new] Added angular mixpanel 1.0.0

- ajax/libs/Leaflet.awesome-markers/package.json
> Add autoupdate for Leaflet.awesome-markers

- ajax/libs/gridstack.js/package.json
Hi,
I've added a source map file to a package
> add source map - gridstack.js

- ajax/libs/jquery.payment/package.json
Is this sufficient to kick off the automatic updating of this library, or should I include the latest version manually as well?
> Auto-update config for stripe/jquery.payment library.

- ajax/libs/riot/package.json
The next Riot version will include new files: riot+compiler.js and riot+compiler.min.js.
Added them to package.json.
> Changed Riot's package.json (added more files)

- ajax/libs/jquery.isotope/package.json
Update Isotope description, homepage, maintainers, git url
> jquery.isotope - add npm auto-update

- ajax/libs/ember-simple-auth/package.json
I have found a git repo with built files since #4318.
> Add autoupdate for ember-simple-auth

- ajax/libs/fullcalendar/package.json
I made some updates to this package's metadata so that the new information will show up on the cdnjs "Search for a library" page.
> [author] fullcalendar package.json updates

- ajax/libs/lazysizes/package.json
> Added namespace property

- ajax/libs/ramda/package.json
One of the authors of Ramda here.  We forgot to include this update several versions back.  Will this automatically fetch the last several missing versions from NPM?  If not, should I do it manually?
> Note changed base path

- ajax/libs/Han/package.json
> Update the `basePath` since Han v3.1.0

- ajax/libs/showdown/package.json
Also changed repo url to `showdownjs/showdown`.
> Add npm updating to showdown

- CONTRIBUTING-WIP.md
- CONTRIBUTING.md
- README.md
...typos, code highlighting etc. :smile:
> Typo fixes in README and CONTRIBUTING files

- ajax/libs/jquery.hoverintent/package.json
Adds autoupdate, author, license, and corrects maintainers.
NOTE: A minified version is not available in the official repository at the moment.
> autoupdate jQuery.hoverIntent

- ajax/libs/html2canvas/package.json
Adds autoupdate and license, and corrects author.
> fixup html2canvas package.json (autoupdate, etc.)

- README.md
Maybe it would be useful to other people. :smile:
> Information on how to use cdnjs-importer

- ajax/libs/seedrandom/package.json
Seedrandom 2.4.0 includes more files that should be be included.
> Include additional files in seedrandom.

- ajax/libs/knockout-pre-rendered/package.json
This PR adds auto-updating for the  [knockout-pre-rendered](https://github.com/ErikSchierboom/knockout-pre-rendered) library.
> Added auto-updating for Knockout-pre-rendered library [author]

- ajax/libs/ready.js/0.1.0/ready.js
- ajax/libs/ready.js/0.1.0/ready.min.js
- ajax/libs/ready.js/package.json
> [author][new] Add ready.js

- ajax/libs/ie8/package.json
I should have done this a while ago, unfortunately realized just recently last two versions of `ie8` got skipped: https://github.com/WebReflection/ie8/issues/17
This should solve for any further change.
Thank You
> Added package.json autoupdate field for ie8

- package.json
- test/valid-packages-test.js
Updated [`is-there`](https://github.com/IonicaBizau/node-is-there) to 2.0.0. :sparkle:
> Is there 2.0.0

- ajax/libs/moment-range/package.json
Restructuring in an upcoming release.
> [author] Add /dist/ to npmFileMap for moment-range

- ajax/libs/highlight.js/package.json
This is to add images included in some styles. Didn't realize that they weren't being added in for while.
> [author] Update highlight.js' package.json

- package.json
> Upgrade is-there to 4.0.0

- ajax/libs/URI.js/package.json
- ajax/libs/angularSubkit/package.json
- ajax/libs/featherlight/package.json
- ajax/libs/ngStorage/package.json
- ajax/libs/quickblox/package.json
- test/valid-packages-test.js
This would automate some of the review feedback from #4760.
> Test autoupdate block for validity when present

- ajax/libs/randomcolor/package.json
Is this the right way to get cdnjs to update to latest release for randomColor? It's currently 2 releases behind.
> added auto update information for randomColor

- ajax/libs/commandz/package.json
I don't quite get how autoupdate works, hope all is well.
> Setup autoupdate for CommandZ

- ajax/libs/material-design-iconic-font/package.json
Update folder name in autoupdate file
> [author] Update autoupdate config in material-design-iconic-font

- ajax/libs/humane-js/package.json
> humane-js auto updater

- ajax/libs/qoopido.js/package.json
- add git autoupdate settings
- remove npm autoupdate settings
> [author] Update package.json

- ajax/libs/Faker/package.json
* filename format is more common in the git repo
* including locales
> use git autoupdate in Faker

- ajax/libs/crunch/package.json
@LeaYeh would you please help me checking the commit :)?
This commit is for adding git autoupdate config in crunch lib.
Thank you！
> Add git autoupdate config in crunch

- ajax/libs/json-mask/package.json
@Amomo could you plz help check this commit?
> Add git autoupdate config in json-mask

- ajax/libs/horsey/package.json
Hi @Piicksarn , I add some keywords for horsey.
Because there has no keywords provided from the repository, I pick some from readme.markdown.
Would you mind checking this PR for me?
Thank you~ :-)
> add keywords in package.json for horsey

- ajax/libs/emberFire/package.json
@maruilian11 Would you mind checking this PR for me?
> Add git autoupdate config in emberFire

- ajax/libs/swipe/package.json
@Piicksarn Would you mind checking this PR for me?
> Add git autoupdate config in swipe

- ajax/libs/backbone.modal/package.json
@Amomo could u plz help me check this pr from #5195, thx.
> point backbone.modal-bundled.js to backbone.modal-bundled-min.js, #5195

- ajax/libs/Sly/package.json
@Amomo, there are two commits included in this PR. First one is enrich lib's package.json, and the second one is add git autoupdate config in this lib. 
Would you please checking these commits for me?
The library information are shown below:
https://github.com/darsain/sly
http://darsa.in/sly
https://cdnjs.com/libraries/Sly
Thank you!
> Enrich Sly's package.json and add git autoupdate config in Sly. #5194 

- README.md
A pretty trivial change, but every little helps ;-)
> Fixed typo (relys -> relies)

- ajax/libs/backbone-react-component/package.json
@LeaYeh could u plz help me check this pr from #5195? thx.
> point backbone-react-component.js to backbone-react-component-min.js

- ajax/libs/rxjs-dom/package.json
@LeaYeh would you please checking the commit for me?
here is the Git repository url: https://github.com/Reactive-Extensions/RxJS-DOM/tree/v6.0.0
and link of cdnjs website: https://cdnjs.com/libraries/rxjs-dom
> Add git autoupdate config in rxjs-dom

- ajax/libs/scrollReveal.js/package.json
@LeaYeh would you please checkout the PR for me?
Thank you!
> Add git autoupdate config in scrollReveal.close #4948

- ajax/libs/jquery-countdown/package.json
@maruilian11, would you please checkout the pr for me?
i found that miss the git repository in jquery-coundown updating( #5381 )
Thank you!
> Enrich jquery-countdown's package.json #5194

- ajax/libs/jqModal/package.json
> update the homepage field of jqModal package.json

- ajax/libs/rangy/package.json
@maruilian11, would you please checkout the pr for me?
The library information is shown below.
Thank you!
**`The git repository url :`** https://github.com/timdown/rangy
- `watch` :  54
- `star` : 715
- `fork`  : 95
> Add git autoupdate config in rangy. close #5342

- ajax/libs/ocanvas/package.json
Built files are now in the git repo and it would be great to have it auto update from there. Thanks!
> [author] Use autoupdate for oCanvas

- ajax/libs/validator/package.json
Hi @Piicksarn from #5453, add git auto-update in validator's package.json
repo: https://github.com/chriso/validator.js
> add git auto-update in validator

- ajax/libs/datatables-colvis/package.json
> Enrich datatables-colvis's package.json(field: repository)

- ajax/libs/datatables-fixedheader/package.json
> Enrich datatables-fixedheader's package.json(field: repository)

- ajax/libs/simplemodal/package.json
> Enrich simplemodal's package.json(keywords/repository/license)

- ajax/libs/datatables-tabletools/package.json
> Enrich datatables-tabletools's package.json(field: repository)

- ajax/libs/highstock/package.json
> Enrich highstock's package.json(field: repository)

- ajax/libs/webfont/package.json
Hi @maruilian11 , From #5420, I have updated info in package.json of webfont.
From #5500, I have added license info.
old repo : http://code.google.com/apis/webfonts/docs/webfont_loader.html
repo : https://github.com/typekit/webfontloader
> update package.json of webfont

- ajax/libs/dat-gui/package.json
Hi @Piicksarn , From #5420, I have updated info in package.json of dat-gui.
From #5500, I also add license info.
repo: https://github.com/dataarts/dat.gui
> add auto-update config & update package.json of dat-gui

- ajax/libs/imgareaselect/package.json
> Enrich imgareaselect's package.json(field: repository)

- ajax/libs/rangy/package.json
Hi @Piicksarn , From #5420, I have updated info in package.json of rangy.
old repo : http://code.google.com/p/rangy/
repo : https://github.com/timdown/rangy
> update package.json of rangy

- ajax/libs/hprose-html5/package.json
> Enrich hprose-html5's package.json(field: license)

- ajax/libs/backbone-localstorage.js/package.json
> Enrich backbone-localstorage.js's package.json(field: license)

- ajax/libs/css-layout/package.json
As a follow-up to this PR https://github.com/cdnjs/cdnjs/pull/5562 a few keywords have been added.
> Added keywords to package.json for css-layout

- ajax/libs/lodash-fp/package.json
cc https://github.com/maruilian11/cdnjs/commit/85d7a57b8e9e7882b367acd77d38e562bd0a1b8e
update the package to match the last tag.
@PeterDaveHello could you please take a look? thank you.
> update lodash-fp dependencies

- ajax/libs/allow-me/package.json
- ajax/libs/jquery.colorbox/package.json
- ajax/libs/jquery.countdown/package.json
- ajax/libs/jquery_lazyload/package.json
- ajax/libs/jxon/package.json
- ajax/libs/leaflet-providers/package.json
- ajax/libs/ng-tags-input/package.json
- ajax/libs/ng-token-auth/package.json
- ajax/libs/ouibounce/package.json
- ajax/libs/plottable.js/package.json
- ajax/libs/progress.js/package.json
- ajax/libs/ramda/package.json
Affected libs( 12 libs):
- allow-me
- jquery.colorbox
- jquery.countdown
- jquery_lazyload
- jxon
- leaflet-providers
- ng-tags-input
- ng-token-auth
- ouibounce
- plottable.js
- progress.js
- ramda
@Amomo, would you mind to checkout the pr for me?
Thank you!
> Add keywords in libs #5422

- ajax/libs/backbone-super/package.json
#5500 
License link: [https://github.com/lukasolson/backbone-super/blob/master/LICENSE](https://github.com/lukasolson/backbone-super/blob/master/LICENSE)
> Enrich backbone-super's package.json(field: license)

- ajax/libs/balance-text/package.json
Add auto-update for adobe-webplatform/balance-text
> Add auto-update for adobe-webplatform/balance-text

- ajax/libs/jquery-contextmenu/package.json
@Piicksarn I added git auto-update config in jquery-contextmenu, from #5505 
repo: https://github.com/swisnl/jQuery-contextMenu
> add git auto-update config in jquery-contextmenu, close #5505

- ajax/libs/jquery.formset/package.json
Hi @maruilian11 , From #5420, I have updated info in package.json of jquery.formset.
From #5500, I also add license info.
old repo : https://code.google.com/p/django-dynamic-formset/
repo : https://github.com/elo80ka/django-dynamic-formset
The repo on GitHub don't have tags, so I don't add auto-update config.
> update package.json of jquery.formset

- ajax/libs/i18next/package.json
**git repo url:** https://github.com/i18next/i18next
**Watch 47
Star 1,083
Fork 180**
@LeaYeh could u help me check this PR for #5426? thank you!
i add some keywords from README.md.
> add i18next git autoupdate and update keywords, close #5426 

- ajax/libs/ng-table/package.json
**git repo url:** https://github.com/esvit/ng-table
**Watch 133
Star 1,748
Fork 553**
@LeaYeh could u help me check this PR for #5002? thank you!
> add ng-table v0.8.3 and update package.json

- ajax/libs/highcharts/package.json
Hi @LeaYeh , 
For #5194 and #5500 , I update the license & repository field in first commit.
highcharts use `"Creative Commons Attribution-NonCommercial 3.0 License"`,
You can find this info from http://shop.highsoft.com/highcharts.html
And, according to [SPDX License List](https://spdx.org/licenses/), it could be noted as `"CC-BY-NC-3.0"`
For #5525 , I add git auto-update config in the second commit.
repo: https://github.com/highslide-software/highcharts-release
download page: http://www.highcharts.com/download
official release: http://code.highcharts.com/zips/Highcharts-4.1.8.zip
> add auto-update config & update package.json of highcharts

- ajax/libs/bootstrap-colorpicker/package.json
#5500
@Piicksarn could you help me to check out this pr?
> bootstrap-colorpicker add license field with Apache-2.0

- ajax/libs/dc/package.json
Hello wonderful cdnjs community,
Please take this pull request, adding sourcemaps to dc.js - mostly to stop Chrome's debugger from complaining, but also occasionally to aide debugging. :grinning: 
Thanks!
Gordon
> add sourcemaps to dc.js

- ajax/libs/backbone.js/package.json
#5500
License link: [https://github.com/jashkenas/backbone/blob/master/LICENSE](https://github.com/jashkenas/backbone/blob/master/LICENSE)
> Enrich backbone.js's package.json(field: license)

- ajax/libs/ember-i18n/package.json
@maruilian11 could you help me to check this pr? 
#5276
> point ember-i18n's version number to a stable version 2.9.1

- ajax/libs/backbone.paginator/package.json
#5500 
license link: [https://github.com/backbone-paginator/backbone.paginator/blob/master/LICENSE-MIT](https://github.com/backbone-paginator/backbone.paginator/blob/master/LICENSE-MIT)
> Enrich backbone.paginator's package.json(field: license)

- ajax/libs/angular-ui-grid/package.json
**git repo url:** https://github.com/angular-ui/ui-grid
**Watch 308
Star 3,240
Fork 1,606**
@Piicksarn   could u help me check this PR for #5794  ? thank you!
> add missing font in auto-update filemap of angular-ui-grid

- ajax/libs/responsive-nav.js/package.json
**git repo url:** https://github.com/viljamis/responsive-nav.js
**Watch 218
Star 3,451
Fork 57**
@LeaYeh could u help me check this PR for #5851 ? thank you!
> correct the main file type of responsive-nav.js, close #5851

- ajax/libs/fdaciuk-ajax/0.0.9/ajax.min.js
- ajax/libs/fdaciuk-ajax/package.json
**git repo url:** https://github.com/fdaciuk/ajax
**Watch 16
Star 104
Fork 17**
@Amomo could u help me check this PR for #5866 ? thank you!
> add ajax v0.0.9 with git auto-update

- ajax/libs/jquery.cycle/package.json
**git repo url:** https://github.com/malsup/cycle
**Watch 101
Star 1,233
Fork 300**
@Amomo   could u help me check this PR for #5699 ? thank you!
> add git auto-update config of jquery.cycle, close #5699

- ajax/libs/jquery-countdown/package.json
#5500 
License link: [https://github.com/kbwood/countdown/blob/master/bower.json](https://github.com/kbwood/countdown/blob/master/bower.json)
[https://github.com/kbwood/countdown/blob/28f28299b48bf6d66c0164b0a0e845d27de44273/kbw.countdown.jquery.json](https://github.com/kbwood/countdown/blob/28f28299b48bf6d66c0164b0a0e845d27de44273/kbw.countdown.jquery.json)
> Enrich jquery-coutdown's package.json(field: license)

- ajax/libs/vue/package.json
Recently moved to the vuejs organization.
> Update Vue.js repo

- ajax/libs/resumable.js/package.json
#5500 
license link: [https://github.com/23/resumable.js/blob/master/MIT-LICENSE](https://github.com/23/resumable.js/blob/master/MIT-LICENSE)
[https://github.com/23/resumable.js/blob/master/bower.json](https://github.com/23/resumable.js/blob/master/bower.json)
> Enrich resumable.js's package.json(field: license)

- ajax/libs/jquery-cookie/package.json
**`git repository : `** https://github.com/carhartl/jquery-cookie/tree/v1.4.0
**`Watch : 458 /  Star : 7473 /  Fork : 3236`**
related issue : #5861
@maruilian11, would you mind to have a look at the pr?
> Add auto-update config on jquery-cookie, close #5861

- ajax/libs/html5-history-api/package.json
@Piicksarn could you help me check out the PR ? thank you~
cc https://github.com/devote/HTML5-History-API/issues/79
> modify html5-history-api licenses field

- ajax/libs/6to5/package.json
Hi @Amomo  , 
From #5500, I have added license info. https://github.com/babel/babel/blob/master/LICENSE#L3
repo : https://github.com/babel/babel
> Enrich 6to5's package.json(field: license)

- ajax/libs/FitText.js/package.json
Hi @Amomo , 
From #5500, I have added license info. https://github.com/davatron5000/FitText.js/blob/master/jquery.fittext.js#L6
> Enrich FitText.js' package.json(field: license)

- ajax/libs/FileSaver.js/package.json
Hi @maruilian11   , 
From #5500, I have added license info. https://github.com/eligrey/FileSaver.js/blob/master/LICENSE.md
repo : https://github.com/eligrey/FileSaver.js
> Enrich FileSaver.js' package.json(field: license)

- ajax/libs/dc/package.json
adding one more artifact to our distro
(oh joy)
thank you!
> add dc.min.css in auto-update filemap of dc

- ajax/libs/jstimezonedetect/package.json
https://github.com/pellepim/jstimezonedetect
> [author] NPM auto update configuration for jstimezonedetect and some general package.json changes

- ajax/libs/oj.VimeoVideo/package.json
**git repo url:** https://github.com/ojjs/oj.VimeoVideo
**Watch 1
Star 1
Fork 0**
@Amomo could you help me check out the PR for #6035 ? thank you~
> add git auto-update config of oj.VimeoVideo

- ajax/libs/easy-pie-chart/package.json
**git repo url:** https://github.com/rendro/easy-pie-chart
**Watch 104
Star 1,389
Fork 338**
@Amomo could you help me check out the PR for #6096 ? thank you~
i have asked author to add v2.1.7 tag.
> add auto-update config field of easy-pie-chart

- ajax/libs/ICanHaz.js/package.json
Hi @Piicksarn , 
From #5500, I have added license info. https://github.com/HenrikJoreteg/ICanHaz.js/blob/v0.10.3/LICENSE#L1
> Enrich ICanHaz.js' package.json(field: license)

- ajax/libs/jquery-throttle-debounce/package.json
**git repo url:** https://github.com/cowboy/jquery-throttle-debounce/tree/v1.1
**Watch 30
Star 812
Fork 125**
@maruilian11,  could you help for me check out the PR, which is referenced to  #6198 ? thank you~
> Add git autoupdate config in package.json of jquery-throttle-debounce.

- ajax/libs/jquery.cycle2/package.json
**git repo url:** https://github.com/malsup/cycle2
**Watch 82
Star 753
Fork 215**
@Amomo could you help me check out the PR for #5963 ? thank you~
> add auto-update config of Jquery.cycle2

- ajax/libs/etp/package.json
> modify npm name from jquery to etp of etp

- ajax/libs/peity/package.json
> change auto-update config from git to npm of peity

- ajax/libs/Counter-Up/1.0.0/jquery.counterup.js
- ajax/libs/Counter-Up/1.0.0/jquery.counterup.min.js
- ajax/libs/Counter-Up/package.json
For #5995, I add Counter-Up at v1.0.0 and add git auto-update config in its package.json.
repo: https://github.com/bfintal/Counter-Up
> [new] add Counter-Up@1.0.0 with git auto-update

- ajax/libs/froala-editor/package.json
> Add autoupdate config in froala-editor 

- ajax/libs/brain/package.json
license ref: https://github.com/harthur/brain/blob/master/LICENSE
> add license info of brain #6324

- ajax/libs/fingerprintjs/package.json
For  #6324
Ref https://github.com/Valve/fingerprintjs#licence
> Add license info of fingerprintjs

- ajax/libs/basket.js/package.json
#6324
[ref](https://github.com/angulartics/angulartics#license)
> add license of basket.js

- ajax/libs/fiber/package.json
source: https://github.com/linkedin/Fiber/blob/master/LICENSE.txt
#6324
> Add license of fiber #6324

- CONTRIBUTING-WIP.md
i think `dist` and `**/*` is better.
> modify npm auto-update example

- ajax/libs/angular-route-segment/package.json
PR for #6324
license info ref: https://github.com/artch/angular-route-segment#license
> add missing license of angular-route-segment

- ajax/libs/architect/package.json
PR for #6324
license info ref: https://github.com/EtienneLem/architect/blob/master/MIT-LICENSE
> add missing license of architect

- ajax/libs/atmosphere/package.json
PR for #6324
license info ref: https://github.com/Atmosphere/atmosphere-javascript/blob/master/LICENSE
> add missing license of atmosphere

- ajax/libs/bootstrap-hover-dropdown/package.json
As mentioned in https://github.com/CWSpear/bootstrap-hover-dropdown/issues/140#issuecomment-161130978
> Enable bootstrap-hover-dropdown autoupdate

- ajax/libs/cookiejar/package.json
https://github.com/walterdavis/cookiejar/blob/master/README.md
> Add licence info of cookiejar

- ajax/libs/pileup/package.json
See https://github.com/cdnjs/cdnjs/pull/6285#issuecomment-161201174
> Add license for pileup

- ajax/libs/jquery.nicescroll/package.json
For #6062 , I add git auto-update config on jquery.nicescroll in its package.json.
repo: https://github.com/inuyaksa/jquery.nicescroll/tree/3.6.0
> auto-update config on jquery.nicescroll, close #6062

- ajax/libs/gridly/1.1.0/gridly-col-widths.min.css
- ajax/libs/gridly/1.1.0/gridly-core.min.css
- ajax/libs/gridly/1.1.0/gridly.min.css
- ajax/libs/gridly/package.json
Added [`gridly`](https://github.com/IonicaBizau/gridly)––the 157B grid system. :dizzy: 
Fixes https://github.com/IonicaBizau/gridly/issues/1.
> Added gridly@1.1.0

- ajax/libs/jQuery.serializeObject/2.0.3/jquery.serializeObject.min.js
- ajax/libs/jQuery.serializeObject/package.json
**git repo url:** https://github.com/hongymagic/jQuery.serializeObject
**Watch 8
Star 98
Fork 51**
@Amomo could u help me check this PR for #6195 ? thank you!
> add jQuery.serializeObject v2.0.3

- ajax/libs/jquery-serialize-object/2.5.0/jquery.serialize-object.min.js
- ajax/libs/jquery-serialize-object/package.json
**git repo url:** https://github.com/macek/jquery-serialize-object
**Watch 35
Star 571
Fork 147**
@Amomo could u help me check this PR for #6194 ? thank you!
> add form-serializer v2.5.0

- ajax/libs/qtip2/package.json
Add auto-updating `npmName` and `npmFileMap` entries
> qTip2 - Update package.json - npmName + npmFileMap

- ajax/libs/qtip2/package.json
Was previously pointing to the old website.
> qTip2 - Amend homepage

- README.md
> modify npm auto-update example of README.md

- ajax/libs/fallback/package.json
> add git auto-update config of fallback

- ajax/libs/hideseek/0.6.2/jquery.hideseek.js
- ajax/libs/hideseek/0.6.2/jquery.hideseek.min.js
- ajax/libs/hideseek/package.json
**git repo url:** https://github.com/vdw/HideSeek
**Watch 19
Star 251
Fork 29**
@Piicksarn could u help me check this PR for #6257 ? thank you!
> add hideseek v0.6.2 

- ajax/libs/backbone-super/package.json
Hi @Piicksarn 
For #5194, I add repository info in the package.json of backbone-super.
repo: https://github.com/lukasolson/backbone-super
> add repository field in backbone-super

- ajax/libs/backbone-super/package.json
After #6321, I add npm auto-update config in the package.json of backbone-super.
repo: https://github.com/lukasolson/backbone-super
npm package url: https://www.npmjs.com/package/backbone-super
> add npm auto-update config in backbone-super

- ajax/libs/pegasus/0.3.2/pegasus-amd.js
- ajax/libs/pegasus/0.3.2/pegasus-amd.min.js
- ajax/libs/pegasus/0.3.2/pegasus-commonjs.js
- ajax/libs/pegasus/0.3.2/pegasus-commonjs.min.js
- ajax/libs/pegasus/0.3.2/pegasus.js
- ajax/libs/pegasus/0.3.2/pegasus.min.js
- ajax/libs/pegasus/package.json
@maruilian11 , would you mind to have a look at the pr?
The PR is referenced to issue  #5928.
The git repo : https://github.com/typicode/pegasus/tree/v0.3.2
Thank you!
> Add pegasus@0.3.2

- ajax/libs/crossfilter/package.json
source: https://github.com/square/crossfilter/blob/master/LICENSE
#6324
> Add license field for crossfilter, #6324

- ajax/libs/parallax/package.json
Hi @Piicksarn 
For #6515, I add git auto-update config in parallax's package.json.
repo url: https://github.com/wagerfield/parallax
> add git auto-update in parallax

- ajax/libs/commandz/package.json
ref : https://github.com/EtienneLem/commandz/blob/master/MIT-LICENSE
> add license info of commandz, #6324

- ajax/libs/angular-bootstrap-lightbox/package.json
https://github.com/cdnjs/cdnjs/pull/6550#issuecomment-166830559
> add author field of angular-bootstrap-lightbox

- ajax/libs/ifvisible/package.json
Hi @Piicksarn , for #6555
I add `npm` auto-update config in ifvisible's package.json.
repo url: https://github.com/serkanyersen/ifvisible.js
npm package url: https://www.npmjs.com/package/ifvisible.js
> add npm auto-update config in ifvisible

- ajax/libs/bootpag/1.0.7/jquery.bootpag.js
- ajax/libs/bootpag/1.0.7/jquery.bootpag.min.js
- ajax/libs/bootpag/package.json
Hi @maruilian11
For #6547, I add bootpag at v1.0.7 and add `npm` auto-update config in its package.json.
repo url: https://github.com/botmonster/jquery-bootpag
npm package url: https://www.npmjs.com/package/bootpag
> [new] add bootpag@1.0.7

- ajax/libs/foundation/package.json
**git repo url:** https://github.com/zurb/foundation-sites
**Watch 1461
Star 22131
Fork 4716**
@maruilian11,  could you help for me check out the PR, which is referenced to  #6519 ? thank you~
> Add git auto-update config on foundation

- ajax/libs/arbor/package.json
for #6324
[ref] (https://github.com/samizdatco/arbor/blob/master/README#L75)
> Add license info of arbor with MIT

- ajax/libs/SpeechKITT/package.json
Updated autoupdate setting as suggested by @PeterDaveHello
Thanks :)
> Updated autoupdate setting for SpeechKITT [author]

- ajax/libs/jquery-countdown/package.json
@Amomo  could you please help me check this PR for #6526 ? thank you!
> update package.json of Jquery countdown

- ajax/libs/chance/package.json
@Piicksarn could you help me check this PR for #6701? thank you!
> add npm auto-update config of chance

- ajax/libs/plupload/package.json
- ajax/libs/showdown/package.json
- ajax/libs/speakingurl/package.json
- ajax/libs/spectrum-i18n/package.json
- ajax/libs/tagmanager/package.json
- ajax/libs/webkit.js/package.json
- ajax/libs/yamlcss/package.json
For #5544, I have update the license info of these 7 libraries.
- [plupload](https://github.com/moxiecode/plupload)　[ref](https://github.com/moxiecode/plupload/blob/master/license.txt)
- [showdown](https://github.com/showdownjs/showdown)　[ref](https://github.com/showdownjs/showdown/blob/master/license.txt)
- [speakingurl](https://github.com/pid/speakingurl)　[ref](https://github.com/pid/speakingurl#license)
- [spectrum-i18n](https://github.com/bgrins/spectrum)　[ref](https://github.com/bgrins/spectrum/blob/master/package.json#L6)
- [tagmanager](https://github.com/max-favilli/tagmanager)　[ref](https://github.com/max-favilli/tagmanager#copyright-and-license)
- [webkit.js](https://github.com/trevorlinton/webkit.js)　[ref](https://webkit.org/licensing-webkit/)
- …
> update license info of libraries #4

- ajax/libs/jquery-dotimeout/1.0/jquery.ba-dotimeout.js
- ajax/libs/jquery-dotimeout/1.0/jquery.ba-dotimeout.min.js
- ajax/libs/jquery-dotimeout/package.json
**git repo url:** https://github.com/cowboy/jquery-dotimeout/tree/v1.0
**Watch 17
Star 275
Fork 30**
@Amomo   could you help me check out the PR for #6205   ? thank you~
> Add jquery-dotimeout@1.0 with git auto-update

- ajax/libs/jquery-outside-events/1.1/jquery.ba-outside-events.js
- ajax/libs/jquery-outside-events/1.1/jquery.ba-outside-events.min.js
- ajax/libs/jquery-outside-events/package.json
**git repo url:** https://github.com/cowboy/jquery-outside-events/tree/v1.1
**Watch 8
Star 211
Fork 32**
@maruilian11 could you help me check out the PR for #6203 ? thank you~
> Add jquery-outside-events@1.1 with git auto-update

- ajax/libs/jquery-replace-text/package.json
**git repo url:** https://github.com/cowboy/jquery-replacetext
@maruilian11  could you help me check out the PR for #6200    ? thank you~
> Add git autoupdate and licences into jquery-replacetext

- ajax/libs/json-schema-faker/.gitkeep
- ajax/libs/json-schema-faker/0.2.8/json-schema-faker.js
- ajax/libs/json-schema-faker/0.2.8/json-schema-faker.min.js
- ajax/libs/json-schema-faker/package.json
I would like to ask you to add json-schema-faker to cdnjs. Below are the informations I found in other PRs and issues. Please let me know if I need to do anything more.
PS cloning the repo is quite tough :disappointed: 
*Library name*: json-schema-faker
*Git repository url*: https://github.com/json-schema-faker/json-schema-faker
*npm package url(optional)*: json-schema-faker
*License(s)*: the MIT license
*Official homepage*: json-schema-faker.js.org
*Watch* 11
*Star* 202
*Fork* 20
> adding json-schema-faker

- ajax/libs/primeui/3.0.0/primeui-min.css
- ajax/libs/primeui/3.0.0/primeui-min.js
- ajax/libs/primeui/3.0.0/primeui.css
- ajax/libs/primeui/3.0.0/primeui.js
- ajax/libs/primeui/package.json
**git repo url:** https://github.com/primefaces/primeui-distribution
**Watch 1
Star 4
Fork 4**
@Amomo could u help me check this PR for #6812 ? thank you!
> add primeui v3.0.0

- ajax/libs/backbone.syphon/package.json
Updating repository URL due to project ownership change and enabled auto update
> [maintainer] Update to repo location and enabling auto update

- ajax/libs/jsoneditor/package.json
Changes:
- Fixes not all files from `dist` folder being copied.
- Fixes broken project url.
- Updated description.
See also #7008
> Update package.json of jsoneditor

- ajax/libs/fancyInput/package.json
https://github.com/cdnjs/cdnjs/pull/7113#discussion_r54558695
@PeterDaveHello sorry for checking carelessly.
> correct repo url of fancyInput

- ajax/libs/jquery-tiny-pubsub/0.7.0/ba-tiny-pubsub.js
- ajax/libs/jquery-tiny-pubsub/0.7.0/ba-tiny-pubsub.min.js
- ajax/libs/jquery-tiny-pubsub/package.json
Hi @maruilian11 this PR is for #6199.
I add `jquery-tiny-pubsub` at `v0.7.0` and add `git` auto-update config in its package.json.
* Git repository (required): https://github.com/cowboy/jquery-tiny-pubsub
- Count of stars: 50
- Count of watchers: **720**
- Count of forks: 178
> [new] add jquery-tiny-pubsub@0.7.0

- ajax/libs/jquery-datetimepicker/package.json
@Amomo could you help me check this PR for #7222 ? thank you!
we already hosted this lib, just need to add full files.
> update auto-update config of jquery-datetimepicker

- ajax/libs/angular-chart.js/package.json
> modify auto-update config of angular-chart.js from git to npm

- ajax/libs/jquery.inview/1.0.0/jquery.inview.js
- ajax/libs/jquery.inview/1.0.0/jquery.inview.min.js
- ajax/libs/jquery.inview/package.json
**git repo url:** https://github.com/zuk/jquery.inview
**Watch 16
Star 201
Fork 358**
@PeterDaveHello  could u help me check this PR for #5620 ? thank you!
[issue](https://github.com/zuk/jquery.inview/issues/22) about confirming the license
**there is only one version released.**
> add jquery.inview v1.0.0

- ajax/libs/leaflet.fullscreen/package.json
> add npm auto-update config of leaflet.fullscreen

- ajax/libs/jquery.tabslet.js/1.7.2/jquery.tabslet.js
- ajax/libs/jquery.tabslet.js/1.7.2/jquery.tabslet.min.js
- ajax/libs/jquery.tabslet.js/package.json
PR for #7369
@PeterDaveHello please help me review this pull request, thank you.
* Git repository (required): https://github.com/vdw/Tabslet
* NPM package url (optional): https://www.npmjs.com/package/tabslet
- Count of stars: 379
- Count of watchers: 20
- Count of forks: 73
- Downloads in the last day: 13
- Downloads in the last week: 34
- Downloads in the last month: 151
autoupdate config added, close #7369, …
> add jquery.tabslet.js 1.7.2

- ajax/libs/jquery-requestAnimationFrame/0.1.2/jquery.requestAnimationFrame.js
- ajax/libs/jquery-requestAnimationFrame/0.1.2/jquery.requestAnimationFrame.min.js
- ajax/libs/jquery-requestAnimationFrame/package.json
PR for #6883 
@pvnr0082t  please help me review this pull request, thank you.
* Git repository (required): https://github.com/gnarf/jquery-requestAnimationFrame
* Official website (optional, not the repository): https://github.com/gnarf/jquery-requestAnimationFrame
- Count of stars: 335
- Count of forks: 35
git …
> add jquery-requestAnimationFrame v0.1.2

- ajax/libs/imgareaselect/package.json
PR for #6207 
* Git repository (required): https://github.com/odyniec/imgareaselect
* Official website (optional, not the repository): http://odyniec.net/projects/imgareaselect/
- Count of stars: 567
- Count of watchers: 40
- Count of forks: 166
close #6207
> add auto-update for imgareaselect

- ajax/libs/jquery-requestAnimationFrame/package.json
PR for #6883
@pvnr0082t  please help me review this pull request, thank you.
* Git repository (required): https://github.com/gnarf/jquery-requestAnimationFrame
* Official website (optional, not the repository): https://github.com/gnarf/jquery-requestAnimationFrame
- Count of stars: 335
- Count of forks: 35
url updated, …
> Update repo url of jquery-requestAnimationFrame

- ajax/libs/Uniform.js/package.json
PR for #7660 
@dannyxx001 Please help me review this pull request, thank you.
* Git repository (required): https://github.com/AudithSoftworks/Uniform
* Official website (optional, not the repository): http://opensource.audith.org/uniform
* NPM package url (optional): https://www.npmjs.com/package/jquery.uniform
- Count of stars: 2231
- Count of watchers: 76
- Count of forks: 374
- Downloads in the last day: 46
- Downloads in the last week: 72
- Downloads in …
> add npm autoupdate config for Uniform.js

- ajax/libs/frzr/package.json
* Git repository (required): https://github.com/pakastin/frzr
* Official website (optional, not the repository): https://frzr.js.org
* NPM package url (optional): https://www.npmjs.com/package/frzr
- Count of stars: 160
- Count of forks: 12
- Downloads in the last day: 111
- Downloads in the last week: 1177
- Downloads in the last month: 7569
> add FRZR view library

- ajax/libs/fingerprintjs/package.json
PR for #7721 
* Git repository (required): https://github.com/Valve/fingerprintjs
* NPM package url (optional): https://www.npmjs.com/package/fingerprintjs
- Count of stars: 1784
- Count of watchers: 134
- Count of forks: 279
- Downloads in the last day: 77
- Downloads in the last week: 313
- Downloads in the last month: 1434
close #7721, cc @Valve
> add npm autoupdate config on fingerprintjs

- ajax/libs/backbone.stickit/package.json
PR for #7731 
@pvnr0082t please help me review this PR, thanks.
* Git repository (required): https://github.com/NYTimes/backbone.stickit
* Official website (optional, not the repository): https://nytimes.github.io/backbone.stickit/
* NPM package url (optional): https://www.npmjs.com/package/backbone.stickit
- Count of stars: 1647
- Count of watchers: 83
- Count of forks: 188
- Downloads in the last day: 139
- Downloads in the last week: 1273 …
> add npm autoupdate and homepage info for backbone.stickit

- ajax/libs/ckeditor/package.json
PR for #5865 
* Git repository (required): https://github.com/ckeditor/ckeditor-releases
* NPM package url (optional): https://www.npmjs.com/package/ckeditor
- Count of stars: 298
- Count of watchers: 63
- Count of forks: 151
- Downloads in the last day: 118
- Downloads in the last week: 836
- Downloads in the last month: 2673
close #5865, cc …
> add npm autoupdate config on ckeditor

- ajax/libs/jquery.cookieBar/0.0.1/cookieBar.css
- ajax/libs/jquery.cookieBar/0.0.1/cookieBar.min.css
- ajax/libs/jquery.cookieBar/0.0.1/jquery.cookieBar.js
- ajax/libs/jquery.cookieBar/0.0.1/jquery.cookieBar.min.js
- ajax/libs/jquery.cookieBar/package.json
PR for #7456 
* Git repository (required): https://github.com/carlwoodhouse/jquery.cookieBar
* Official website (optional, not the repository): https://carlwoodhouse.github.io/jquery.cookieBar/
- Count of stars: 65
- Count of forks: 15
close #7456, cc …
> add jquery.cookieBar v0.0.1 with git autoupdate config

- ajax/libs/react-router-redux/package.json
* Git repository (required): https://github.com/reactjs/react-router-redux
* Official website (optional, not the repository): -
* NPM package url (optional): https://www.npmjs.com/package/react-router-redux
- Count of stars: 3, 053
- Count of watchers: 118
- Count of forks: 238
- Downloads in the last day: 2, 216
- Downloads in the last week: 39,155
- Downloads in the last month: 195,073
I'm trying to follow @PeterDaveHello's advice from #3941:
> @ clayreimann we'll need much more time on the discussion about how to handle the files, but at the mean time, actually you can submit a PR on GitHub with only a single package.json, please take a look at #7149
This is my first time sending a library to `cdnjs`, so I …
> [new] Add react-router-redux v4.0.4 with npm auto-update config

- ajax/libs/ng2-formly/package.json
@kennynaoh, I have fixed the wrong repo url, please help me to review this pull request, thanks!
* Git repository (required): https://github.com/formly-js/ng2-formly
* Official website (optional, not the repository): http://formly-js.github.io/ng2-formly/
* NPM package url (optional): https://www.npmjs.com/package/ng2-formly
- Count of stars: 30
- Count of forks: 7
- Downloads in the last day: 2
- Downloads in the last week: 170
- …
> update repo url in ng2-formly 2.0.0-alpha.5

- ajax/libs/zabuto_calendar/package.json
PR to fix #7885 
* Git repository (required): https://github.com/zabuto/calendar
- Count of stars: 153
- Count of forks: 92
add repo info in package.json, cc #7885, cc @zabuto
> add repository information of zabuto_calendar

- ajax/libs/chaplin/package.json
@Amomo, would you please check out the commit for me?
the git repository url is shown below:
https://github.com/chaplinjs/chaplin
> Modifiy repository field in package.json of chaplin.

- test/valid-packages-test.js
add one check point to check repo info when using git auto-update, cc @PeterDaveHello
> [test] check repository when using git auto-update

- ajax/libs/mixitup/package.json
PR for #7822 
@dannyxx001 Please help me review this pull request, thank you.
* Git repository (required): https://github.com/patrickkunka/mixitup
* Official website (optional, not the repository): https://mixitup.kunkalabs.com/
- Count of stars: 3339
- Count of watchers: 180
- Count of forks: 508
correct homepage provided in #7822
> update homepage info for mixitup

- ajax/libs/soundplayer-widget/package.json
PR for #7966 
@pvnr0082t  please help me review it, thanks.
* Git repository (required): https://github.com/soundblogs/soundplayer-widget
* NPM package url (optional): https://www.npmjs.com/package/soundplayer-widget
- Count of stars: 23
- Count of watchers: 4
- Downloads in the last day: 32
- Downloads in the last week: 132
- Downloads in the last month: 516
close #7966
> add repo info in soundplayer-widget

- test/valid-packages-test.js
check repo exist when using git/npm auto-update config, cc @PeterDaveHello, cc #7905
> [test] update check repository when using auto-update

- ajax/libs/3Dmol/package.json
@pvnr0082t please help me review this pull request, thank you.
* Git repository (required): https://github.com/3dmol/3Dmol.js
* Official website (optional, not the repository): http://3dmol.csb.pitt.edu
- Count of stars: 166
- Count of forks: 45
cc #8000
> fix license of 3Dmol.js

- ajax/libs/qwest/package.json
Just a simple update of the existing package.json
> Add qwest homepage

- ajax/libs/acorn/package.json
PR for #8073 
@pvnr0082t please help me review this pull request, thank you.
* Git repository (required): https://github.com/ternjs/acorn
* NPM package url (optional): https://www.npmjs.com/package/acorn
- Count of stars: 1,651
- Count of watchers: 73
- Count of forks: 200
* NPM download stats (optional): 
- Downloads in the last day: 97,009
- Downloads in the last week: 2,000,572
- Downloads in the last month: 8,128,293
cc #8073
> add keywords in acorn

- ajax/libs/agility/package.json
PR for #8073 
* Git repository (required):https://github.com/arturadib/agility
* Official website (optional, not the repository):http://agilityjs.com
- Count of stars:558
- Count of watchers:33
- Count of forks:77
cc #8073
> Add missing keywords of Agility

- ajax/libs/alertify.js/package.json
PR for #8073 
* Git repository (required):https://github.com/fabien-d/alertify.js
* Official website (optional, not the repository):http://fabien-d.github.io/alertify.js/
- Count of stars:4219
- Count of watchers:209
- Count of forks:708
cc #8073
> Add missing keywords of alertify.js

- ajax/libs/algoliasearch-helper-js/package.json
PR for #8073 
@pvnr0082t please help me review this pull request, thank you.
* Git repository (required): https://github.com/algolia/algoliasearch-helper-js
- Count of stars: 36
- Count of watchers: 25
cc #8073
> add keywords in algoliasearch-helper-js

- ajax/libs/anchor-js/package.json
> Add missing keywords of anchor-js

- ajax/libs/loaders.css/package.json
> transfer loaders.css to use npm auto-update

- ajax/libs/load.js/package.json
@maruilian11 could plz check this pr?
lib: https://github.com/chriso/load.js
this lib has only one version.
#5500
> load.js add license field with MIT

- ajax/libs/jquery-date-range-picker/package.json
* Git repository (required):https://github.com/longbill/jquery-date-range-picker
* Official website (optional, not the repository):http://longbill.github.io/jquery-date-range-picker/
- Count of stars: 493
- Count of watchers: 36
- Count of forks: 223
* [] Close corresponding issue in commit message
* [] Mention related issue(s), people in …
> [author] Add jquery-date-range-picker by package.json

- ajax/libs/jquery.lazy/package.json
Add plugin files and update dependencies.
Use file rules as suggested in #8133.
> [author] Update package.json for jquery.lazy

- ajax/libs/javascript-debug/0.4/ba-debug.js
- ajax/libs/javascript-debug/0.4/ba-debug.min.js
- ajax/libs/javascript-debug/package.json
**git repo url:** https://github.com/cowboy/javascript-debug
**Watch 20
Star 425
Fork 63**
@Amomo could u help me check this PR for #6204 ? thank you!
> add javascript-debug v0.4 with git auto-update

- ajax/libs/angular-autofields/package.json
> modify keywords field in angular-autofields

- ajax/libs/angular-carousel/package.json
> Add keywords in angular-carousel, cc #5422

- ajax/libs/browser-logos/package.json
https://github.com/cdnjs/cdnjs/pull/7967#issuecomment-226268584
> correct repository url of browser-logos

- ajax/libs/vidom/package.json
* Git repository (required): https://github.com/dfilatov/vidom
* NPM package url (optional): https://www.npmjs.com/package/vidom
- Count of stars: 157
- Count of watchers: 15
- Count of forks: 9
> [author] [new] Add vidom by single package.json

- ajax/libs/angular-data/package.json
> Add keywords in angular-data, cc #5422

- ajax/libs/angular-datatables/package.json
PR for #5422 
@dannyxx001 please help me review it, thanks.
> Add keywords of angular-datatables

- README.md
Spelling correction in README.md, corrected "mechanishm" to read "mechanism"
> correct spelling of mechanism in readme

- ajax/libs/angular-dragula/package.json
> Add keywords of angular-dragula, cc #5422

- ajax/libs/angular-materialize/package.json
> Update package.json of angular-materialize

- ajax/libs/jszip-utils/0.0.2/jszip-utils-ie.js
- ajax/libs/jszip-utils/0.0.2/jszip-utils-ie.min.js
- ajax/libs/jszip-utils/0.0.2/jszip-utils.js
- ajax/libs/jszip-utils/0.0.2/jszip-utils.min.js
- ajax/libs/jszip-utils/package.json
PR for #7819 
* Git repository (required): https://github.com/Stuk/jszip-utils
* Official website (optional, not the repository): https://stuk.github.io/jszip-utils
* NPM package url (optional): https://www.npmjs.com/package/jszip-utils
- Count of stars: 33
- Downloads in the last day: 13
- Downloads in the last week: 58
- Downloads in the last month: 319 …
> add jszip-utils@0.0.2 w/ npm autoupdate

- .github/CONTRIBUTING.md
> Fix typo in .github/CONTRIBUTING.md

- ajax/libs/selectize.js/package.json
Not really sure how to proceed here, but I hope making this change will allow the lib to auto-update. I'm a maintainer of Selectize at https://github.com/selectize/selectize.js/.
> Selectize.js: Update ref to moved repo

- ajax/libs/attrchange/package.json
> Modify keywords field of attrchange, cc #5422

- ajax/libs/angular-truncate/package.json
> Fix "keywords" of angular-truncate, cc #5422

- ajax/libs/backbone.modal/package.json
> Add keywords of backbone.modal, cc #5422

- ajax/libs/pileup/package.json
> update autoupdate config of pileup

- ajax/libs/jquery-jcrop/package.json
@Amomo could you help me check this PR for #6206? thank you.
> add git auto-update config of jquery-jcrop

- ajax/libs/winjs/package.json
PR for #5422 
@kennynaoh please help me review it,thanks.
> Add keywords of winjs, cc #5422

- ajax/libs/task.js/package.json
* Git repository (required):https://github.com/icodeforlove/task.js
- Count of stars: 38
- Count of watchers: 1
- Count of forks: 2
> add task.js w/ npm autoupdate

- ajax/libs/t7/package.json
PR for #5422 
@pvnr0082t please help me review it,thanks.
> Add keywords of t7, cc #5422

- ajax/libs/jquery-contextify/package.json
Updated the homepage URL (the old one is dead).
> [author] Updated jquery-contextify homepage

- ajax/libs/accounting.js/package.json
PR for #5500 
@kennynaoh please help me review it.
> add license of accounting.js, cc #5500

- ajax/libs/plupload/package.json
> Add keywords of plupload, cc #5422

- ajax/libs/jquery-smoove/package.json
> [author] Updated jquery-smoove URL

- ajax/libs/jquery-i18next/package.json
PR for #8707 
@kennynaoh  Please help me review this pull request, thank you.
close #8707
> update npm auto-update of jquery-i18next

- ajax/libs/jquery.html5loader/package.json
> Add keywords of jquery.html5loader, cc #5422

- ajax/libs/jshint/package.json
> Add keywords of jshint, cc #5422

- ajax/libs/push.js/package.json
PR for #8748 
@kennynaoh please help me review it,thanks.
> update auto-update config of push.js

- ajax/libs/flag-icon-css/package.json
> Add keywords of flag-icon-css, cc #5422

- ajax/libs/meshki/package.json
* Git repository (required): https://github.com/Borderliner/Meshki
* Official website (optional, not the repository): http://meshki.borderliner.ir
* NPM package url (optional): https://npmjs.com/package/meshki
- Count of stars: 5
- Count of watchers: 5
- Downloads in the last day: 24
- Downloads in the last week: 379
- Downloads in the last month: 642
Well the project is pretty new, but it has decent downloads from NPM. Thanks in advance.
> [Author] [New] add Meshki v0.5.1 with npm auto-update

- ajax/libs/motion.js/package.json
> Add keywords of motion.js, cc #5422

- ajax/libs/mhayes-twentytwenty/package.json
> Add keywords of mhayes-twentytwenty, cc #5422

- ajax/libs/startbootstrap-sb-admin-2/package.json
* Git repository (required): https://github.com/BlackrockDigital/startbootstrap-sb-admin-2
* Official website (optional, not the repository): https://startbootstrap.com/template-overviews/sb-admin-2/
- Count of stars: 3487
- Count of watchers: 322
- Count of forks: 1767
> Update startbootstrap sb admin 2

- ajax/libs/history/package.json
- ajax/libs/react-modal/package.json
- ajax/libs/react-redux/package.json
- ajax/libs/react-router/package.json
- ajax/libs/redux/package.json
PR for #7913
Affected 5 libs as follow:
- history
- react-modal
- react-redux
- react-router
- redux
close #7913
> Update libs belong to rackt

- ajax/libs/gridlex/package.json
Folder to gridlex.min.css has changed from dist/ to docs/
> [author] update package.json for Gridlex path

- .github/CONTRIBUTING.md
> CONTRIBUTING.md: fix sparse checkout link

- ajax/libs/jump.js/1.0.1/jump.js
- ajax/libs/jump.js/1.0.1/jump.min.js
- ajax/libs/jump.js/package.json
PR for #8838 
* Git repository (required): https://github.com/callmecavs/jump.js
* Official website (optional, not the repository): http://callmecavs.com/jump.js/
* NPM package url (optional): https://www.npmjs.com/package/jump.js
- Count of stars: 2341
- Count of watchers: 57
- Count of forks: 96
- Downloads in the last day: 47
- Downloads in the last week: 312
- Downloads in the last month: 2209 …
> add jump.js@1.0.1 w/ npm autoupdate

- ajax/libs/Leaflet.awesome-markers/package.json
> Add keywords of Leaflet.awesome-markers, cc #5422

- ajax/libs/line-chart/package.json
> Add keywords of  line-chart, cc #5422

- build/packages.json.js
for #4599
Now write SRI data by "library name" / "library version" and store in the `sri` directory under the `new-website` repo.
> impliment SRI (again) for js and css with sha256

- circle.yml
hide npm test result on circle-ci if test passed
> hide npm test result on circle-ci if test passed

- ajax/libs/browser-deeplink/1.0.0/browser-deeplink.js
- ajax/libs/browser-deeplink/1.0.0/browser-deeplink.min.js
- ajax/libs/browser-deeplink/1.0.1/browser-deeplink.js
- ajax/libs/browser-deeplink/1.0.1/browser-deeplink.min.js
- ajax/libs/browser-deeplink/package.json
**npm package url:** https://www.npmjs.com/package/browser-deeplink
**30 downloads in the last day
84 downloads in the last week
341 downloads in the last month**
**git repo url:** https://github.com/hampusohlsson/browser-deeplink
**Watch 17
Star 252
Fork 84**
@Amomo could u help me check this PR for #8594 ? thank you!
> manually add browser-deeplink w/ git auto-update

- ajax/libs/mark.js/8.1.0/jquery.mark.es6.js
- ajax/libs/mark.js/8.1.0/jquery.mark.es6.min.js
- ajax/libs/mark.js/8.1.0/jquery.mark.js
- ajax/libs/mark.js/8.1.0/jquery.mark.min.js
- ajax/libs/mark.js/8.1.0/mark.es6.js
- ajax/libs/mark.js/8.1.0/mark.es6.min.js
- ajax/libs/mark.js/8.1.0/mark.js
- ajax/libs/mark.js/8.1.0/mark.min.js
I've forgot to increase the minor version before creating the tag.
> Updated mark.js v8.1.0

- ajax/libs/dracula/package.json
- ajax/libs/graphdracula/package.json
* Git repository (required): https://github.com/strathausen/dracula
* Official website (optional, not the repository): https://www.graphdracula.net
* NPM package url (optional): https://www.npmjs.com/package/graphdracula
a graph drawing library in JavaScript, see www.graphdracula.net
> Add dracula.js

- ajax/libs/webuploader/package.json
#5500
license link: https://github.com/fex-team/webuploader/blob/master/LICENSE
> Enrich webuploader's package.json(field:license)

- ajax/libs/angular-inview/package.json
PR for #8777 
There is a new file called: `angular-inview.spec.js` but we don't need it.
close #8777
> update autoupdate config of angular-inview

- ajax/libs/svgeezy/1.0.0/svgeezy.js
- ajax/libs/svgeezy/1.0.0/svgeezy.min.js
- ajax/libs/svgeezy/package.json
PR for #8950 
* Git repository (required):https://github.com/benhowdle89/svgeezy
* Official website (optional, not the repository):http://benhowdle.im/svgeezy/
- Count of stars:862
- Count of watchers:53
- Count of forks:91
close #8950, cc @benhowdle89
> Add svgeezy@1.0.0 w/ git auto-update config

- ajax/libs/agility/package.json
Modified misspelled license field, cc #5500
> Modified misspelled license field, cc #5500

- ajax/libs/augment.js/package.json
@kennynaoh 
Please help me review this PR, thanks.
[ref](https://github.com/olivernn/augment.js/blob/master/LICENSE)
> Add license of augment.js, cc #5500

- ajax/libs/bootstrap-notify/package.json
PR for #5500 
This is [reference](https://github.com/goodybag/bootstrap-notify/blob/master/js/bootstrap-notify.js).
> Add license of bootstrap-notify, cc #5500

- ajax/libs/aurora.js/package.json
PR for #5422 
@kennynaoh Please help me review it, thanks.
Reference is README of [aurora.js](https://github.com/audiocogs/aurora.js).
> Add keywords of aurora.js, cc #5422

- ajax/libs/balloon-css/package.json
> Add keywords of balloon-css, cc #5422

- ajax/libs/jquery-fullscreen-plugin/1.1.4/jquery.fullscreen-min.js
- ajax/libs/jquery-fullscreen-plugin/1.1.4/jquery.fullscreen.js
- ajax/libs/jquery-fullscreen-plugin/package.json
PR for #9116 
@pvnr0082t please help me review this pull request, thank you.
* Git repository (required): https://github.com/kayahr/jquery-fullscreen-plugin
- Count of stars: 282
- Count of watchers: 22
- Count of forks: 114
git auto-update config added, close #9116, cc @kayahr
> add jquery-fullscreen-plugin@1.1.4 w/ git autoupdate

- ajax/libs/space/package.json
PR for #5422 
@kennynaoh please help me review it.
Ref is Readme of this [lib](https://github.com/breck7/space).
> Add keywords of space, cc #5422

- ajax/libs/phery.js/package.json
> [new] Add phery.js w/ git autoupdate by a single package.json

- ajax/libs/jQuery-rwdImageMaps/1.6/jquery.rwdImageMaps.js
- ajax/libs/jQuery-rwdImageMaps/1.6/jquery.rwdImageMaps.min.js
- ajax/libs/jQuery-rwdImageMaps/package.json
PR for #9268 
* Git repository (required): https://github.com/stowball/jQuery-rwdImageMaps
* NPM package url (optional): 
- Count of stars: 1002
- Count of watchers: 87
- Count of forks: 409
close #9268, cc @stowball
> add jQuery-rwdImageMaps@1.6 w/ git autoupdate

- ajax/libs/sopa/package.json
Reference:
https://github.com/dougmartin/Stop-Censorship/blob/7d01c8b47f15b8958787e044d41f3d1af4559222/README.md
> Add license info of sopa, cc #5500

- ajax/libs/angular-cache/package.json
PR for #5422 
@dannyxx001 Please help me review this pull request, thank you.
> add keywords in angular-cache, cc #5422

- ajax/libs/spf/package.json
PR for #5422 
@kennynaoh 
Please help me review it.
Add keywords from [README](https://github.com/youtube/spfjs/blob/master/README.md) of spf.
> Add keywords of spf, cc #5422

- ajax/libs/sceditor/package.json
close #9296
* Git repository (required): https://github.com/samclarke/SCEditor
* Official website (optional, not the repository): http://www.sceditor.com/
* NPM package url (optional): https://www.npmjs.com/package/sceditor
- Count of stars: 310
- Count of watchers: 34
- Count of forks: 115
- Downloads in the last week: 42
- Downloads in the last month: 77
> [New] Add SCEditor w/ single package.json

- documents/sparseCheckout.md
/home/peter/.git/ should be ~/cdnjs
> Fix sparseCheckout document example output

- ajax/libs/angular-deckgrid/package.json
* Git repository (required): https://github.com/akoenig/angular-deckgrid
- Count of stars: 1,114
- Count of watchers: 46
- Count of forks: 208
> Add angular-deckgrid w/ single package.json

- ajax/libs/swiftclick/package.json
* Git repository (required): https://github.com/munkychop/swiftclick
* NPM package url (optional): https://www.npmjs.com/package/swiftclick
- Count of stars: 65
- Count of watchers: 9
- Count of forks: 5
- Downloads in the last day: 11
- Downloads in the last week: 78
- Downloads in the last month: 350
> Add swiftclick by single package.json

- test/valid-packages-test.js
PR for check empty files field in auto-update config.
And I have checked all **package.json**.
There is no affected lib.
cc @PeterDaveHello , cc #9299
> [test] check files in auto-update config file map

- ajax/libs/camanjs/package.json
Reference:
https://github.com/meltingice/CamanJS/commit/25502b14b5afe61d8180666313511a4a6498318a
> Add license info of camanjs, cc #5500

- ajax/libs/tipograf/1.0.2/tipograf.css
- ajax/libs/tipograf/1.0.2/tipograf.min.css
- ajax/libs/tipograf/package.json
PR for #9231 
@x09326 please help me review this pull request, thank you.
* Git repository (required): https://github.com/mightyCrow/tipograf
* Official website (optional, not the repository): https://mightycrow.github.io/tipograf/
* NPM package url (optional): https://www.npmjs.com/package/tipograf
- Count of stars: 96
- Count of watchers: 4
- Count of forks: 8
- Downloads in the last day: 6
- Downloads in the last week: 80
- Downloads in the last month: 105 …
> add tipograf@1.0.2 w/ npm auto-update

- ajax/libs/tweet/package.json
https://github.com/seaofclouds/tweet#licensed-under-the-mit
> Add license of tweet, cc #9248

- ajax/libs/noisy/package.json
https://github.com/DanielRapp/Noisy/blob/master/MIT-LICENSE.txt
> add license of noisy library, cc #9248

- ajax/libs/ie8/package.json
https://github.com/WebReflection/ie8/blob/master/LICENSE.txt
> Add license of ie8, cc #9248

- ajax/libs/feedback.js/package.json
https://github.com/niklasvh/feedback.js/blob/master/License
> Add license of feedback.js, cc #9248

- ajax/libs/swipe/package.json
https://github.com/thebird/Swipe/blob/master/LICENSE.md
> Add license of swipe ,cc #9248

- ajax/libs/cufon/package.json
https://github.com/sorccu/cufon/blob/master/LICENSE.txt
> Add license of cuff,cc #9248

- ajax/libs/flot/package.json
https://github.com/flot/flot/blob/master/LICENSE.txt
> Add license of flot, cc #9248

- ajax/libs/galleria/package.json
https://github.com/worseisbetter/galleria/blob/master/LICENSE
> Add license of galleria, cc #9248

- ajax/libs/knockout-postbox/package.json
https://github.com/rniemeyer/knockout-postbox/blob/master/LICENSE
> add license of knockout-postbox

- ajax/libs/vue-smart-table/package.json
https://github.com/gurghet/vue-smart-table/blob/master/LICENSE
> Add license of vue-smart-table, cc #9248

- ajax/libs/wysihtml5/package.json
https://github.com/xing/wysihtml5/blob/master/LICENSE
> Add a license of wysihtml5, cc #9248

- ajax/libs/ng-csv/package.json
https://github.com/asafdav/ng-csv/blob/master/LICENSE
> Add license of ng-csv, cc #9248

- ajax/libs/hashgrid/package.json
https://github.com/dotjay/hashgrid/blob/master/LICENSE
> Add license of hashgrid, cc #9248

- ajax/libs/cubism/package.json
https://github.com/square/cubism/blob/master/LICENSE
> Add a license of cubism, cc #9248

- ajax/libs/ng-prettyjson/0.2.0/ng-prettyjson.css
- ajax/libs/ng-prettyjson/0.2.0/ng-prettyjson.js
- ajax/libs/ng-prettyjson/0.2.0/ng-prettyjson.min.css
- ajax/libs/ng-prettyjson/0.2.0/ng-prettyjson.min.js
- ajax/libs/ng-prettyjson/package.json
PR for #9266 
* Git repository (required): https://github.com/darul75/ng-prettyjson
* Official website (optional, not the repository): https://darul75.github.io/ng-prettyjson/
* NPM package url (optional): https://www.npmjs.com/package/ng-prettyjson
- Count of stars: 53
- Count of forks: 27
- Downloads in the last day: 35
- Downloads in the last week: 236 …
> add ng-prettyjson@0.2.0 w/ npm autoupdate

- ajax/libs/qwery/package.json
https://github.com/ded/qwery/blob/master/LICENSE
> Add license of qwery, cc #9248

- ajax/libs/owl-carousel/package.json
http://owlgraphic.com/owlcarousel/
> Add license of owl-carousel, cc #9248

- ajax/libs/vertx/package.json
References at line 5:
https://github.com/eclipse/vert.x/blob/master/LICENSE-eplv10-aslv20.html
> Add license info of vertx, cc #5500

- ajax/libs/geo-location-javascript/package.json
https://code.google.com/archive/p/geo-location-javascript/
> Add license of geo-location-javascript, cc #9248

- ajax/libs/timezone-js/package.json
https://github.com/mde/timezone-js#license
> Add license of timezone-js, cc #5500

- ajax/libs/web-starter-kit/package.json
Reference: https://github.com/google/web-starter-kit/blob/master/LICENSE
> Add license of web-starter-kit, cc #5500

- ajax/libs/tinymce/package.json
Reference: https://github.com/tinymce/tinymce/blob/master/LICENSE.TXT
> Add license of tinymce, cc #5500

- ajax/libs/semantic-ui-react/package.json
@cdnjs/intern, @cdnjs/intern2
It's addition modification for https://github.com/cdnjs/cdnjs/issues/9503
Please help me review this pull request, thank you!
----
* Git repository (required): https://github.com/Semantic-Org/Semantic-UI-React
* Official website (optional, not the repository): http://react.semantic-ui.com
* NPM package url (optional): https://www.npmjs.com/package/semantic-ui-react
- Count of stars: **1037**
- Count of watchers: **80**
- Count of forks: **100**
* NPM download …
> Modify configs in package.json of semantic-ui-react

- ajax/libs/requirejs-plugins/package.json
https://github.com/millermedeiros/requirejs-plugins/blob/master/LICENSE.txt
> Add license of requirejs-plugins, cc #9248

- ajax/libs/jquery-textext/package.json
https://github.com/alexgorbatchev/jquery-textext/blob/master/MIT-LICENSE
> Add a license of jquery-textext, cc #5500

- ajax/libs/tablesort/package.json
https://github.com/tristen/tablesort/blob/gh-pages/LICENCE
> add license of tablesort, cc #9248

- ajax/libs/dragonbones/package.json
https://github.com/DragonBones/DragonBonesJS/blob/master/LICENSE
> add license of dragonbones

- ajax/libs/hyperform/package.json
* Git repository (required): https://github.com/hyperform/hyperform.git
* Official website (optional, not the repository): https://hyperform.js.org
* NPM package url (optional): https://www.npmjs.com/package/hyperform
- Count of stars: 394
- Downloads in the last day: 49
- Downloads in the last week: 582
- Downloads in the last month: 1294
**I'm not sure about the next points. Am I supposed to check them, or does the …
> Add Hyperform w/ npm autoupdate by package.json

- ajax/libs/mdbootstrap/package.json
Pull request for issue: #9531 
@x09326 @kennynaoh Please help me review this pull request, thank you.
use git auto-update instead of npm auto-update
close #9531
> transfer mdbootstrap to git auto-update

- ajax/libs/localStorage/package.json
https://github.com/mortzdk/localStorage/blob/master/LICENSE
This PR replace #9515.
> add license of localStorage, cc #9248

- ajax/libs/string_score/package.json
https://github.com/joshaven/string_score/blob/master/LICENSE.md
> Add license of string_score, cc #9248

- ajax/libs/stapes/package.json
https://github.com/hay/stapes/blob/master/stapes.js#L12
> add license of stapes

- ajax/libs/datejs/package.json
https://github.com/datejs/Datejs/blob/master/LICENSE
https://github.com/datejs/Datejs/blob/master/package.json
> add license to datejs, cc #5500

- ajax/libs/hinclude/package.json
https://github.com/mnot/hinclude/blob/master/LICENSE
> Add license of hinclude, cc #9248

- package.json
https://github.com/geraintluff/tv4#license
> add license info of tv4, cc #5500

- ajax/libs/libil/package.json
- package.json
https://github.com/lynxluna/libil/blob/master/README.md#license
> Add license info of libil, cc #5500

- ajax/libs/klass/package.json
- package.json
https://github.com/ded/klass/blob/master/README.md#LICENSE
> Add license info of klass, cc #5500

- ajax/libs/placeholders/package.json
- package.json
https://github.com/jamesallardice/Placeholders.js/blob/master/README.md
> Add license info of placeholders, cc #5500

- ajax/libs/require-css/package.json
https://github.com/guybedford/require-css/blob/master/LICENSE
> Add license of require-css, cc #5500

- ajax/libs/ReStable/0.1.2/jquery.restable.css
- ajax/libs/ReStable/0.1.2/jquery.restable.js
- ajax/libs/ReStable/0.1.2/jquery.restable.min.css
- ajax/libs/ReStable/0.1.2/jquery.restable.min.js
- ajax/libs/ReStable/package.json
Pull request for issue: #9590 
@kennynaoh Please help me review this pull requset, thanks.
* Git repository (required):https://github.com/micc83/ReStable
* Official website (optional, not the repository):https://codeb.it/restable
- Count of stars:171
- Count of watchers:6
- Count of forks:44
close #9590, cc @micc83
> Add ReStable@0.1.2 w/ git auto-update config

- ajax/libs/ng-clip/package.json
https://github.com/asafdav/ng-clip/edit/master/LICENSE
> Add license of ng-clip, cc #9248

- ajax/libs/numeral.js/1.5.3/languages.min.js
- ajax/libs/numeral.js/1.5.3/languages/be-nl.min.js
- ajax/libs/numeral.js/1.5.3/languages/chs.min.js
- ajax/libs/numeral.js/1.5.3/languages/cs.min.js
- ajax/libs/numeral.js/1.5.3/languages/da-dk.min.js
- ajax/libs/numeral.js/1.5.3/languages/de-ch.min.js
- ajax/libs/numeral.js/1.5.3/languages/de.min.js
- ajax/libs/numeral.js/1.5.3/languages/en-gb.min.js
- ajax/libs/numeral.js/1.5.3/languages/es-ES.min.js
- ajax/libs/numeral.js/1.5.3/languages/es.min.js
- ajax/libs/numeral.js/1.5.3/languages/et.min.js
- ajax/libs/numeral.js/1.5.3/languages/fi.min.js
- ajax/libs/numeral.js/1.5.3/languages/fr-CA.min.js
- ajax/libs/numeral.js/1.5.3/languages/fr-ch.min.js
- ajax/libs/numeral.js/1.5.3/languages/fr.min.js
- ajax/libs/numeral.js/1.5.3/languages/hu.min.js
- ajax/libs/numeral.js/1.5.3/languages/it.min.js
- ajax/libs/numeral.js/1.5.3/languages/ja.min.js
- ajax/libs/numeral.js/1.5.3/languages/nl-nl.min.js
- ajax/libs/numeral.js/1.5.3/languages/pl.min.js
- ajax/libs/numeral.js/1.5.3/languages/pt-br.min.js
- ajax/libs/numeral.js/1.5.3/languages/pt-pt.min.js
- ajax/libs/numeral.js/1.5.3/languages/ru-UA.min.js
- ajax/libs/numeral.js/1.5.3/languages/ru.min.js
- ajax/libs/numeral.js/1.5.3/languages/sk.min.js
- ajax/libs/numeral.js/1.5.3/languages/th.min.js
- ajax/libs/numeral.js/1.5.3/languages/tr.min.js
- ajax/libs/numeral.js/1.5.3/languages/uk-UA.min.js
- ajax/libs/numeral.js/package.json
PR for #9479 
@pvnr0082t please help me review this pull request, thanks!
update npmFileMap in package.json to grab languages directory automatically and add the languages files for the last added version.
> update auto-update cfg & add missing files of numeral.js

- ajax/libs/joopl/package.json
http://matiasfidemraizer.com/joopl/
> Add license of joopl, cc #5500

- ajax/libs/mycolorway-simple-hotkeys/package.json
https://github.com/mycolorway/simple-hotkeys/blob/master/LICENSE
> Add license of mycolorway-simple-hotkeys, cc #5500

- ajax/libs/github-repo-widget/package.json
https://github.com/JoelSutherland/GitHub-jQuery-Repo-Widget/blob/master/LICENSE
> add license github-repo-widget , cc #9248

- ajax/libs/knockout.mapping/package.json
https://github.com/SteveSanderson/knockout.mapping/blob/master/LICENSE
> add license of knockout.mapping, cc #9248

- ajax/libs/pubnub/package.json
https://github.com/pubnub/pubnub-api/blob/master/LICENSE
cc #5500, cc @x09326
> add license of pubnub

- ajax/libs/stylus/package.json
https://github.com/stylus/stylus/blob/dev/LICENSE
> add license of stylus, cc #5500

- ajax/libs/humane-js/package.json
Reference: https://github.com/wavded/humane-js/blob/master/readme.md#license
> Add license info of humane-js , cc #5500

- ajax/libs/ember-resource.js/package.json
* Git repository (required): https://github.com/zendesk/ember-resource/
- Count of stars: 143
- Count of watchers: 259
- Count of forks: 32
cc @staugaard @shajith @jish
> setup autoupdate for ember-resource.js

- ajax/libs/hiw-api/package.json
added license to hiw-api
https://github.com/HealthIndicators/js-api/blob/master/LICENSE.md
> add license to hiw-api

- ajax/libs/slidesjs/package.json
Reference: https://github.com/nathansearles/Slides#license
> Add license of slidesjs, cc #5500

- ajax/libs/flexie/package.json
Reference: https://github.com/doctyper/flexie#copyright-and-software-license
cc #9248
> Add license of flexie, cc #9248

- ajax/libs/requirejs-async/package.json
Reference: https://github.com/millermedeiros/requirejs-plugins/blob/master/LICENSE.txt
> Add license info of requirejs-async, cc #5500

- ajax/libs/easyXDM/package.json
Reference: https://github.com/oyvindkinsey/easyXDM/blob/master/MIT-license.txt
> Add license info of easyXDM, cc #5500

- ajax/libs/s3colors/package.json
Reference: https://github.com/Shaz3e/S3-Colors/blob/master/LICENSE
> Add license info of s3colors, cc #5500

- ajax/libs/taskforce/package.json
Reference: https://github.com/tfrce/project-megaphone/blob/gh-pages/COPYING
cc #5500
> Add license of taskforce, cc #5500

- ajax/libs/scriptaculous/package.json
Reference: https://github.com/madrobby/scriptaculous#license
cc #5500
> Add license of scriptaculous, cc #5500

- ajax/libs/jqcloud/package.json
Reference:
https://github.com/lucaong/jQCloud/blob/master/LICENSE.txt
> Add license of jqcloud, cc #5500

- ajax/libs/graphael/package.json
https://github.com/DmitryBaranovskiy/g.raphael/blob/b0290afa10307ed79e6fc77a19688557e1978edc/g.bar.js
https://github.com/DmitryBaranovskiy/g.raphael/blob/b0290afa10307ed79e6fc77a19688557e1978edc/g.dot.js
https://github.com/DmitryBaranovskiy/g.raphael/blob/b0290afa10307ed79e6fc77a19688557e1978edc/g.line.js
https://github.com/DmitryBaranovskiy/g.raphael/blob/b0290afa10307ed79e6fc77a19688557e1978edc/g.pie.js
> Add a license of graphael, cc #5500

- ajax/libs/zingchart/package.json
Reference:
https://www.zingchart.com/buy/
> Add license of zingchart, cc #5500

- ajax/libs/hydna/package.json
https://github.com/hydna/hydnajs/blob/75535be49fbe9d8405288c493573fe205af542de/dist/hydna.js#L306
> Add a license of hydna, cc #5500

- ajax/libs/jqueryui-touch-punch/package.json
cc #5500, Reference: https://github.com/furf/jquery-ui-touch-punch/blob/master/README.md @kennynaoh
> Add licenses of jqueryui-touch-punch

- ajax/libs/selectivizr/package.json
https://github.com/keithclark/selectivizr/blob/master/selectivizr.js#L3
I have corrected already .please review
@pvnr0082t
> add license of selectivizr, cc #5500

- ajax/libs/swfobject/package.json
Reference: https://github.com/swfobject/swfobject/blob/master/LICENSE
> Add license of swfobject, cc #5500

- ajax/libs/kartograph-js/package.json
license ref: https://github.com/kartograph/kartograph.js/blob/master/LICENSE
> add license kartograph-js, cc #5500

- ajax/libs/treesaver/package.json
Reference: https://github.com/Treesaver/treesaver
> Add license of treesaver, cc #5500

- ajax/libs/kiss.animate/package.json
license ref: https://github.com/daogurtsov/KISS.Animate/blob/master/MIT-LICENSE.txt
> add license kiss.animate, cc #5500

- ajax/libs/datepick/package.json
cc #5500, cc @pvnr0082t
Please help me review.
Thanks.
> Correct license typo of datepick

- ajax/libs/zoomove/1.2.1/zoomove.min.css
- ajax/libs/zoomove/1.2.1/zoomove.min.js
- ajax/libs/zoomove/package.json
Pull request for #9255 
* Git repository (required): https://github.com/thompsonemerson/zoomove
* Official website (optional, not the repository): http://thompsonemerson.github.io/zoomove
* NPM package url (optional): https://www.npmjs.com/package/zoomove
- Count of stars: 110
- Count of forks: 29
- Downloads in the last day: 2
- Downloads in the last week: 7
- Downloads in the last month: 83
close #9255, cc @thompsonemerson
> Add ZooMove@1.2.1 w/ npm autoupdate

- ajax/libs/dragdealer/package.json
https://github.com/skidding/dragdealer/blob/master/dragdealer
@nolsherry
> Add license of dragdealer , cc #9248

- ajax/libs/jquery-jkit/package.json
https://github.com/FrediBach/jQuery-jKit/blob/master/license.txt
@pvnr0082t
> Add license of jquery-jkit, cc #5500

- ajax/libs/polymaps/package.json
reference: https://github.com/simplegeo/polymaps/blob/master/LICENSE
> add license of polymaps, cc #5500

- ajax/libs/taskforce/package.json
Keywords of taskforce are previously empty, which is lack of good search performance. Accordingly, add keywords of taskforce to improve it.
> Add keywords of taskforce

- ajax/libs/prettyCheckable/package.json
Add license of prettyCheckable.
ref: http://arthurgouveia.com/prettyCheckable/
The license link is located at the bottom right of the page.
> Add license of prettyCheckable, cc #5500

- ajax/libs/money.js/package.json
Reference: https://github.com/openexchangerates/money.js/blob/master/money.js
@kennynaoh   Please review this PR. Thanks!
> Add license of money.js, cc #5500

- ajax/libs/helium-css/package.json
Ref: https://github.com/geuis/helium-css/blob/master/helium.js
> Add license of helium-css, cc #5500

- ajax/libs/jquery.ba-bbq/package.json
Reference: https://github.com/cowboy/jquery-bbq/blob/master/README.markdown#license
> Add license info of jquery.ba-bbq, cc #5500

- ajax/libs/jquery.atmosphere/package.json
Reference: https://github.com/Atmosphere/atmosphere-javascript/blob/master/LICENSE
> Add license info of jquery.atmosphere, cc #5500

- ajax/libs/jquery-history/package.json
Reference: https://github.com/tkyk/jquery-history-plugin/blob/master/jquery.history.js
> Add license of jquery-history, cc #5500

- ajax/libs/dd_belatedpng/package.json
Reference: http://www.dillerdesign.com/experiment/DD_belatedPNG/
> Add license of dd_belatedpng, cc #5500

- ajax/libs/jquery-gamequery/package.json
Reference: http://gamequeryjs.com/
> Add license of jquery-gamequery, cc #5500

- ajax/libs/jeditable.js/package.json
Ref: https://github.com/tuupola/jquery_jeditable/blob/master/jquery.jeditable.js#L6
> Add license of jeditable.js, cc #5500

- ajax/libs/jquery.fileDownload/package.json
Reference: https://github.com/johnculviner/jquery.fileDownload/blob/master/LICENSE
> Add license info of jquery.fileDownload, cc #5500

- ajax/libs/jquery.spritely/package.json
Reference: https://github.com/artlogicmedia/spritely/blob/master/README.md#license
> Add license info of jquery.spritely, cc #5500

- ajax/libs/jschannel/package.json
Reference: https://github.com/mozilla/jschannel#license
> Add license info of jschannel, cc #5500

- ajax/libs/lettering.js/package.json
https://github.com/davatron5000/Lettering.js/blob/master/jquery.lettering.js#L6
> Add license of lettering.js, cc #5500

- ajax/libs/diff_match_patch/package.json
Reference: https://code.google.com/p/google-diff-match-patch/
> Add license of diff_match_patch, cc #5500

- ajax/libs/ext-core/package.json
https://github.com/MikhailTatsky/ext-core/blob/ext-core-3.1/src/ext-core.jsb#L2
@pvnr0082t 
Please review this
> Add license of ext-core, cc #5500

- ajax/libs/prefixfree/package.json
reference: https://github.com/LeaVerou/prefixfree/blob/gh-pages/bower.json#L10
> Add license of prefixfree, cc #5500

- ajax/libs/path.js/package.json
reference:
https://github.com/mtrpcic/pathjs#copyright-and-licensing
> Add license of path.js, cc #5500

- ajax/libs/kiwi/package.json
reference:
https://github.com/coolony/kiwi#license
> Add license of kiwi, cc #5500

- ajax/libs/jshashes/package.json
> jshashes - fix github link

- ajax/libs/labjs/package.json
ref: https://github.com/getify/LABjs/blob/master/LAB.js#L3
> Add license of LAB.js

- ajax/libs/toxiclibsjs/package.json
https://github.com/hapticdata/toxiclibsjs/blob/master/LICENSE.txt
> Add license of toxiclibsjs, cc #5500

- ajax/libs/jquery.customSelect/package.json
Reference:
https://github.com/adamcoulombe/jquery.customSelect/blob/master/jquery.customSelect.js#L7
https://github.com/adamcoulombe/jquery.customSelect/blob/master/jquery.customSelect.js#L8
> Add licenses of jquery.customSelect, cc #5500

- ajax/libs/jquery-resize/package.json
Reference: http://benalman.com/about/license/
> Add license of jquery-resize, cc #5500

- ajax/libs/r2d3/package.json
ref: https://github.com/mhemesath/r2d3/blob/master/LICENSE
> Add license of r2d3, cc #5500

- ajax/libs/zumper-angular-payments/1.0.7/angular-payments.js
- ajax/libs/zumper-angular-payments/1.0.7/angular-payments.min.js
- ajax/libs/zumper-angular-payments/package.json
Pull request for issue: #9811 
@pvnr0082t please help me review this PR, thank you.
* Git repository (required): https://github.com/zumper/angular-payments
* NPM package url (optional): https://www.npmjs.com/package/angular-payments
- Count of stars: 4
- Count of watchers: 29
- Count of forks: 254
- Downloads in the last day: 106
- Downloads in the last week: 520 …
> add zumper-angular-payments@1.0.7 w/ git auto-update

- ajax/libs/MinPubSub/0.0.2/minpubsub.js
- ajax/libs/MinPubSub/0.0.2/minpubsub.src.js
- ajax/libs/MinPubSub/package.json
Pull request for issue: #8658
Related issue(s): #9414
* Git repository (required): https://github.com/daniellmb/MinPubSub
* NPM package url (optional): https://www.npmjs.com/package/minpubsub
- Count of stars: 201
- Count of watchers: 9
- Count of forks: 45
* NPM download stats (optional): 
- Downloads in the last day: 2
- Downloads in the last week: 9
- Downloads in the last month: 31
close #8658, cc #9414 @daniellmb
> Add MinPubSub@0.0.2 w/ npm auto-update

- documents/autoupdate.md
> Update auto-update document

- ajax/libs/stickyNavbar.js/1.3.4/jquery.stickyNavbar.js
- ajax/libs/stickyNavbar.js/1.3.4/jquery.stickyNavbar.min.js
- ajax/libs/stickyNavbar.js/package.json
Pull request for issue: #8413 
- Because we don't need `stickyNavbar.css` in old versions, I exclude it. 
Ref: https://github.com/jbutko/stickyNavbar.js/issues/50
- use git auto-update because there are 18 releases on GitHub but 4 on NPM
* Git repository (required):  https://github.com/jbutko/stickyNavbar.js
* Official website (optional, not the repository): https://www.jozefbutko.com/stickynavbar/
* NPM package url (optional): https://www.npmjs.com/package/stickyNavbar.js
* …
> Add stickyNavbar.js@1.3.4 w/ git auto-update

- ajax/libs/animejs/package.json
Pull request for issue: #9905
@Piicksarn @cdnjs/intern2 Could you please help me review this PR? Thanks!
> Change animejs to use git auto-update, close #9905

- ajax/libs/beepjs/package.json
Ref: https://github.com/luciferous/beepjs/blob/master/beep.js
@cdnjs/intern2  please help me review it, thanks.
> Add license of beepjs

- ajax/libs/onsen/package.json
@PeterDaveHello 
This is a fixed version of the PR #9970.
Could you review this PR?
----
* Git repository (required): https://github.com/OnsenUI/OnsenUI
* Official website (optional, not the repository): https://onsen.io/
* NPM package url (optional): https://www.npmjs.com/package/onsenui
- Count of stars: 3936
- Count of watchers: 254
- Count of forks: 537
- Downloads in the last day: 286 …
> Update auto-update config of onsen

- ajax/libs/infinity/package.json
Ref: https://github.com/airbnb/infinity/blob/master/LICENSE
@cdnjs/intern2  please help me review it, thanks.
> Add license of infinity

- spec/tools/fixFormatSpec.js
- test/valid-packages-test.js
- tools/fixFormat.js
Addresses issue: https://github.com/cdnjs/cdnjs/issues/9943
> Remove keys with leading underscore from package json

- ajax/libs/reading-time/1.0.0/readingTime.js
- ajax/libs/reading-time/1.0.0/readingTime.min.js
- ajax/libs/reading-time/package.json
close #9950, cc @michael-lynch
Pull request for issue: #9950 
@x09326  Please review this PR. Thanks!
* Git repository (required): https://github.com/michael-lynch/reading-time
* License and its reference: MIT  https://github.com/michael-lynch/reading-time/commit/14e894e9a1b0457fcbe9f0593f52f2ea432db9f5#diff-cab473f52840eb83e6884fc8712938dfL9
- Count of stars: 402
- …
> add reading-time@1.0.0 w/ git auto-update

- ajax/libs/jquery.swipebox/package.json
Reference: https://github.com/brutaldesign/swipebox/blob/master/grunt/package.json#L9
> Add license of jquery.swipebox, cc #5500

- ajax/libs/typeis/1.1.1/typeis.js
- ajax/libs/typeis/1.1.1/typeis.min.js
- ajax/libs/typeis/package.json
close #9339, cc @salihsagdilek
Pull request for issue: #9339
@x09326 Please help me review this PR. Thanks!
* Git repository (required): https://github.com/typeis/typeisjs
* Official website (optional, not the repository): https://typeis.github.io
* NPM package url (optional): https://www.npmjs.com/package/typeis
- Count of stars: 78
- …
> add typeis@1.1.1 w/ npm auto-update

- ajax/libs/angular-elastic-input/2.4.0/angular-elastic-input.js
- ajax/libs/angular-elastic-input/2.4.0/angular-elastic-input.min.js
- ajax/libs/angular-elastic-input/package.json
Pull request for issue: #9867
@pvnr0082t Please review this PR. Thank you.
* Git repository (required): https://github.com/jacek-pulit/angular-elastic-input
* Official website (optional, not the repository): https://jacek-pulit.github.io/angular-elastic-input/
* NPM package url (optional): https://www.npmjs.com/package/angular-elastic-input
* License and its reference: MIT license, Ref: https://github.com/jacek-pulit/angular-elastic-input/blob/master/LICENSE
- Count of …
> add angular-elastic-input@2.4.0 w/ git auto-update

- ajax/libs/what-input/package.json
Pull request for issue: #10168 
update npm auto-update config of what-input
**Git repository url:** https://github.com/ten1seven/what-input 
**NPM package url:** https://www.npmjs.com/package/what-input
> update npm auto-update config of what-input, close #10168

- ajax/libs/canvas-nest.js/package.json
Pull request for issue: #6590. Just for update canvas-nest.js 's source code folder.
* Git repository (required): https://github.com/hustcc/canvas-nest.js
- Count of stars: 523
- Count of watchers: 31
- Count of forks: 155
> [Author] update canvas-nest.js npm auto-update config

- ajax/libs/svg.js/package.json
> [AUTHOR] Update svg.js package.json

- ajax/libs/libphonenumber-js/package.json
A cleaner remake of the previously approved PR: https://github.com/cdnjs/cdnjs/pull/9963
> Add "libphonenumber-js" with single package.json

- ajax/libs/semantic-ui-calendar/package.json
Pull request for issue: #10229 
Checklist for **lib adding request issue** 
* Git repository (required): https://github.com/mdehoog/Semantic-UI-Calendar
* NPM package url (optional): https://www.npmjs.com/package/semantic-ui-calendar
- Count of stars: 149
- Count of watchers: 9
- Count of forks: 16
- Downloads in the last day: 9
- Downloads in the last week: 128
- Downloads in the last month: 490
* [ X ] This lib was not found on cdnjs repo
* [ X ] No already exist / duplicated issue and PR
* [ X] The lib has notable popularity
* [ X ] More than 100 [Stars / Watchers / Forks] on [GitHub / Bitbucket]
* [ almost ] More than 500 …
> add semantic-ui-calendar w/ git auto-update

- ajax/libs/ninjaui/package.json
Reference: https://github.com/ninja/ui/blob/master/LICENSE.txt
> Add license of ninjaui, cc #5500

- ajax/libs/mogl/package.json
Reference: https://github.com/projectBS/MoGL/blob/master/doc/0.2/Matrix_.md
> Add license of mogl, cc #5500

- ajax/libs/qoopido.demand/package.json
* Git repository (required): https://github.com/dlueth/qoopido.demand
* Official website (optional, not the repository): https://demand.qoopido.com/
* NPM package url (optional): https://www.npmjs.com/package/qoopido.demand
* GitHub / Bitbucket popularity (required): MIT OR GPL-3.0+
- Count of stars: 15
- Count of forks: 1
- Downloads in the last day: 9
- Downloads in the last week: 802 …
> [New] add qoopido.demand w/ single package.json

- ajax/libs/paper-css/package.json
* Git repository (required): https://github.com/cognitom/paper-css.git
* NPM package url (optional): http://npmjs.com/package/paper-css
- Count of stars: 173
- Count of forks: 9
- Downloads in the last week: 17
- Downloads in the last month: 116
> [new][author] Add paper-css by single package.json

- ajax/libs/jquery-animateNumber/0.0.14/jquery.animateNumber.js
- ajax/libs/jquery-animateNumber/0.0.14/jquery.animateNumber.min.js
- ajax/libs/jquery-animateNumber/package.json
close #9990, cc @aishek 
Pull request for issue: #9990
Related issue(s): # #9990
@nolsherry please help me to review the PR,thank you
* Git repository (required): https://github.com/aishek/jquery-animateNumber
* Official website (optional, not the repository): http://aishek.github.io/jquery-animateNumber
* NPM package url (optional):https://www.npmjs.com/package/jquery.animate-number
* License and its reference:MIT
- Count of stars: 460
- Count of watchers: 19
- Count of forks: 103
* NPM …
> add jquery-animateNumber@0.0.14 w/ git auto-update

- ajax/libs/qoopido.nucleus/package.json
* Git repository (required): https://github.com/dlueth/qoopido.nucleus
* Official website (optional, not the repository): https://nucleus.qoopido.com/
* NPM package url (optional): https://www.npmjs.com/package/qoopido.nucleus
* License and its reference: MIT (https://raw.githubusercontent.com/dlueth/qoopido.nucleus/master/LICENSE)
- Count of stars: 2
- Count of watchers: 1 …
> [New] add qoopido.nucleus w/ single package.json and npm auto-update

- ajax/libs/sockjs-client/package.json
Pull request for issue: n/a
Related issue(s): n/a
* Git repository (required): https://github.com/sockjs/sockjs-client
* NPM package url (optional): sockjs-client
- Count of watchers: 254
- Count of stars: 4579
- Count of forks: 601
> [author] sockjs-client: change to npm for autoupdate

- README.md
Draft of "Adding a library by a single package.json"
> Draft of "Adding a library by a single package.json"

- ajax/libs/classlist/package.json
* Git repository (required): https://github.com/eligrey/classList.js.git
* Official website (optional, not the repository): https://github.com/eligrey/classList.js
* License and its reference: Unlicense
- Count of watchers: 24
- Count of stars: 807
- Count of forks: 172
> Add git autoupdate to classlist

- ajax/libs/tablefilter/package.json
reference: http://tablefilter.free.fr/
> Add license of tablefilter, cc #5500

- ajax/libs/mediaelement-plugins/package.json
* Git repository (required): https://github.com/johndyer/mediaelement-plugins
- Count of stars: 2
> Add MediaElement Plugins by single package.json w/ git auto-update

- ajax/libs/vega/package.json
Supercedes https://github.com/cdnjs/cdnjs/pull/10535
cc @PeterDaveHello
> Update Vega auto-update config for v3 & author info

- ajax/libs/amcharts/package.json
**git repo url:** https://github.com/amcharts/amcharts3
**Watch 4
Star 7
Fork 3**
@Amomo  could u help me check this PR for #5337 ? thank you!
> Update Amcharts auto-update config and meta data

- ajax/libs/interactive-data-display/package.json
* Git repository (required): https://github.com/predictionmachines/InteractiveDataDisplay
* License and its reference: Apache-2.0 (https://github.com/predictionmachines/InteractiveDataDisplay/blob/master/LICENSE)
- Count of stars: 33
- Count of forks: 18 …
> [new] Add InteractiveDataDisplay w/ git auto-update

- ajax/libs/openlayers/package.json
> [author] add OpenLayers auto-update config, update license, keywords

- ajax/libs/hyperapp/package.json
Pull request for issue:  #10498
Related issue(s): https://github.com/cdnjs/cdnjs/pull/10608
* Git repository (required): https://github.com/hyperapp/hyperapp
* NPM package url (optional): https://www.npmjs.com/package/hyperapp
* License and its reference: https://github.com/hyperapp/hyperapp/blob/master/LICENSE
* Count of watchers: 43
* Count of stars: 1205
* Count of forks: 71
* Downloads in the last day: 262 …
> Add hyperapp by single package.json w/ npm auto-update

- ajax/libs/academicons/package.json
~~Pull request for issue: #~~
~~Related issue(s): # #~~
* Git repository (required): https://github.com/jpswalsh/academicons.git
* Official website (optional, not the repository): https://jpswalsh.github.io/academicons/
* License and its reference: [SIL OFL 1.1](http://scripts.sil.org/OFL), [MIT](http://opensource.org/licenses/mit-license.html)
- Count of stars: 146
- Count of forks: 16
Removed "version" from packages.json so no assets included ( #7793 )
> Add academicons by single package.json w/ git auto-update

- ajax/libs/scrolldir/1.2.2/scrolldir.auto.js
- ajax/libs/scrolldir/1.2.2/scrolldir.auto.min.js
- ajax/libs/scrolldir/1.2.2/scrolldir.js
- ajax/libs/scrolldir/1.2.2/scrolldir.min.js
- ajax/libs/scrolldir/package.json
Pull request for issue: #10657 
Note that if you are using a distribution purpose repository/package, please also provide the URL and other related info like the popularity of the source code repo/package.
* Git repository (required): https://github.com/dollarshaveclub/scrolldir
* Official website (optional, not the repository): https://dollarshaveclub.github.io/scrolldir/
* NPM package url (optional): https://www.npmjs.com/package/scrolldir
* License and its reference:  MIT
- Count of stars: 94
- Count of forks: 1
- Downloads in the last day: 95
- Downloads in the last week: 679
- …
> Add scrolldir@1.2.2 w/ npm auto-update

- ajax/libs/jquery-one-page-nav/package.json
Reference: https://github.com/davist11/jQuery-One-Page-Nav/blob/master/jquery.nav.js#L6
> Add license info of jquery-one-page-nav, cc #5500

- ajax/libs/mdbootstrap/4.3.0/img/svg/arrow_left.svg
- ajax/libs/mdbootstrap/4.3.0/img/svg/arrow_right.svg
- ajax/libs/mdbootstrap/package.json
Pull request for issue: #10432 
* Git repository (required): https://github.com/mdbootstrap/bootstrap-material-design
* Official website (optional, not the repository): https://mdbootstrap.com/material-design-for-bootstrap/
* NPM package url (optional): https://www.npmjs.com/package/mdbootstrap
* License and its reference: [MIT](https://mdbootstrap.com/license/)
- Count of watchers: 47
- Count of stars: 737
- Count of forks: 137
- Downloads in the last day: 41 …
> Update mdbootstrap v4.3.0 files and auto-update config

- ajax/libs/lazyload/package.json
ref: https://github.com/rgrove/lazyload/blob/master/LICENSE
> Add license of lazyload, cc #5500

- ajax/libs/Leaflet.EasyButton/package.json
Pull request for issue: #10739
* Git repository: https://github.com/CliffCloud/Leaflet.EasyButton
* Official website: http://danielmontague.com/projects/easyButton.js/v1/examples/
* NPM package url: https://www.npmjs.com/package/leaflet-easybutton
* License and its reference: https://github.com/CliffCloud/Leaflet.EasyButton/blob/master/LICENSE
- Count of stars: 195
- Count of forks: 59 …
> Add Leaflet.EasyButton w/ git auto-update via single package.json

- ajax/libs/float-label-css/package.json
* Git repository (required): https://github.com/tonystar/float-label-css
* NPM package url (optional):https://www.npmjs.com/package/float-label-css
- Count of stars: 44
- Count of forks: 4
- Downloads in the last day: 17
- Downloads in the last week: 104
- Downloads in the last month: 403
> [author] Add float-label-css via single package.json w/ auto-update

- ajax/libs/vega-lite/package.json
https://github.com/vega/vega-lite/pull/1957
> Update auto-update config of Vega-Lite

- ajax/libs/jquery.form/package.json
Pull request for issue: #10683
* Git repository (required):  https://github.com/jquery-form/form
* Official website (optional, not the repository):  https://jquery-form.github.io/form/
* NPM package url (optional):  jquery-form
* License and its reference:  MIT OR LGPL-3.0
- Count of watchers:  249
- Count of stars:  3,911
- Count of forks:  1,194
- Downloads in the last day:  71
- Downloads in the last week:  2,185
- Downloads in the last month:  12,288
> Update package.json of jquery.form

- ajax/libs/gotem/package.json
Pull request for issue: #10509
* Git repository (required): https://github.com/callmecavs/gotem
* NPM package url (optional): https://www.npmjs.com/package/gotem
* License and its reference: [MIT](https://github.com/callmecavs/gotem#license)
- Count of stars: 386
- Count of forks: 8
- Downloads in the last week: 2 
- Downloads in the last month: 58 …
> Add gotem w/ npm auto-update via single package.json

- ajax/libs/transformation-matrix-js/package.json
Pull request for issue: #10763
* Git repository (required): https://gitlab.com/epistemex/transformation-matrix-js.git
* NPM package url (optional): https://www.npmjs.com/package/transformation-matrix-js
* License and its reference: [MIT](https://gitlab.com/epistemex/transformation-matrix-js#license)
- Count of watchers: 0
- Count of stars: 0
- Downloads in the last day: 284
- Downloads in the last week: 1,341 …
> Add transformation-matrix-js w/ git auto-update via single package.json

- ajax/libs/mobi.css/package.json
We have created a new organization for Mobi.css
The repo url has changed from
`git+https://github.com/xcatliu/mobi.css.git`
to
`git+https://github.com/mobi-css/mobi.css.git`
* Git repository (required): https://github.com/mobi-css/mobi.css
* Official website (optional, not the repository): http://getmobicss.com
* NPM package url (optional): https://www.npmjs.com/package/mobi.css
- Count of watchers: 87
- Count of stars: 2059
- Count of forks: 160
* NPM …
> Move mobi.css from personal repo to organization

- ajax/libs/twbuttons/package.json
Pull request for issue: n/a
Related issue(s): https://github.com/onokumus/twbuttons/issues/1
* Git repository (required): https://github.com/onokumus/twbuttons
* Official website (optional, not the repository): https://onokumus.github.io/twbuttons/
* NPM package url (optional): https://www.npmjs.com/package/twbuttons
- Count of stars: 19
- Downloads in the last day: 1 
- Downloads in …
> Add twbuttons w/ git auto-update via single package.json

- ajax/libs/social-likes/package.json
@cdnjs/intern2 Please help me review this PR, thanks.
Pull request for issue: #10845
* GitHub / Bitbucket popularity:
Watch 82
Star 1,100
Fork 268
* NPM download stats:
12 downloads in the last day
124 downloads in the last week
390 downloads in the last month
> Update social-likes auto-update filemap

- ajax/libs/autonumeric/package.json
Update the package.json with the file structure of 2.0 onward
* Git repository (required): https://github.com/BobKnothe/autoNumeric/
* Official website (optional, not the repository): http://www.decorplanit.com/plugin/
* NPM package url (optional): https://www.npmjs.com/package/autonumeric
* License and its reference: MIT, https://github.com/BobKnothe/autoNumeric/blob/master/LICENSE
- Count of watchers: 51
- Count of stars: 576
- Count of forks: 271
- Downloads in the last month: 6315
> Update autoNumeric package.json and autoupdate config

- ajax/libs/jquery-te/package.json
https://github.com/fattihkoca/jQuery-TE/blob/master/jQuery-TE_v.1.3.2/GPL-LICENSE.txt
> Add license of jquery-te, cc #5500

- ajax/libs/lobipanel/package.json
Pull request for issue: #10738
* Git repository (required): https://github.com/arboshiki/lobipanel
* Official website (optional, not the repository): https://lobianijs.com/site/lobipanel
* License and its reference: [MIT](https://github.com/arboshiki/lobipanel/blob/master/LICENSE)
- Count of stars: 107
- Count of forks: 31
> Add lobipanel w/ git auto-update via single package.json

- ajax/libs/gibon/package.json
Pull request for issue: #10651 
* Git repository (required): https://github.com/tunnckoCore/gibon
* NPM package url (optional): https://www.npmjs.com/package/gibon
- Count of watchers: 15
- Count of stars: 392
- Count of forks: 12
- Downloads in the last day: 1
- Downloads in the last week: 17
- Downloads in the last month: 253
> Add gibon w/ npm auto-update via single package.json

- ajax/libs/owl-carousel/package.json
This domain is being used to redirect to sometimes malicious content.
> [Security] Do not link to http://owlgraphic.com

- ajax/libs/fitvids/package.json
Pull request for issue: #10476 
* Git repository (required):https://github.com/davatron5000/FitVids.js
> Add git auto-update config of fitvids

- ajax/libs/downloadjs/package.json
- ajax/libs/legojs/package.json
- ajax/libs/radiobox.css/package.json
- ajax/libs/skel-layers/package.json
> Update out-date library repository info

- ajax/libs/mediaelement/package.json
> [Author] Update MediaElement package info

- ajax/libs/progressively/package.json
Pull request for issue: #10115
* Git repository (required): https://github.com/thinker3197/progressively
* Official website (optional, not the repository): https://thinker3197.github.io/progressively
* NPM package url (optional): https://www.npmjs.com/package/progressively
- Count of stars: 358
- Count of forks: 37
- Downloads in the last day: 7
- Downloads in the last week: 33
- …
> Add progressively w/ npm auto-update via single package.json

- ajax/libs/jquery-layout/package.json
Ref: https://github.com/allpro/layout/blob/master/LICENSE.txt
@cdnjs/intern2  please help me review this, thanks.
> Add license of jquery-layout

- ajax/libs/togeojson/package.json
Pull request for issue: #10425
@cdnjs/intern3 Please help me on this PR. Thanks.
* Git repository (required): https://github.com/mapbox/togeojson
* Official website (optional, not the repository): http://mapbox.github.io/togeojson/
* NPM package url (optional): https://www.npmjs.com/package/togeojson
* License and its reference: BSD-2-Clause, ref: https://github.com/mapbox/togeojson/blob/master/LICENSE
- Count of watchers: 119
- Count of stars: 579
- Count of forks: 134 …
> Add togeojson via package.json w/ npm auto-update

- ajax/libs/mapbox-gl/package.json
Pull request for issue: #10654 (supersedes PR #10734, #10745, #10746, #10767)
* Git repository (required): https://github.com/mapbox/mapbox-gl-js
* Official website (optional, not the repository): https://www.mapbox.com/mapbox-gl-js/api/
* NPM package url (optional): https://www.npmjs.com/package/mapbox-gl
* License and its reference: [BSD-3-Clause](https://www.npmjs.com/package/mapbox-gl)
- Count of watchers: 221
- Count of stars: 1554
- Count of forks: 367
- Downloads in the last day: 962
- Downloads in the last week: 11352
- Downloads in the last month: 46516
> Add mapbox-gl via single package.json w/ npm auto-update

- ajax/libs/autonumeric/package.json
* Git repository (required): https://github.com/autoNumeric/autoNumeric
* NPM package url (optional): https://www.npmjs.com/package/autonumeric
> Update autoNumeric with its new github organization

- ajax/libs/jquery.touch/package.json
Pull request for issue: #10946
* Git repository (required): https://github.com/ajlkn/jquery.touch
- Count of stars: 127
- Count of forks: 36
> Add jquery.touch w/ git auto-update via single package.json

- ajax/libs/printThis/package.json
Pull request for issue: #10724 
@cdnjs/intern3 please help me review this PR, thanks!
* Git repository (required): https://github.com/jasonday/printThis
- Count of watchers: 47
- Count of stars: 290
- Count of forks: 198
> Add printThis via single package.json w/ git auto-update

- ajax/libs/roundSlider/package.json
Pull request for issue: #10110
* Git repository (required): https://github.com/soundar24/roundSlider
* Official website (optional, not the repository): http://roundsliderui.com/
* NPM package url (optional): 
- Count of stars: 113
- Count of forks: 33
> Add roundSlider w/ git auto-update via single package.json

- .gitignore
- ajax/libs/slim.js/package.json
Pull request for issue: #11007 
> [Author] Add slim.js via single package.json w/ npm auto-update

- ajax/libs/timelinejs/package.json
close #10540. The old GitHub repo is currently out of maintainence and moved to a new repo.
@cdnjs/intern3 Please help me review this PR, thanks!
Pull request for issue: #10540 
* Git repository (required):https://github.com/NUKnightLab/TimelineJS3
* Official website (optional, not the repository): http://timeline.knightlab.com/
* License and its reference: [MPL-2.0](https://github.com/NUKnightLab/TimelineJS3/blob/master/LICENSE)
- Count of watchers: 850
- Count of …
> Update timelinejs auto-update config & repository url
